Ads API .NET library: Google.Api.Ads.Dfp.Util.PreconditionUtilities Class Reference
Google.Api.Ads.Dfp.Util.PreconditionUtilities Class Reference
Static Public Member Functions
static void CheckArgumentNotNull (object value, string argument)
Utility method for null checking arguments.
Member Function Documentation
static void Google.Api.Ads.Dfp.Util.PreconditionUtilities.CheckArgumentNotNull (object value, string argument) inline static
Utility method for null checking arguments.
Parameters
obj The Object to check
argument The name of the argument being checked
Referenced by Google.Api.Ads.Dfp.Util.v201306.StatementBuilder.From(), Google.Api.Ads.Dfp.Util.v201311.StatementBuilder.From(), Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.From(), Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.From(), Google.Api.Ads.Dfp.Util.v201308.StatementBuilder.From(), Google.Api.Ads.Dfp.Util.v201403.StatementBuilder.From(), Google.Api.Ads.Dfp.Util.v201403.StatementBuilder.OrderBy(), Google.Api.Ads.Dfp.Util.v201308.StatementBuilder.OrderBy(), Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.OrderBy(), Google.Api.Ads.Dfp.Util.v201306.StatementBuilder.OrderBy(), Google.Api.Ads.Dfp.Util.v201311.StatementBuilder.OrderBy(), Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.OrderBy(), Google.Api.Ads.Dfp.Util.v201306.StatementBuilder.Select(), Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.Select(), Google.Api.Ads.Dfp.Util.v201311.StatementBuilder.Select(), Google.Api.Ads.Dfp.Util.v201308.StatementBuilder.Select(), Google.Api.Ads.Dfp.Util.v201403.StatementBuilder.Select(), Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.Select(), Google.Api.Ads.Dfp.Util.v201403.StatementBuilder.Where(), Google.Api.Ads.Dfp.Util.v201308.StatementBuilder.Where(), Google.Api.Ads.Dfp.Util.v201311.StatementBuilder.Where(), Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.Where(), Google.Api.Ads.Dfp.Util.v201306.StatementBuilder.Where(), and Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.Where().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/src/Common/Util/PreconditionUtilities.cs