Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywordIdeas Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywordIdeas Class Reference
This code example retrieves keywords that are related to a given keyword.
Public Member Functions
void Run (AdWordsUser user)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example retrieves keywords that are related to a given keyword.
Tags: TargetingIdeaService.get
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywordIdeas.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywordIdeas.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywordIdeas.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywordIdeas.Run (AdWordsUser user) inline
Runs the code example.
Parameters
user The AdWords user.
References Google.Api.Ads.AdWords.v201409.TargetingIdea.data, Google.Api.Ads.AdWords.v201409.TargetingIdeaPage.entries, Google.Api.Ads.AdWords.v201409.TargetingIdeaService.get(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201409.Criterion.id, Google.Api.Ads.AdWords.v201409.TargetingIdeaSelector.ideaType, Google.Api.Ads.AdWords.v201409.Type_AttributeMapEntry.key, Google.Api.Ads.AdWords.v201409.LanguageSearchParameter.languages, Google.Api.Ads.AdWords.v201409.Paging.numberResults, Google.Api.Ads.AdWords.v201409.TargetingIdeaSelector.paging, Google.Api.Ads.AdWords.v201409.RelatedToQuerySearchParameter.queries, Google.Api.Ads.AdWords.v201409.TargetingIdeaSelector.requestedAttributeTypes, Google.Api.Ads.AdWords.v201409.TargetingIdeaSelector.requestType, Google.Api.Ads.AdWords.v201409.TargetingIdeaSelector.searchParameters, Google.Api.Ads.AdWords.v201409.Paging.startIndex, Google.Api.Ads.AdWords.Lib.AdWordsService.v201409.TargetingIdeaService, Google.Api.Ads.AdWords.v201409.TargetingIdeaPage.totalNumEntries, Google.Api.Ads.AdWords.v201409.IntegerSetAttribute.value, and Google.Api.Ads.AdWords.v201409.Type_AttributeMapEntry.value.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywordIdeas.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywordIdeas.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywordIdeas.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201409/Optimization/GetKeywordIdeas.cs