Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywordsInBulk Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywordsInBulk Class Reference
This code example shows how to add keywords in bulk using the MutateJobService.
Public Member Functions
void Run (AdWordsUser user, long adGroupId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example shows how to add keywords in bulk using the MutateJobService.
Tags: MutateJobService.mutate, MutateJobService.get Tags: MutateJobService.getResult
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywordsInBulk.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywordsInBulk.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywordsInBulk.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywordsInBulk.Run (AdWordsUser user, long adGroupId) inline
Runs the code example.
Parameters
user The AdWords user.
adGroupId Id of the ad groups to which keywords are added.
References Google.Api.Ads.AdWords.v201402.AdGroupCriterion.adGroupId, Google.Api.Ads.AdWords.v201402.AdGroupCriterion.criterion, Google.Api.Ads.AdWords.v201402.SimpleMutateResult.errors, Google.Api.Ads.AdWords.v201402.ApiError.errorString, Google.Api.Ads.AdWords.v201402.Job.failureReason, Google.Api.Ads.AdWords.v201402.ApiError.fieldPath, Google.Api.Ads.AdWords.v201402.MutateJobService.get(), Google.Api.Ads.AdWords.v201402.MutateJobService.getResult(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.SimpleMutateJob.id, Google.Api.Ads.AdWords.v201402.Operand.Item, Google.Api.Ads.AdWords.v201402.JobResult.Item, Google.Api.Ads.AdWords.v201402.BulkMutateJobSelector.jobIds, Google.Api.Ads.AdWords.v201402.Keyword.matchType, Google.Api.Ads.AdWords.v201402.MutateJobService.mutate(), Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.MutateJobService, Google.Api.Ads.AdWords.v201402.AdGroupCriterionOperation.operand, Google.Api.Ads.AdWords.v201402.BulkMutateJobPolicy.prerequisiteJobIds, Google.Api.Ads.AdWords.v201402.SimpleMutateResult.results, Google.Api.Ads.AdWords.v201402.SimpleMutateJob.status, Google.Api.Ads.AdWords.v201402.Keyword.text, and Google.Api.Ads.AdWords.v201402.ApiError.trigger.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywordsInBulk.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywordsInBulk.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywordsInBulk.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201402/CampaignManagement/AddKeywordsInBulk.cs