Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds Class Reference
This code example adds third party redirect ads to an ad group. To get ad groups, run GetAdGroups.cs.
Public Member Functions
void Run (AdWordsUser user, long adGroupId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example adds third party redirect ads to an ad group. To get ad groups, run GetAdGroups.cs.
Tags: AdGroupAdService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds.Run (AdWordsUser user, long adGroupId) inline
Runs the code example.
Parameters
user The AdWords user.
adGroupId Id of the ad group to which ads are added.
References Google.Api.Ads.AdWords.v201406.AdGroupAd.ad, Google.Api.Ads.AdWords.v201406.RichMediaAd.adAttributes, Google.Api.Ads.AdWords.v201406.RichMediaAd.adDuration, Google.Api.Ads.AdWords.Lib.AdWordsService.v201406.AdGroupAdService, Google.Api.Ads.AdWords.v201406.AdGroupAd.adGroupId, Google.Api.Ads.AdWords.v201406.RichMediaAd.certifiedVendorFormatId, Google.Api.Ads.AdWords.v201406.RichMediaAd.dimensions, Google.Api.Ads.AdWords.v201406.ThirdPartyRedirectAd.expandingDirections, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetRandomString(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201406.Dimensions.height, Google.Api.Ads.AdWords.v201406.Ad.id, Google.Api.Ads.AdWords.v201406.ThirdPartyRedirectAd.isCookieTargeted, Google.Api.Ads.AdWords.v201406.ThirdPartyRedirectAd.isTagged, Google.Api.Ads.AdWords.v201406.ThirdPartyRedirectAd.isUserInterestTargeted, Google.Api.Ads.AdWords.v201406.RichMediaAd.name, Google.Api.Ads.AdWords.v201406.AdGroupAdOperation.operand, Google.Api.Ads.AdWords.v201406.RichMediaAd.richMediaAdType, Google.Api.Ads.AdWords.v201406.RichMediaAd.snippet, Google.Api.Ads.AdWords.v201406.RichMediaAd.sourceUrl, Google.Api.Ads.AdWords.v201406.Ad.url, Google.Api.Ads.AdWords.v201406.AdGroupAdReturnValue.value, and Google.Api.Ads.AdWords.v201406.Dimensions.width.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdXBuyer/CSharp/v201406/BasicOperations/AddThirdPartyRedirectAds.cs