Ads API .NET library: Google.Api.Ads.Common.Lib.AdsSoapClient Class Reference
Google.Api.Ads.Common.Lib.AdsSoapClient Class Reference
Base class for all SOAP services supported by this library.
Protected Member Functions
new object[] Invoke (string methodName, object[] parameters)
Invokes a SOAP service method synchronously using SOAP.
new IAsyncResult BeginInvoke (string methodName, object[] parameters, AsyncCallback callback, object asyncState)
Starts an asynchronous invocation of a SOAP service method using SOAP.
new object[] EndInvoke (IAsyncResult asyncResult)
Ends an asynchronous invocation of a SOAP service method using SOAP.
virtual void InitForCall (string methodName, object[] parameters)
Initializes the service before MakeApiCall.
virtual void CleanupAfterCall (string methodName, object[] parameters)
Cleans up the service after MakeApiCall.
virtual object[] MakeApiCall (string methodName, object[] parameters)
This method makes the actual SOAP API call. It is a thin wrapper over SOAPHttpClientProtocol:Invoke, and provide things like protection from race condition.
virtual ErrorHandler CreateErrorHandler ()
Creates the error handler.
virtual Exception GetCustomException (SoapException ex)
Gets a custom exception that wraps the SOAP exception thrown by the server.
override WebRequest GetWebRequest (Uri uri)
Creates a WebRequest instance for the specified url.
override WebResponse GetWebResponse (WebRequest request)
Returns a response from a synchronous request to an XML Web service method.
override WebResponse GetWebResponse (WebRequest request, IAsyncResult result)
Returns a response from an asynchronous request to a SOAP service method.
string GetDefaultNamespace ()
Gets the default XML namespace, based on the type of this object.
Static Protected Member Functions
static XmlElement GetFaultNode (SoapException exception, string ns, string nodeName)
Extracts the fault xml node from soap exception.
Properties
AdsUser User [get, set]
Gets or sets the AdsUser object that created this service.
ServiceSignature Signature [get, set]
Gets or sets the signature for this service.
WebRequest LastRequest [get, set]
Gets or sets the web request associated with this service's last API call.
WebResponse LastResponse [get, set]
Gets or sets the web response associated with this service's last API call.
Properties inherited from Google.Api.Ads.Common.Lib.AdsClient
string ConnectionGroupName [get, set]
Gets or sets the name of the connection group for the request.
ICredentials Credentials [get, set]
Gets or sets security credentials for client authentication.
bool PreAuthenticate [get, set]
Gets or sets whether pre-authentication is enabled.
Encoding RequestEncoding [get, set]
The System.Text.Encoding used to make the client request to the service.
int Timeout [get, set]
The timeout for the request.
string Url [get, set]
The url endpoint for the service.
bool UseDefaultCredentials [get, set]
Gets or sets whether this service should use the credentials from System.Net.CredentialCache.DefaultCredentials.
bool AllowAutoRedirect [get, set]
Gets or sets whether the client automatically follows server redirects.
X509CertificateCollection ClientCertificates [get]
Gets the collection of client certificates.
CookieContainer CookieContainer [get, set]
Gets or sets the collection of cookies.
bool EnableDecompression [get, set]
Gets or sets whether gzip compression is enabled.
IWebProxy Proxy [get, set]
Gets or sets proxy information for making a service request through a firewall.
bool UnsafeAuthenticatedConnectionSharing [get, set]
Gets or sets a value that indicates whether connection sharing is enabled when the client uses NTLM authentication to connect to the Web server that hosts the web service.
string UserAgent [get, set]
Gets or sets the value for the user agent header that is sent with each request.
AdsUser User [get, set]
Gets or sets the AdsUser object that created this service.
ServiceSignature Signature [get, set]
Gets or sets the signature for this service.
WebRequest LastRequest [get, set]
Gets or sets the web request associated with this service's last API call.
WebResponse LastResponse [get, set]
Gets or sets the web response associated with this service's last API call.
Detailed Description
Base class for all SOAP services supported by this library.
Member Function Documentation
new IAsyncResult Google.Api.Ads.Common.Lib.AdsSoapClient.BeginInvoke (string methodName, object[] parameters, AsyncCallback callback, object asyncState) inline protected
Starts an asynchronous invocation of a SOAP service method using SOAP.
Parameters
methodName The name of the SOAP service method in the derived class that is invoking BeginInvoke.
parameters An array of objects containing the parameters to pass to the SOAP service. The order of the values in the array correspond to the order of the parameters in the calling method of the derived class.
callback The delegate to call when the asynchronous invoke is complete.
asyncState Extra information supplied by the caller.
Returns
An IAsyncResult which is passed to EndInvoke to obtain the return values from the remote method call.
virtual void Google.Api.Ads.Common.Lib.AdsSoapClient.CleanupAfterCall (string methodName, object[] parameters) inline protected virtual
Cleans up the service after MakeApiCall.
Parameters
methodName Name of the method.
parameters The method parameters.
Reimplemented in Google.Api.Ads.Dfa.Lib.DfaSoapClient, and Google.Api.Ads.AdWords.Lib.AdWordsSoapClient.
References Google.Api.Ads.Common.Lib.ContextStore.RemoveKey().
virtual ErrorHandler Google.Api.Ads.Common.Lib.AdsSoapClient.CreateErrorHandler () inline protected virtual
Creates the error handler.
Returns
The error handler instance.
Reimplemented in Google.Api.Ads.Dfa.Lib.DfaSoapClient, and Google.Api.Ads.AdWords.Lib.AdWordsSoapClient.
new object [] Google.Api.Ads.Common.Lib.AdsSoapClient.EndInvoke (IAsyncResult asyncResult) inline protected
Ends an asynchronous invocation of a SOAP service method using SOAP.
Parameters
asyncResult The IAsyncResult returned from BeginInvoke.
Returns
An array of objects containing the return value and any by-reference or out parameters of the derived class method.
Exceptions
ArgumentNullException Thrown if asyncResult is null.
virtual Exception Google.Api.Ads.Common.Lib.AdsSoapClient.GetCustomException (SoapException ex) inline protected virtual
Gets a custom exception that wraps the SOAP exception thrown by the server.
Parameters
ex SOAPException that was thrown by the server.
Returns
A custom exception object that wraps the SOAP exception.
Any service that wishes to provide a custom exception should override this method.
Reimplemented in Google.Api.Ads.Dfa.Lib.DfaSoapClient, Google.Api.Ads.AdWords.Lib.AdWordsSoapClient, and Google.Api.Ads.Dfp.Lib.DfpSoapClient.
string Google.Api.Ads.Common.Lib.AdsSoapClient.GetDefaultNamespace () inline protected
Gets the default XML namespace, based on the type of this object.
Returns
The XML namespace to which this object is serialized, or an empty string if the method fails to retrieve the default namespace.
All the services making use of the XML Serialization framework (including ones generated by wsdl.exe and xsd.exe) will have a WebServiceBindingAttribute decoration, something like:
[System.Web.Services.WebServiceBindingAttribute(Name = "SomeServiceSoapBinding", Namespace = "https://the_xml_namespace_for_serializing")] public partial class SomeService : SoapHttpClientProtocol { ... }
The only exception to this rule is when we choose to write our own serialization framework, by implementing IXmlSerializable on AdsSoapClient. If and when someone does that, and someone were to call this method, then he/she will get an empty string from this method.
static XmlElement Google.Api.Ads.Common.Lib.AdsSoapClient.GetFaultNode (SoapException exception, string ns, string nodeName) inline static protected
Extracts the fault xml node from soap exception.
Parameters
exception The SOAP exception corresponding to the SOAP fault.
ns The xml namespace for the fault node.
nodeName The root node name for fault node.
Returns
The fault node.
override WebRequest Google.Api.Ads.Common.Lib.AdsSoapClient.GetWebRequest (Uri uri) inline protected
Creates a WebRequest instance for the specified url.
Parameters
uri The Uri to use when creating the WebRequest.
Returns
The WebRequest instance.
override WebResponse Google.Api.Ads.Common.Lib.AdsSoapClient.GetWebResponse (WebRequest request) inline protected
Returns a response from a synchronous request to an XML Web service method.
Parameters
request The System.Net.WebRequest from which to get the response.
Returns
The web response.
override WebResponse Google.Api.Ads.Common.Lib.AdsSoapClient.GetWebResponse (WebRequest request, IAsyncResult result) inline protected
Returns a response from an asynchronous request to a SOAP service method.
Parameters
request The System.Net.WebRequest from which to get the response.
result The System.IAsyncResult to pass to System.Net. HttpWebRequest.EndGetResponse(System.IAsyncResult) when the response has completed.
Returns
The web response.
virtual void Google.Api.Ads.Common.Lib.AdsSoapClient.InitForCall (string methodName, object[] parameters) inline protected virtual
Initializes the service before MakeApiCall.
Parameters
methodName Name of the method.
parameters The method parameters.
Reimplemented in Google.Api.Ads.Dfa.Lib.DfaSoapClient, Google.Api.Ads.Dfp.Lib.DfpSoapClient, and Google.Api.Ads.AdWords.Lib.AdWordsSoapClient.
References Google.Api.Ads.Common.Lib.ContextStore.AddKey().
new object [] Google.Api.Ads.Common.Lib.AdsSoapClient.Invoke (string methodName, object[] parameters) inline protected
Invokes a SOAP service method synchronously using SOAP.
Parameters
methodName The name of the SOAP service method in the derived class that is invoking BeginInvoke.
parameters An array of objects containing the parameters to pass to the SOAP service. The order of the values in the array correspond to the order of the parameters in the calling method of the derived class.
Returns
An array of objects containing the return value and any by reference or out parameters of the derived class method.
virtual object [] Google.Api.Ads.Common.Lib.AdsSoapClient.MakeApiCall (string methodName, object[] parameters) inline protected virtual
This method makes the actual SOAP API call. It is a thin wrapper over SOAPHttpClientProtocol:Invoke, and provide things like protection from race condition.
Parameters
methodName The name of the SOAP API method.
parameters The list of parameters for the SOAP API method.
Returns
The results from calling the SOAP API method.
References Google.Api.Ads.Common.Lib.ErrorHandler.PrepareForRetry(), and Google.Api.Ads.Common.Lib.ErrorHandler.ShouldRetry().
Property Documentation
WebRequest Google.Api.Ads.Common.Lib.AdsSoapClient.LastRequest get set
Gets or sets the web request associated with this service's last API call.
WebResponse Google.Api.Ads.Common.Lib.AdsSoapClient.LastResponse get set
Gets or sets the web response associated with this service's last API call.
ServiceSignature Google.Api.Ads.Common.Lib.AdsSoapClient.Signature get set
Gets or sets the signature for this service.
AdsUser Google.Api.Ads.Common.Lib.AdsSoapClient.User get set
Gets or sets the AdsUser object that created this service.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/src/Common/Lib/AdsSoapClient.cs