Ads API .NET library: Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileLineItem Class Reference
Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileLineItem Class Reference
This code example creates a new line item to serve to the mobile platform. Mobile features needs to be enabled in your account to use mobile targeting. To determine which line items exist, run GetAllLineItems.cs. To determine which orders exist, run GetAllOrders.cs. To determine which placements exist, run GetAllPlacements.cs.
Public Member Functions
override void Run (DfpUser user)
Run the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current time stamp.
Detailed Description
This code example creates a new line item to serve to the mobile platform. Mobile features needs to be enabled in your account to use mobile targeting. To determine which line items exist, run GetAllLineItems.cs. To determine which orders exist, run GetAllOrders.cs. To determine which placements exist, run GetAllPlacements.cs.
Tags: LineItemService.getLineItemsByStatement Tags: LineItemService.performLineItemAction
Member Function Documentation
static void Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileLineItem.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileLineItem.Run (DfpUser user) inline virtual
Run the code example.
Parameters
user The DFP user object running the code example.
Implements Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfp.v201403.LineItemSummary.allowOverbook, Google.Api.Ads.Dfp.v201403.LineItemSummary.costPerUnit, Google.Api.Ads.Dfp.v201403.LineItemSummary.costType, Google.Api.Ads.Dfp.v201403.LineItemService.createLineItems(), Google.Api.Ads.Dfp.v201403.LineItemSummary.creativePlaceholders, Google.Api.Ads.Dfp.v201403.LineItemSummary.creativeRotationType, Google.Api.Ads.Dfp.v201403.Money.currencyCode, Google.Api.Ads.Dfp.v201403.DeviceManufacturerTargeting.deviceManufacturers, Google.Api.Ads.Dfp.v201403.TechnologyTargeting.deviceManufacturerTargeting, Google.Api.Ads.Dfp.v201403.LineItemSummary.endDateTime, Google.Api.Ads.Dfp.Util.v201403.DateTimeUtilities.FromString(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfp.v201403.Size.height, Google.Api.Ads.Dfp.v201403.Technology.id, Google.Api.Ads.Dfp.v201403.LineItemSummary.id, Google.Api.Ads.Dfp.v201403.Targeting.inventoryTargeting, Google.Api.Ads.Dfp.v201403.Size.isAspectRatio, Google.Api.Ads.Dfp.v201403.DeviceManufacturerTargeting.isTargeted, Google.Api.Ads.Dfp.Lib.DfpService.v201403.LineItemService, Google.Api.Ads.Dfp.v201403.LineItemSummary.lineItemType, Google.Api.Ads.Dfp.v201403.Money.microAmount, Google.Api.Ads.Dfp.v201403.TechnologyTargeting.mobileDeviceSubmodelTargeting, Google.Api.Ads.Dfp.v201403.TechnologyTargeting.mobileDeviceTargeting, Google.Api.Ads.Dfp.v201403.LineItemSummary.name, Google.Api.Ads.Dfp.v201403.LineItemSummary.orderId, Google.Api.Ads.Dfp.v201403.CreativePlaceholder.size, Google.Api.Ads.Dfp.v201403.LineItemSummary.startDateTimeType, Google.Api.Ads.Dfp.v201403.MobileDeviceTargeting.targetedMobileDevices, Google.Api.Ads.Dfp.v201403.MobileDeviceSubmodelTargeting.targetedMobileDeviceSubmodels, Google.Api.Ads.Dfp.v201403.InventoryTargeting.targetedPlacementIds, Google.Api.Ads.Dfp.v201403.LineItem.targeting, Google.Api.Ads.Dfp.v201403.LineItemSummary.targetPlatform, Google.Api.Ads.Dfp.v201403.Targeting.technologyTargeting, Google.Api.Ads.Dfp.v201403.LineItemSummary.unitsBought, Google.Api.Ads.Dfp.v201403.LineItemSummary.unitType, and Google.Api.Ads.Dfp.v201403.Size.width.
Property Documentation
override string Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileLineItem.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfp/CSharp/v201403/LineItemService/CreateMobileLineItem.cs