Ads API .NET library: Google.Api.Ads.Dfp.Util.v201705.DateTimeUtilities Class Reference
Google.Api.Ads.Dfp.Util.v201705.DateTimeUtilities Class Reference
A utility class that allows you to build Datetime objects from strings.
Static Public Member Functions
static DfpDateTime FromString (string dateString, string timeZoneId)
Converts the string in format yyyyMMdd HH:mm:ss to a DateTime object with the specified time zone.
static DfpDateTime FromDateTime (System.DateTime dateTime, string timeZoneId)
Converts a System.DateTime object to a Dfp DateTime object with the specified timeZoneId. Does not perform time zone conversion. This means the returned DateTime value may not represent the same instant as the System.DateTime value.
static DfpDateTime FromDateTime (ZonedDateTime dateTime)
Converts a NodaTime.ZonedDateTime object to a Dfp DateTime object with its intrinsic timezone.
Detailed Description
A utility class that allows you to build Datetime objects from strings.
Member Function Documentation
static DfpDateTime Google.Api.Ads.Dfp.Util.v201705.DateTimeUtilities.FromDateTime (System.DateTime dateTime, string timeZoneId) inline static
Converts a System.DateTime object to a Dfp DateTime object with the specified timeZoneId. Does not perform time zone conversion. This means the returned DateTime value may not represent the same instant as the System.DateTime value.
Parameters
dateTime The DateTime object.
timeZoneId The timeZoneId to use.
Returns
A Dfp Datetime object.
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201705.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201705.GetOrdersStartingSoon.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201705.GetReconciliationReportForLastBillingPeriod.Run().
static DfpDateTime Google.Api.Ads.Dfp.Util.v201705.DateTimeUtilities.FromDateTime (ZonedDateTime dateTime) inline static
Converts a NodaTime.ZonedDateTime object to a Dfp DateTime object with its intrinsic timezone.
Parameters
dateTime The ZonedDateTime object.
Returns
A Dfp Datetime object.
static DfpDateTime Google.Api.Ads.Dfp.Util.v201705.DateTimeUtilities.FromString (string dateString, string timeZoneId) inline static
Converts the string in format yyyyMMdd HH:mm:ss to a DateTime object with the specified time zone.
Parameters
dateString The date string.
timeZoneId The timeZoneId to set.
Returns
A Dfp Datetime object.
The documentation for this class was generated from the following file:
/usr/local/google/users/cseeley/tmp/tmp.aw3Sqx33Br/dist/github/src/Dfp/Util/v201705/DateTimeUtilities.cs