Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddProductPartitionTree Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddProductPartitionTree Class Reference
This code example creates a ProductPartition tree.
Public Member Functions
void Run (AdWordsUser user, long adGroupId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example creates a ProductPartition tree.
Tags: AdGroupCriterionService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddProductPartitionTree.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddProductPartitionTree.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddProductPartitionTree.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddProductPartitionTree.Run (AdWordsUser user, long adGroupId) inline
Runs the code example.
Parameters
user The AdWords user.
adGroupId The ad group to which product partition is added.
References Google.Api.Ads.AdWords.Lib.AdWordsService.v201409.AdGroupCriterionService, Google.Api.Ads.AdWords.v201409.ProductCanonicalCondition.condition, Google.Api.Ads.AdWords.v201409.AdGroupCriterion.criterion, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201409.Criterion.id, Google.Api.Ads.AdWords.v201409.AdGroupCriterionService.mutate(), Google.Api.Ads.AdWords.v201409.ProductPartition.parentCriterionId, Google.Api.Ads.AdWords.v201409.ProductPartition.parentCriterionIdSpecified, Google.Api.Ads.AdWords.v201409.ProductBiddingCategory.type, Google.Api.Ads.AdWords.v201409.ProductBrand.value, and Google.Api.Ads.AdWords.v201409.ProductBiddingCategory.value.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddProductPartitionTree.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddProductPartitionTree.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddProductPartitionTree.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201409/ShoppingCampaigns/AddProductPartitionTree.cs