Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign Class Reference
This code example illustrates how to create a video campaign.
Public Member Functions
void Run (AdWordsUser user)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example illustrates how to create a video campaign.
Tags: VideoCampaignService.mutate, BudgetService.mutate
AdWords for Video API is a Beta feature.
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign.Run (AdWordsUser user) inline
Runs the code example.
Parameters
user The AdWords user.
References Google.Api.Ads.AdWords.v201402.Budget.amount, Google.Api.Ads.AdWords.v201402.Budget.budgetId, Google.Api.Ads.AdWords.v201402.VideoCampaign.budgetId, Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.BudgetService, Google.Api.Ads.AdWords.v201402.Budget.deliveryMethod, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetRandomString(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.VideoCampaign.id, Google.Api.Ads.AdWords.v201402.Money.microAmount, Google.Api.Ads.AdWords.v201402.BudgetService.mutate(), Google.Api.Ads.AdWords.v201402.VideoCampaignService.mutate(), Google.Api.Ads.AdWords.v201402.Budget.name, Google.Api.Ads.AdWords.v201402.VideoCampaign.name, Google.Api.Ads.AdWords.v201402.BudgetOperation.operand, Google.Api.Ads.AdWords.v201402.VideoCampaignOperation.operand, Google.Api.Ads.AdWords.v201402.Budget.period, Google.Api.Ads.AdWords.v201402.VideoCampaign.startDate, Google.Api.Ads.AdWords.v201402.VideoCampaign.status, Google.Api.Ads.AdWords.v201402.BudgetReturnValue.value, Google.Api.Ads.AdWords.v201402.VideoCampaignReturnValue.value, and Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.VideoCampaignService.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201402/AdWordsForVideo/AddVideoCampaign.cs