Ads API .NET library: Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders Class Reference
Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders Class Reference
This code example gets all orders. To create orders, run CreateOrders.cs.
Public Member Functions
override void Run (DfpUser user)
Run the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current time stamp.
Detailed Description
This code example gets all orders. To create orders, run CreateOrders.cs.
Tags: OrderService.getOrdersByStatement
Member Function Documentation
static void Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders.Run (DfpUser user) inline virtual
Run the code example.
Parameters
user The DFP user object running the code example.
Implements Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfp.v201408.Order.advertiserId, Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.GetOffset(), Google.Api.Ads.Dfp.v201408.OrderService.getOrdersByStatement(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfp.v201408.Order.id, Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.IncreaseOffsetBy(), Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.Limit(), Google.Api.Ads.Dfp.v201408.Order.name, Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.OrderBy(), Google.Api.Ads.Dfp.Lib.DfpService.v201408.OrderService, Google.Api.Ads.Dfp.v201408.OrderPage.results, Google.Api.Ads.Dfp.v201408.OrderPage.startIndex, Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.SUGGESTED_PAGE_LIMIT, Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.ToStatement(), and Google.Api.Ads.Dfp.v201408.OrderPage.totalResultSetSize.
Property Documentation
override string Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfp/CSharp/v201408/OrderService/GetAllOrders.cs