Ads API .NET library: Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateUser Class Reference
Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateUser Class Reference
This code example deactivates a user. Deactivated users can no longer make requests to the API. The user making the request cannot deactivate itself. To determine which users exist, run GetAllUsers.cs.
Public Member Functions
override void Run (DfpUser user)
Run the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current time stamp.
Detailed Description
This code example deactivates a user. Deactivated users can no longer make requests to the API. The user making the request cannot deactivate itself. To determine which users exist, run GetAllUsers.cs.
Tags: UserService.getUsersByStatement, UserService.performUserAction
Member Function Documentation
static void Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateUser.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateUser.Run (DfpUser user) inline virtual
Run the code example.
Parameters
user The DFP user object running the code example.
Implements Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.AddValue(), Google.Api.Ads.Dfp.v201405.UserRecord.email, Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.GetOffset(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfp.v201405.UserService.getUsersByStatement(), Google.Api.Ads.Dfp.v201405.UserRecord.id, Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.IncreaseOffsetBy(), Google.Api.Ads.Dfp.v201405.User.isActive, Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.Limit(), Google.Api.Ads.Dfp.v201405.UpdateResult.numChanges, Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.OrderBy(), Google.Api.Ads.Dfp.v201405.UserService.performUserAction(), Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.RemoveLimitAndOffset(), Google.Api.Ads.Dfp.v201405.UserPage.results, Google.Api.Ads.Dfp.v201405.UserPage.startIndex, Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.SUGGESTED_PAGE_LIMIT, Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.ToStatement(), Google.Api.Ads.Dfp.v201405.UserPage.totalResultSetSize, Google.Api.Ads.Dfp.Lib.DfpService.v201405.UserService, and Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.Where().
Property Documentation
override string Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateUser.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfp/CSharp/v201405/UserService/DeactivateUser.cs