Ads API .NET library: Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUserTeamAssociations Class Reference
Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUserTeamAssociations Class Reference
This code example updates user team associations by setting the overridden access type to read only for all teams that the user belongs to. To determine which users exists, run GetAllUsers.cs.
Public Member Functions
override void Run (DfpUser user)
Run the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current time stamp.
Detailed Description
This code example updates user team associations by setting the overridden access type to read only for all teams that the user belongs to. To determine which users exists, run GetAllUsers.cs.
Tags: UserTeamAssociationService.getUserTeamAssociationsByStatement Tags: UserTeamAssociationService.updateUserTeamAssociations
Member Function Documentation
static void Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUserTeamAssociations.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUserTeamAssociations.Run (DfpUser user) inline virtual
Run the code example.
Parameters
dfpUser The DFP user object running the code example.
Implements Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.AddValue(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfp.v201405.UserTeamAssociationService.getUserTeamAssociationsByStatement(), Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.Limit(), Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.OrderBy(), Google.Api.Ads.Dfp.v201405.UserRecordTeamAssociation.overriddenTeamAccessType, Google.Api.Ads.Dfp.v201405.UserTeamAssociationPage.results, Google.Api.Ads.Dfp.v201405.UserRecordTeamAssociation.teamId, Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.ToStatement(), Google.Api.Ads.Dfp.v201405.UserTeamAssociationService.updateUserTeamAssociations(), Google.Api.Ads.Dfp.v201405.UserTeamAssociation.userId, Google.Api.Ads.Dfp.Lib.DfpService.v201405.UserTeamAssociationService, and Google.Api.Ads.Dfp.Util.v201405.StatementBuilder.Where().
Property Documentation
override string Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUserTeamAssociations.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfp/CSharp/v201405/UserTeamAssociationService/UpdateUserTeamAssociations.cs