Ads API .NET library: Google.Api.Ads.Common.Lib.TraceListener Class Reference
Google.Api.Ads.Common.Lib.TraceListener Class Reference abstract
Listens to SOAP messages sent and received by this library.
Public Member Functions
void InitForCall ()
Initializes the listener for handling an API call.
void HandleMessage (XmlDocument soapMessage, AdsClient service, SoapMessageDirection direction)
Handles the SOAP message.
void CleanupAfterCall ()
Cleans up any resources after an API call.
Protected Member Functions
TraceListener (AppConfig config)
Protected constructor.
abstract ISet< string > GetFieldsToMask ()
Gets a list of fields to be masked in xml logs.
virtual string FormatHttpRequest (string soapRequest)
Creates a formatted http request text, to be written into HTTP logs.
virtual string FormatHttpResponse (string soapResponse)
Creates a formatted http response text, to be written into HTTP logs.
virtual string FormatSoapRequest (WebRequest webRequest, string soapRequest)
Creates a formatted soap request text, to be written into SOAP logs.
virtual string FormatSoapResponse (WebResponse webResponse, string soapResponse)
Creates a formatted soap response text, to be written into SOAP logs.
virtual string GetTimeStamp ()
Gets the current timestamp as a formatted string.
string AppendHeadersToSoapXml (string soapRequest, string headers)
Appends the HTTP headers to SOAP xml.
void MaskCredentialsInLogs (XmlDocument soapMessageXml, ISet< string > fieldNames)
Masks a list of fields in the SOAP message before logging it.
Properties
AppConfig Config [get]
Gets the config class to be used with this class.
Properties inherited from Google.Api.Ads.Common.Lib.Configurable
AppConfig Config [get]
Gets the application configuration class for this object.
Detailed Description
Listens to SOAP messages sent and received by this library.
Constructor & Destructor Documentation
Google.Api.Ads.Common.Lib.TraceListener.TraceListener (AppConfig config) inline protected
Protected constructor.
Parameters
config The config class.
Member Function Documentation
string Google.Api.Ads.Common.Lib.TraceListener.AppendHeadersToSoapXml (string soapRequest, string headers) inline protected
Appends the HTTP headers to SOAP xml.
Parameters
soapRequest The SOAP request.
headers The HTTP headers.
Returns
The modified SOAP xml for appending to the logs.
References Google.Api.Ads.Common.Util.SerializationUtilities.LoadXml().
void Google.Api.Ads.Common.Lib.TraceListener.CleanupAfterCall () inline
Cleans up any resources after an API call.
Implements Google.Api.Ads.Common.Lib.SoapListener.
References Google.Api.Ads.Common.Lib.ContextStore.RemoveKey().
virtual string Google.Api.Ads.Common.Lib.TraceListener.FormatHttpRequest (string soapRequest) inline protected virtual
Creates a formatted http request text, to be written into HTTP logs.
Parameters
soapRequest The request xml for this SOAP call.
Returns
A formatted string that represents the HTTP request.
Reimplemented in Google.Api.Ads.AdWords.Lib.AdWordsTraceListener, Google.Api.Ads.Common.Lib.DfaTraceListener, and Google.Api.Ads.Dfp.Lib.DfpTraceListener.
virtual string Google.Api.Ads.Common.Lib.TraceListener.FormatHttpResponse (string soapResponse) inline protected virtual
Creates a formatted http response text, to be written into HTTP logs.
Parameters
soapResponse The response xml for this SOAP call.
Returns
A formatted string that represents the HTTP response.
Reimplemented in Google.Api.Ads.AdWords.Lib.AdWordsTraceListener, Google.Api.Ads.Common.Lib.DfaTraceListener, and Google.Api.Ads.Dfp.Lib.DfpTraceListener.
virtual string Google.Api.Ads.Common.Lib.TraceListener.FormatSoapRequest (WebRequest webRequest, string soapRequest) inline protected virtual
Creates a formatted soap request text, to be written into SOAP logs.
Parameters
webRequest The web request for this SOAP call.
soapRequest The request xml for this SOAP call.
Returns
A formatted string that represents the SOAP request.
References Google.Api.Ads.Common.Lib.AppConfig.MaskCredentials.
virtual string Google.Api.Ads.Common.Lib.TraceListener.FormatSoapResponse (WebResponse webResponse, string soapResponse) inline protected virtual
Creates a formatted soap response text, to be written into SOAP logs.
Parameters
webResponse The web response for this SOAP call.
soapResponse The response xml for this SOAP call.
Returns
A formatted string that represents the SOAP response.
abstract ISet<string> Google.Api.Ads.Common.Lib.TraceListener.GetFieldsToMask () protected pure virtual
Gets a list of fields to be masked in xml logs.
Returns
The list of fields to be masked.
Implemented in Google.Api.Ads.AdWords.Lib.AdWordsTraceListener, Google.Api.Ads.Dfp.Lib.DfpTraceListener, and Google.Api.Ads.Common.Lib.DfaTraceListener.
virtual string Google.Api.Ads.Common.Lib.TraceListener.GetTimeStamp () inline protected virtual
Gets the current timestamp as a formatted string.
Returns
The current timestamp.
void Google.Api.Ads.Common.Lib.TraceListener.HandleMessage (XmlDocument soapMessage, AdsClient service, SoapMessageDirection direction) inline
Handles the SOAP message.
Parameters
soapMessage The SOAP message.
service The SOAP service.
direction The direction of message.
Implements Google.Api.Ads.Common.Lib.SoapListener.
References Google.Api.Ads.Common.Lib.ContextStore.AddKey(), and Google.Api.Ads.Common.Lib.ContextStore.GetValue().
void Google.Api.Ads.Common.Lib.TraceListener.InitForCall () inline
Initializes the listener for handling an API call.
Implements Google.Api.Ads.Common.Lib.SoapListener.
void Google.Api.Ads.Common.Lib.TraceListener.MaskCredentialsInLogs (XmlDocument soapMessageXml, ISet< string > fieldNames) inline protected
Masks a list of fields in the SOAP message before logging it.
Parameters
soapMessageXml The SOAP message, loaded as an XmlDocument.
fieldNames The list of field names to be masked.
Property Documentation
AppConfig Google.Api.Ads.Common.Lib.TraceListener.Config get
Gets the config class to be used with this class.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/src/Common/Lib/TraceListener.cs