Ads API .NET library: Google.Api.Ads.Common.Lib.ContextStore Class Reference
Google.Api.Ads.Common.Lib.ContextStore Class Reference
This class provides access to the call context, and hides the differences when the library is running as a web application or a normal application.
Static Public Member Functions
static void AddKey (string key, object value)
Adds a key-value pair to the context store.
static void RemoveKey (string key)
Removes a stored value from the context store.
static object GetValue (string key)
Gets the value of an item stored in the context store.
Detailed Description
This class provides access to the call context, and hides the differences when the library is running as a web application or a normal application.
Member Function Documentation
static void Google.Api.Ads.Common.Lib.ContextStore.AddKey (string key, object value) inline static
Adds a key-value pair to the context store.
Parameters
key The key for the value being stored.
value The value being stored.
static object Google.Api.Ads.Common.Lib.ContextStore.GetValue (string key) inline static
Gets the value of an item stored in the context store.
Parameters
key The key for which value should be retrieved.
Returns
The object's value, or null if the key is missing.
Referenced by Google.Api.Ads.Dfa.Lib.DfaSoapClient.CleanupAfterCall(), Google.Api.Ads.AdWords.Lib.AdWordsSoapClient.GetCustomException(), Google.Api.Ads.AdWords.Lib.AdWordsSoapClient.GetWebRequest(), Google.Api.Ads.Dfp.Lib.DfpSoapClient.GetWebRequest(), Google.Api.Ads.Dfa.Lib.DfaSoapClient.GetWebRequest(), Google.Api.Ads.Common.Logging.TraceListener.HandleMessage(), Google.Api.Ads.AdWords.Lib.AdWordsCallListener.HandleMessage(), and Google.Api.Ads.Dfa.Lib.SoapHeaderListener.HandleMessage().
static void Google.Api.Ads.Common.Lib.ContextStore.RemoveKey (string key) inline static
Removes a stored value from the context store.
Parameters
key The key for the value to be removed.
The documentation for this class was generated from the following file:
/tmp/tmp.F65L8O0niy/dist/github/src/Common/Lib/ContextStore.cs