Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria Class Reference
This code example adds various types of targeting criteria to a campaign. To get a list of campaigns, run GetCampaigns.cs.
Public Member Functions
void Run (AdWordsUser user, long campaignId)
Runs the code example.
void Run (AdWordsUser user, long campaignId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example adds various types of targeting criteria to a campaign. To get a list of campaigns, run GetCampaigns.cs.
Tags: CampaignCriterionService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria.Run().
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException().
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria.Run (AdWordsUser user, long campaignId) inline
Runs the code example.
Parameters
user The AdWords user.
campaignId Id of the campaign to which targeting criteria are added.
References Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.CampaignCriterionService, Google.Api.Ads.AdWords.v201402.CampaignCriterion.campaignId, Google.Api.Ads.AdWords.v201402.CampaignCriterion.criterion, Google.Api.Ads.AdWords.v201402.Criterion.CriterionType, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.Criterion.id, Google.Api.Ads.AdWords.v201402.CampaignCriterionOperation.operand, Google.Api.Ads.AdWords.v201402.Placement.url, and Google.Api.Ads.AdWords.v201402.CampaignCriterionReturnValue.value.
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria.Run (AdWordsUser user, long campaignId) inline
Runs the code example.
Parameters
user The AdWords user.
campaignId Id of the campaign to which targeting criteria are added.
References Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.CampaignCriterionService, Google.Api.Ads.AdWords.v201402.CampaignCriterion.campaignId, Google.Api.Ads.AdWords.v201402.PlacesOfInterestOperand.category, Google.Api.Ads.AdWords.v201402.CampaignCriterion.criterion, Google.Api.Ads.AdWords.v201402.Criterion.CriterionType, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.Criterion.id, Google.Api.Ads.AdWords.v201402.Function.lhsOperand, Google.Api.Ads.AdWords.v201402.GeoTargetOperand.locations, Google.Api.Ads.AdWords.v201402.LocationGroups.matchingFunction, Google.Api.Ads.AdWords.v201402.Keyword.matchType, Google.Api.Ads.AdWords.v201402.CampaignCriterionOperation.operand, Google.Api.Ads.AdWords.v201402.Function.rhsOperand, Google.Api.Ads.AdWords.v201402.Keyword.text, Google.Api.Ads.AdWords.v201402.IncomeOperand.tier, and Google.Api.Ads.AdWords.v201402.CampaignCriterionReturnValue.value.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201402/Targeting/AddCampaignTargetingCriteria.cs