Ads API .NET library: Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory Class Reference
Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory Class Reference
This code example gets all active content categorized as "comedy" using the network's content browse custom targeting key. This feature is only available to DFP video publishers.
Public Member Functions
override void Run (DfpUser user)
Run the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current time stamp.
Detailed Description
This code example gets all active content categorized as "comedy" using the network's content browse custom targeting key. This feature is only available to DFP video publishers.
Tags: NetworkService.getCurrentNetwork Tags: CustomTargetingService.getCustomTargetingValuesByStatement Tags: ContentService.getContentByStatementAndCustomTargetingValue ///
Member Function Documentation
static void Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Run (DfpUser user) inline virtual
Run the code example.
Parameters
user The DFP user object running the code example.
Implements Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.AddValue(), Google.Api.Ads.Dfp.v201408.Network.contentBrowseCustomTargetingKeyId, Google.Api.Ads.Dfp.Lib.DfpService.v201408.ContentService, Google.Api.Ads.Dfp.Lib.DfpService.v201408.CustomTargetingService, Google.Api.Ads.Dfp.v201408.ContentService.getContentByStatementAndCustomTargetingValue(), Google.Api.Ads.Dfp.v201408.NetworkService.getCurrentNetwork(), Google.Api.Ads.Dfp.v201408.CustomTargetingService.getCustomTargetingValuesByStatement(), Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.GetOffset(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfp.v201408.CustomTargetingValue.id, Google.Api.Ads.Dfp.v201408.Content.id, Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.IncreaseOffsetBy(), Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.Limit(), Google.Api.Ads.Dfp.v201408.Content.name, Google.Api.Ads.Dfp.Lib.DfpService.v201408.NetworkService, Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.OrderBy(), Google.Api.Ads.Dfp.v201408.CustomTargetingValuePage.results, Google.Api.Ads.Dfp.v201408.ContentPage.results, Google.Api.Ads.Dfp.v201408.ContentPage.startIndex, Google.Api.Ads.Dfp.v201408.Content.status, Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.SUGGESTED_PAGE_LIMIT, Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.ToStatement(), Google.Api.Ads.Dfp.v201408.ContentPage.totalResultSetSize, and Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.Where().
Property Documentation
override string Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfp/CSharp/v201408/ContentService/GetContentByCategory.cs