Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordBidSimulations Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordBidSimulations Class Reference
This code example gets a bid landscape for an ad group and a keyword. To get ad groups, run GetAdGroups.cs. To get keywords, run GetKeywords.cs.
Public Member Functions
void Run (AdWordsUser user, long adGroupId, long keywordId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example gets a bid landscape for an ad group and a keyword. To get ad groups, run GetAdGroups.cs. To get keywords, run GetKeywords.cs.
Tags: DataService.getCriterionBidLandscape
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordBidSimulations.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordBidSimulations.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordBidSimulations.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordBidSimulations.Run (AdWordsUser user, long adGroupId, long keywordId) inline
Runs the code example.
Parameters
user The AdWords user.
adGroupId Id of the ad group for which keyword bid simulations are retrieved.
keywordId Id of the keyword for which bid simulations are retrieved.
References Google.Api.Ads.AdWords.v201402.BidLandscape.adGroupId, Google.Api.Ads.AdWords.v201402.BidLandscapeLandscapePoint.bid, Google.Api.Ads.AdWords.v201402.BidLandscapeLandscapePoint.clicks, Google.Api.Ads.AdWords.v201402.BidLandscapeLandscapePoint.cost, Google.Api.Ads.AdWords.v201402.CriterionBidLandscape.criterionId, Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.DataService, Google.Api.Ads.AdWords.v201402.BidLandscape.endDate, Google.Api.Ads.AdWords.v201402.CriterionBidLandscapePage.entries, Google.Api.Ads.AdWords.v201402.Predicate.field, Google.Api.Ads.AdWords.v201402.Selector.fields, Google.Api.Ads.AdWords.v201402.DataService.getCriterionBidLandscape(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.BidLandscapeLandscapePoint.impressions, Google.Api.Ads.AdWords.v201402.BidLandscape.landscapePoints, Google.Api.Ads.AdWords.v201402.BidLandscapeLandscapePoint.marginalCpc, Google.Api.Ads.AdWords.v201402.Money.microAmount, Google.Api.Ads.AdWords.v201402.Paging.numberResults, Google.Api.Ads.AdWords.v201402.Selector.paging, Google.Api.Ads.AdWords.v201402.Selector.predicates, Google.Api.Ads.AdWords.v201402.BidLandscape.startDate, Google.Api.Ads.AdWords.v201402.Paging.startIndex, Google.Api.Ads.AdWords.v201402.Page.totalNumEntries, and Google.Api.Ads.AdWords.v201402.Predicate.values.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordBidSimulations.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordBidSimulations.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordBidSimulations.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201402/Optimization/GetKeywordBidSimulations.cs