Ads API .NET library: Google.Api.Ads.Dfp.Examples.CSharp.SampleBase Class Reference
Google.Api.Ads.Dfp.Examples.CSharp.SampleBase Class Reference abstract
This abstract class represents a code example.
Public Member Functions
abstract void Run (DfpUser user)
Run the code example.
Protected Member Functions
string _T (string prompt)
string GetTimeStamp ()
Gets the current time stamp.
Properties
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This abstract class represents a code example.
Member Function Documentation
string Google.Api.Ads.Dfp.Examples.CSharp.SampleBase._T (string prompt) inline protected
string Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.GetTimeStamp () inline protected
Gets the current time stamp.
Returns
The current timestamp as a string.
You can use this method to generate a random string for use with various entities that need a unique name. The method adds a 100ms delay to prevent closely placed calls from generating the same timestamp.
abstract void Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Run (DfpUser user) pure virtual
Run the code example.
Parameters
user DFP user object running the code example.
Implemented in Google.Api.Ads.Dfp.Examples.CSharp.v201311.MakeTestNetwork, Google.Api.Ads.Dfp.Examples.CSharp.v201403.MakeTestNetwork, Google.Api.Ads.Dfp.Examples.CSharp.v201405.MakeTestNetwork, Google.Api.Ads.Dfp.Examples.CSharp.v201408.MakeTestNetwork, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201311.ActivateLineItem, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201403.ActivateLineItem, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201405.ActivateLineItem, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLineItem, Google.Api.Ads.Dfp.Examples.CSharp.v201311.SetLineItemCustomFieldValue, Google.Api.Ads.Dfp.Examples.CSharp.v201403.SetLineItemCustomFieldValue, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileLineItem, Google.Api.Ads.Dfp.Examples.CSharp.v201405.SetLineItemCustomFieldValue, Google.Api.Ads.Dfp.Examples.CSharp.v201408.SetLineItemCustomFieldValue, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCustomTargetingValuesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateMobileLineItem, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetGeoTargets, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetGeoTargets, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetGeoTargets, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreativeFromTemplate, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomTargetingKeysAndValues, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateVideoLineItem, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeFromTemplate, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomTargetingKeysAndValues, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateVideoLineItem, Google.Api.Ads.Dfp.Examples.CSharp.v201403.TargetCustomCriteria, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreativeFromTemplate, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomTargetingKeysAndValues, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateVideoLineItem, Google.Api.Ads.Dfp.Examples.CSharp.v201405.TargetCustomCriteria, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCreativeFromTemplate, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomTargetingKeysAndValues, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateVideoLineItem, Google.Api.Ads.Dfp.Examples.CSharp.v201408.TargetCustomCriteria, Google.Api.Ads.Dfp.Examples.CSharp.v201311.TargetCustomCriteria, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItemsUsingPql, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCustomTargetingValuesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItemsUsingPql, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCustomTargetingValuesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItemsUsingPql, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingValuesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemsUsingPql, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetContentByCategory, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CopyImageCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomFieldOptions, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomTargetingKeys, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomTargetingValues, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLabelsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetOrdersByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunReportWithCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetContentByCategory, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CopyImageCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomFieldOptions, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomTargetingKeys, Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunReportWithCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetContentByCategory, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CopyImageCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomFieldOptions, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomTargetingKeys, Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunReportWithCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CopyImageCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomFieldOptions, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingKeys, Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReportWithCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomCreative, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateAllLineItemCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCustomTargetingKeysAndValues, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCustomTargetingKeysByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateActiveLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201311.DisplayReport, Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunDeliveryReport, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllSuggestedAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetSuggestedAdUnit, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetSuggestedUnitByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetTeamsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateUser, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUserTeamAssociationsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomCreative, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCustomTargetingKeysAndValues, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomTargetingValues, Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateActiveLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201403.DisplayReport, Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunDeliveryReport, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllSuggestedAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetSuggestedUnitByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateUser, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomCreative, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCustomTargetingKeysAndValues, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomTargetingValues, Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateActiveLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201405.DisplayReport, Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunDeliveryReport, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllSuggestedAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetSuggestedUnitByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateUser, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomCreative, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomTargetingKeysAndValues, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingValues, Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201408.DisplayReport, Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunDeliveryReport, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllSuggestedAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetSuggestedUnitByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201311.PopulateFirstPartyAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCompaniesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItemCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateMobileAdUnit, Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeActivateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201311.ActivateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLicasByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItemsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetRecentlyUpdatedLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivatePlacement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.FetchMatchTables, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItemsNamedLike, Google.Api.Ads.Dfp.Examples.CSharp.v201311.DownloadReport, Google.Api.Ads.Dfp.Examples.CSharp.v201311.ApproveSuggestedAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUserTeamAssociation, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201403.PopulateFirstPartyAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItemCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileAdUnit, Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeActivateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLabelsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201403.ActivateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetRecentlyUpdatedLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetOrdersByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivatePlacement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.FetchMatchTables, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLineItemsNamedLike, Google.Api.Ads.Dfp.Examples.CSharp.v201403.DownloadReport, Google.Api.Ads.Dfp.Examples.CSharp.v201403.ApproveSuggestedAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetTeamsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201405.PopulateFirstPartyAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItemCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateMobileAdUnit, Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeActivateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLabelsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201405.ActivateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetRecentlyUpdatedLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetOrdersByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivatePlacement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.FetchMatchTables, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLineItemsNamedLike, Google.Api.Ads.Dfp.Examples.CSharp.v201405.DownloadReport, Google.Api.Ads.Dfp.Examples.CSharp.v201405.ApproveSuggestedAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetTeamsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201408.PopulateFirstPartyAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateMobileAdUnit, Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLabelsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetRecentlyUpdatedLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetOrdersByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.FetchMatchTables, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsNamedLike, Google.Api.Ads.Dfp.Examples.CSharp.v201408.DownloadReport, Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetTeamsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativeTemplate, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnitsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLabel, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLica, Google.Api.Ads.Dfp.Examples.CSharp.v201311.ApproveOrder, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreatePlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdatePlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunInventoryReport, Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunMergedDeliveryReport, Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunReachReport, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetTeam, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUsersByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCustomTargetingKeysByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAdUnitsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetInventoryTree, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201403.ApproveOrder, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreatePlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdatePlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunInventoryReport, Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunMergedDeliveryReport, Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunReachReport, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCustomTargetingKeysByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAdUnitsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetInventoryTree, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201405.ApproveOrder, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreatePlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdatePlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunInventoryReport, Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunMergedDeliveryReport, Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunReachReport, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingKeysByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetInventoryTree, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreatePlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdatePlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunInventoryReport, Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReachReport, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetFirstPartyAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUninvitedContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetForecast, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateVideoAdUnit, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetInventoryTree, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLabels, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllNetworks, Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetPlacementsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunSalesReport, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeleteUserTeamAssociation, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetFirstPartyAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCompaniesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUninvitedContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllContent, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCreativesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetForecast, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateVideoAdUnit, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLicasByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLineItemsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllNetworks, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetPlacementsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunSalesReport, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUsersByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeleteUserTeamAssociation, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUserTeamAssociationsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetFirstPartyAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCompaniesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUninvitedContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllContent, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCreativesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetForecast, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateVideoAdUnit, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLicasByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLineItemsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllNetworks, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetPlacementsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunSalesReport, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUsersByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeleteUserTeamAssociation, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUserTeamAssociationsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetFirstPartyAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCompaniesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUninvitedContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContent, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomFields, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetForecast, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateVideoAdUnit, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLicasByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllNetworks, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetPlacementsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunSalesReport, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUsersByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUserTeamAssociations, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUserTeamAssociationsByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCompany, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllContent, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreative, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreativeTemplates, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativeTemplatesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeActivateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetForecastById, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnit, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLicas, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItems, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItem, Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllPlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetPlacement, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllRoles, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreativeTemplates, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCreativeTemplatesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeActivateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetForecastById, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllPlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllRoles, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreativeTemplates, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCreativeTemplatesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeActivateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetForecastById, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllPlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllRoles, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateActivityGroups, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateActivities, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateAudienceSegments, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContacts, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeTemplates, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativeTemplatesByStatement, Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetForecastById, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllPlacements, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllTeams, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllRoles, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCompanies, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreatives, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnitSizes, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllAdUnits, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCurrentNetwork, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUser, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAdUnitSizes, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCurrentNetwork, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAdUnitSizes, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCurrentNetwork, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitSizes, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCurrentNetwork, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllOrders, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetOrder, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllUsers, Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCurrentUser, Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCurrentUser, Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCurrentUser, and Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCurrentUser.
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCurrentUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCurrentUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCurrentUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCurrentUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCurrentNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCurrentNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCurrentNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCurrentNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAdUnitSizes.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitSizes.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnitSizes.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAdUnitSizes.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCompany.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativeTemplatesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCreativeTemplatesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCreativeTemplatesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativeTemplatesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeActivateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeActivateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeActivateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllRoles.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllContent.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllPlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllPlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllPlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllPlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetPlacement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetForecastById.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetForecastById.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetForecastById.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetForecastById.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreative.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllRoles.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllRoles.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllRoles.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreativeTemplates.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreativeTemplates.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreativeTemplates.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeTemplates.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCompaniesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLicasByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLicasByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLicasByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUsersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLineItemsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUninvitedContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLineItemsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUninvitedContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUninvitedContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUninvitedContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllNetworks.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllNetworks.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllNetworks.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllNetworks.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCreativesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllContent.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContent.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllContent.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetPlacementsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetPlacementsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetPlacementsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetPlacementsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetForecast.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetForecast.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetForecast.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetForecast.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunSalesReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunSalesReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunSalesReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunSalesReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateVideoAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateVideoAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateVideoAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateVideoAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUserTeamAssociationsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCreativesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetInventoryTree.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUsersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUsersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeleteUserTeamAssociation.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeleteUserTeamAssociation.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeleteUserTeamAssociation.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUserTeamAssociationsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCompaniesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUserTeamAssociationsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCompaniesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLabel.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAdUnitsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReachReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunMergedDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunReachReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetInventoryTree.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetInventoryTree.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ApproveOrder.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ApproveOrder.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ApproveOrder.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCustomTargetingKeysByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCustomTargetingKeysByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingKeysByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunInventoryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunInventoryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunInventoryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunInventoryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunMergedDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunMergedDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunReachReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunReachReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetTeam.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnitsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAdUnitsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUsersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetInventoryTree.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativeTemplate.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUserTeamAssociation.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetTeamsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLabelsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLabelsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLabelsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ActivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ActivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCompaniesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLicasByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateMobileAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ApproveSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeActivateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItemsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetRecentlyUpdatedLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetRecentlyUpdatedLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetRecentlyUpdatedLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetRecentlyUpdatedLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItemCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItemCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItemCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.PopulateFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.FetchMatchTables.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.FetchMatchTables.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetOrdersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetOrdersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetOrdersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.PopulateFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivatePlacement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.PopulateFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivatePlacement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.FetchMatchTables.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.FetchMatchTables.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.PopulateFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItemsNamedLike.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLineItemsNamedLike.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLineItemsNamedLike.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsNamedLike.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DownloadReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DownloadReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DownloadReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DownloadReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivatePlacement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ActivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateMobileAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateMobileAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetTeamsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeActivateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetTeamsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeActivateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ApproveSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ApproveSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomCreative.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetSuggestedUnitByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetSuggestedUnitByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateActiveLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DisplayReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUserTeamAssociationsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DisplayReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomTargetingValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateAllLineItemCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetSuggestedAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetTeamsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateActiveLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DisplayReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomCreative.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCustomTargetingKeysByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomTargetingValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomCreative.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DisplayReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetSuggestedUnitByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetSuggestedUnitByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateActiveLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomCreative.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CopyImageCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeleteContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReportWithCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetOrdersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingKeys.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunReportWithCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CopyImageCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunReportWithCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunReportWithCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetContentByCategory.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomFieldOptions.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomTargetingKeys.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeleteContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetContentByCategory.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CopyImageCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetContentByCategory.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomTargetingValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomFieldOptions.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomTargetingKeys.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomFieldOptions.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CopyImageCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomFieldOptions.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLabelsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomTargetingKeys.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItemsUsingPql.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemsUsingPql.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCustomTargetingValuesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingValuesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItemsUsingPql.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.TargetCustomCriteria.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCustomTargetingValuesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItemsUsingPql.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateVideoLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateVideoLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.TargetCustomCriteria.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreativeFromTemplate.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.TargetCustomCriteria.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreativeFromTemplate.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCreativeFromTemplate.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateVideoLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeFromTemplate.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.TargetCustomCriteria.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateVideoLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetGeoTargets.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateMobileLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetGeoTargets.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCustomTargetingValuesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetGeoTargets.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.SetLineItemCustomFieldValue.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.SetLineItemCustomFieldValue.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.SetLineItemCustomFieldValue.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.SetLineItemCustomFieldValue.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ActivateLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ActivateLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ActivateLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.MakeTestNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.MakeTestNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.MakeTestNetwork.Main(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.MakeTestNetwork.Main().
Property Documentation
abstract string Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCurrentUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCurrentUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCurrentUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCurrentUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCurrentNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCurrentNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCurrentNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCurrentNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAdUnitSizes.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitSizes.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnitSizes.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAdUnitSizes.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCompany.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativeTemplatesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCreativeTemplatesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCreativeTemplatesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativeTemplatesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeActivateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeActivateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeActivateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllRoles.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllContent.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllPlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllPlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllPlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllPlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetPlacement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetForecastById.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetForecastById.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetForecastById.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetForecastById.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreative.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllRoles.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllRoles.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllRoles.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreativeTemplates.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreativeTemplates.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreativeTemplates.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeTemplates.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCompaniesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLicasByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLicasByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLicasByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUsersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLineItemsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUninvitedContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLineItemsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUninvitedContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUninvitedContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUninvitedContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllNetworks.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllNetworks.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllNetworks.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllNetworks.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCreativesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllContent.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContent.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllContent.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetPlacementsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetPlacementsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetPlacementsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetPlacementsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetForecast.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetForecast.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetForecast.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetForecast.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunSalesReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunSalesReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunSalesReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunSalesReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateVideoAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateVideoAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateVideoAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateVideoAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUserTeamAssociationsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCreativesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetInventoryTree.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUsersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUsersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeleteUserTeamAssociation.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeleteUserTeamAssociation.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeleteUserTeamAssociation.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUserTeamAssociationsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCompaniesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUserTeamAssociationsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCompaniesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLabel.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAdUnitsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReachReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunMergedDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunReachReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateUsers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetInventoryTree.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetInventoryTree.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ApproveOrder.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ApproveOrder.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ApproveOrder.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCustomTargetingKeysByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCustomTargetingKeysByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingKeysByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunInventoryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunInventoryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunInventoryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunInventoryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunMergedDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunMergedDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunReachReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreatePlacements.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunReachReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateOrders.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetTeam.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnitsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAdUnitsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContacts.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUsersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetInventoryTree.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateActivities.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativeTemplate.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUserTeamAssociation.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetTeamsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLabelsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLabelsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLabelsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCompanies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ActivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ActivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCompaniesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLicasByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateMobileAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ApproveSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeActivateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItemsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetRecentlyUpdatedLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetRecentlyUpdatedLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetRecentlyUpdatedLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetRecentlyUpdatedLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItemCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItemCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItemCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.PopulateFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.FetchMatchTables.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.FetchMatchTables.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetOrdersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetOrdersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetOrdersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.PopulateFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivatePlacement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.PopulateFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivatePlacement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.FetchMatchTables.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.FetchMatchTables.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.PopulateFirstPartyAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItemsNamedLike.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLineItemsNamedLike.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLineItemsNamedLike.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsNamedLike.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DownloadReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DownloadReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DownloadReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DownloadReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivatePlacement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ActivateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateMobileAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateMobileAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetTeamsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeActivateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetTeamsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateActivityGroups.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeActivateAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ApproveSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ApproveSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomCreative.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetSuggestedUnitByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetSuggestedUnitByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateActiveLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DisplayReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUserTeamAssociationsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUserTeamAssociations.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DisplayReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomTargetingValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateAllLineItemCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetSuggestedAdUnit.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetTeamsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateActiveLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DisplayReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomCreative.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCustomTargetingKeysByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomTargetingValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateUser.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreativeWrappers.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunDeliveryReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomCreative.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DisplayReport.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateTeams.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetSuggestedUnitByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetSuggestedUnitByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllSuggestedAdUnits.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateAudienceSegments.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateActiveLabels.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomCreative.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CopyImageCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeleteContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReportWithCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetOrdersByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingKeys.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunReportWithCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CopyImageCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunReportWithCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunReportWithCustomFields.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetContentByCategory.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomFieldOptions.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomTargetingKeys.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeleteContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetContentByCategory.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CopyImageCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetContentByCategory.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomTargetingValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomFieldOptions.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomTargetingKeys.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomFieldOptions.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CopyImageCreatives.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomFieldOptions.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLabelsByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomTargetingKeys.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItemsUsingPql.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemsUsingPql.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCustomTargetingValuesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateContentMetadataKeyHierarchies.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingValuesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItemsUsingPql.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.TargetCustomCriteria.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCustomTargetingValuesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItemsUsingPql.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateVideoLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateVideoLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.TargetCustomCriteria.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreativeFromTemplate.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.TargetCustomCriteria.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreativeFromTemplate.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateCreativeFromTemplate.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateVideoLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeFromTemplate.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.TargetCustomCriteria.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateVideoLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomTargetingKeysAndValues.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetGeoTargets.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateMobileLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetGeoTargets.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLineItems.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCustomTargetingValuesByStatement.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetGeoTargets.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.SetLineItemCustomFieldValue.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.SetLineItemCustomFieldValue.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.SetLineItemCustomFieldValue.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.SetLineItemCustomFieldValue.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ActivateLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ActivateLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLicas.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ActivateLineItem.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.MakeTestNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.MakeTestNetwork.Main(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.MakeTestNetwork.Main(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.MakeTestNetwork.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfp/CSharp/SampleBase.cs