Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetAdParameters Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetAdParameters Class Reference
This code example illustrates how to create a text ad with ad parameters. To add an ad group, run AddAdGroup.cs. To add a keyword, run run AddKeyword.cs.
Public Member Functions
void Run (AdWordsUser user, long adGroupId, long criterionId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example illustrates how to create a text ad with ad parameters. To add an ad group, run AddAdGroup.cs. To add a keyword, run run AddKeyword.cs.
Tags: AdGroupAdService.mutate, AdParamService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetAdParameters.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetAdParameters.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetAdParameters.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetAdParameters.Run (AdWordsUser user, long adGroupId, long criterionId) inline
Runs the code example.
Parameters
user The AdWords user.
adGroupId Id of the ad group that contains the criterion.
criterionId Id of the keyword for which the ad parameters are set.
References Google.Api.Ads.AdWords.v201406.AdGroupAd.ad, Google.Api.Ads.AdWords.Lib.AdWordsService.v201406.AdGroupAdService, Google.Api.Ads.AdWords.v201406.AdGroupAd.adGroupId, Google.Api.Ads.AdWords.v201406.AdParam.adGroupId, Google.Api.Ads.AdWords.Lib.AdWordsService.v201406.AdParamService, Google.Api.Ads.AdWords.v201406.AdParam.criterionId, Google.Api.Ads.AdWords.v201406.TextAd.description1, Google.Api.Ads.AdWords.v201406.TextAd.description2, Google.Api.Ads.AdWords.v201406.Ad.displayUrl, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201406.TextAd.headline, Google.Api.Ads.AdWords.v201406.Ad.id, Google.Api.Ads.AdWords.v201406.AdParam.insertionText, Google.Api.Ads.AdWords.v201406.AdGroupAdService.mutate(), Google.Api.Ads.AdWords.v201406.AdParamService.mutate(), Google.Api.Ads.AdWords.v201406.AdGroupAdOperation.operand, Google.Api.Ads.AdWords.v201406.AdParamOperation.operand, Google.Api.Ads.AdWords.v201406.AdParam.paramIndex, Google.Api.Ads.AdWords.v201406.AdGroupAd.status, Google.Api.Ads.AdWords.v201406.Ad.url, and Google.Api.Ads.AdWords.v201406.AdGroupAdReturnValue.value.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetAdParameters.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetAdParameters.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetAdParameters.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201406/CampaignManagement/SetAdParameters.cs