Ads API .NET library: Google.Api.Ads.Common.Lib.AdsUser Class Reference
Google.Api.Ads.Common.Lib.AdsUser Class Reference abstract
Represents an Ads API user.
Public Member Functions
abstract Type[] GetServiceTypes ()
Gets all the service types to be registered against this user.
abstract SoapListener[] GetDefaultListeners ()
Gets the default listeners.
void RegisterService (string serviceId, ServiceFactory serviceFactory)
Register a service with AdsUser.
ServiceFactory GetServiceFactory (string serviceId)
Gets the service factory for a service.
AdsClient GetService (ServiceSignature serviceSignature)
Creates an object of the requested type of service.
AdsClient GetService (ServiceSignature serviceSignature, string serverUrl)
Creates an object of the requested type of service.
AdsClient GetService (ServiceSignature serviceSignature, Uri serverUrl)
Creates an object of the requested type of service.
Protected Member Functions
AdsUser (AppConfigBase config)
Protected constructor. Use this version from a derived class if you want the library to use all settings from App.config.
AdsUser (AppConfigBase config, Dictionary< string, string > headers)
Protected constructor. Use this version from a derived class if you want the library to use all settings from App.config.
void RegisterServices (Type[] servicesFamilies)
Registers a family of services against this user.
void SetHeadersFromConfig ()
Set the user headers from App.config.
Properties
AdsOAuthProvider OAuthProvider [get, set]
Gets or sets the OAuth provider.
AppConfig Config [get]
Gets or sets the application configuration for this user.
List< SoapListener > Listeners [get]
Gets the listeners.
Properties inherited from Google.Api.Ads.Common.Lib.Configurable
AppConfig Config [get]
Gets the application configuration class for this object.
Detailed Description
Represents an Ads API user.
Constructor & Destructor Documentation
Google.Api.Ads.Common.Lib.AdsUser.AdsUser (AppConfigBase config) inline protected
Protected constructor. Use this version from a derived class if you want the library to use all settings from App.config.
Google.Api.Ads.Common.Lib.AdsUser.AdsUser (AppConfigBase config, Dictionary< string, string > headers) inline protected
Protected constructor. Use this version from a derived class if you want the library to use all settings from App.config.
This constructor exists for backward compatibility purposes.
Member Function Documentation
abstract SoapListener [] Google.Api.Ads.Common.Lib.AdsUser.GetDefaultListeners () pure virtual
Gets the default listeners.
Returns
A list of default listeners
Implemented in Google.Api.Ads.AdWords.Lib.AdWordsUser, Google.Api.Ads.Dfa.Lib.DfaUser, and Google.Api.Ads.Dfp.Lib.DfpUser.
AdsClient Google.Api.Ads.Common.Lib.AdsUser.GetService (ServiceSignature serviceSignature) inline
Creates an object of the requested type of service.
Parameters
serviceSignature Signature of the service being requested.
Returns
An object of the requested type of service. The caller should cast this object to the desired type.
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetCurrentUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetCurrentUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetCurrentUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetCurrentUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetCurrentUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCurrentUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCurrentUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCurrentUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAdUnitSizes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAdUnitSizes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAdUnitSizes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAdUnitSizes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAdUnitSizes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnitSizes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAdUnitSizes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAdUnitSizes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetCurrentNetwork.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetCurrentNetwork.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetCurrentNetwork.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetCurrentNetwork.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetCurrentNetwork.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCurrentNetwork.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCurrentNetwork.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCurrentNetwork.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllRoles.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllRoles.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllRoles.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllRoles.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllRoles.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetForecastById.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllRoles.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllRoles.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllRoles.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetForecastById.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetForecastById.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetForecastById.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetForecastById.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetForecastById.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetForecastById.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetForecastById.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetCompany.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetCompany.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetCompany.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetCompany.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetCompany.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCompany.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllPlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllPlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllPlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllPlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllPlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllPlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllPlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllPlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetPlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetPlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetPlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetPlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetPlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetPlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.RunSalesReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.RunSalesReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.RunSalesReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.RunSalesReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.RunSalesReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunSalesReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunSalesReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunSalesReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateThirdPartySlots.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateThirdPartySlots.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateThirdPartySlots.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetForecast.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetForecast.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetForecast.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetForecast.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetForecast.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetForecast.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetForecast.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateVideoAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateVideoAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateVideoAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateVideoAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateVideoAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateVideoAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateVideoAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetForecast.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllNetworks.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllNetworks.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllNetworks.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllNetworks.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllNetworks.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllNetworks.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllNetworks.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllNetworks.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateVideoAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.RunInventoryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.RunInventoryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.RunInventoryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.RunInventoryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.RunInventoryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.RunMergedDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.RunMergedDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.RunMergedDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.RunMergedDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.RunMergedDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunMergedDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunMergedDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunMergedDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetActiveActivities.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreatePlacementStrategy.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunReachReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetTeam.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetTeam.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetTeam.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetTeam.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetTeam.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetTeam.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateThirdPartySlot.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllThirdPartySlots.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllThirdPartySlots.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllThirdPartySlots.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateThirdPartySlot.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateThirdPartySlot.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunReachReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateUserTeamAssociations.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetActivityTypes.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetActivityTypes.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreatePlacementStrategy.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllActivityGroups.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetPlacementTypes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.RunReachReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.RunReachReport.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetPricingTypes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunReachReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetPricingTypes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllActivityGroups.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetPlacementTypes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.RunReachReport.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetChangeLogObjectTypes.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetSize.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetSize.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetTagMethodTypes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateLabels.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetUserFilterTypes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLabels.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetUserFilterTypes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetLabel.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetLabel.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetLabel.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetLabel.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetLabel.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLabel.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetTagMethodTypes.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetChangeLogObjectTypes.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateAdvertiserGroup.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateAdvertiserGroup.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetLica.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetLica.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetLica.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetLica.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetLica.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLica.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunInventoryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdatePlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetCreativeTemplate.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetCreativeTemplate.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetCreativeTemplate.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetCreativeTemplate.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetCreativeTemplate.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativeTemplate.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunInventoryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunInventoryReport.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateContentCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DownloadReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.ArchiveThirdPartySlot.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.ArchiveThirdPartySlot.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.DeactivatePlacement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateContentCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateMobileAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.FetchMatchTables.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.ArchiveThirdPartySlot.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateMobileAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateMobileAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateMobileAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateMobileAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateMobileAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.PopulateFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.FetchMatchTables.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.FetchMatchTables.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.PopulateFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.PopulateFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.PopulateFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateMobileAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.DownloadReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DownloadReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DownloadReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.DownloadReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.DownloadReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.DownloadReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.DownloadReport.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetCampaigns.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateCreativeWrappers.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetDFASite.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateCampaign.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllSuggestedAdUnits.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetCampaigns.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.DeactivateAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.DeactivateAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.DeactivateAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetSuggestedAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetSuggestedAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.DeactivateAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetSuggestedAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.DeactivateAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllCustomFields.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateAdvertiser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateCampaign.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateAdvertiser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateCreativeField.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateCreativeFieldValue.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateCreativeFieldValue.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetTeamsByStatement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateHTMLAsset.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateTeams.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateTeams.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateHTMLAsset.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetThirdPartySlotsByStatement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateImageAsset.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetCreativeFieldValues.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateImageAsset.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetThirdPartySlotsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetThirdPartySlotsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetAdTypes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateCreativeWrappers.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetAdTypes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeWrappers.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetCountries.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetTeamsByStatement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetContentCategories.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllCustomFields.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetCountries.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCustomFields.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateCreativeField.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.DisplayReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.DisplayReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateCustomCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DisplayReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DisplayReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetPlacementStrategies.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetContentCategories.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DisplayReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.DisplayReport.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetPlacementStrategies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetSuggestedAdUnit.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetSuggestedAdUnit.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetSubnetworks.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetSuggestedAdUnit.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetSubnetworks.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetCreativeTypes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetDFASite.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetPlacements.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetCreativeFieldValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetCreativeTypes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetActivityGroups.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetPlacements.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateCustomCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateCustomCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateCustomCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateCustomCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.RunDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.RunDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.RunDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.RunDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.RunDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateCustomFieldOptions.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateCustomFieldOptions.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateCustomFieldOptions.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateCustomFieldOptions.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomFieldOptions.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomFieldOptions.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomFieldOptions.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddAudience.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.EstimateKeywordTraffic.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetAdvertisers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.RunReportWithCustomFields.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateCustomFieldOptions.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetAdvertiserGroups.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetAdvertisers.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.EstimateKeywordTraffic.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.EstimateKeywordTraffic.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetLabelsByStatement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetAdvertiserGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetLabelsByStatement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddAudience.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetLabelsByStatement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddAudience.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddConversionTracker.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddConversionTracker.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.DownloadTags.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.UpdateCustomTargetingValues.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.LookupLocation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.DownloadTags.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.LookupLocation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetAllCities.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.LookupLocation.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UploadImage.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateCreativeGroup.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateCreativeGroup.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetCreatives.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetBudgetSuggestion.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateMobileAsset.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetCreativeField.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateMobileAsset.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetAllLineItemsUsingPql.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateSpotlightActivityGroup.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateSubnetwork.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateSpotlightActivityGroup.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetReport.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetKeywordIdeas.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.UploadImage.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UploadImage.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetAllLineItemsUsingPql.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.AssignCreativesToPlacements.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddVideoCampaign.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetCampaigns.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetUserRoles.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetUserRoles.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetCampaigns.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordIdeas.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetCreativeField.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetCampaigns.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetKeywordIdeas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.TargetCustomCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.TargetCustomCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.TargetCustomCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.TargetCustomCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.TargetCustomCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.TargetCustomCriteria.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.AssignCreativesToPlacements.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateSubnetwork.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetAllCities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddVideoCampaign.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItemsUsingPql.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetAllCities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetAllLineItemsUsingPql.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetAllCities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateCustomTargetingKeysAndValues.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetPlacements.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetPlacements.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.CreateAccount.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateCustomTargetingKeysAndValues.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywords.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateCustomTargetingKeysAndValues.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAccountChanges.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateCustomTargetingKeysAndValues.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExpressBusinesses.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetCreativeGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateCustomTargetingKeysAndValues.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetKeywords.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetPlacementIdeas.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateUserRole.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetPlacementIdeas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateCreativeFromTemplate.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateCreativeFromTemplate.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCreativeFromTemplate.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateCreativeFromTemplate.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.CreateAccount.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateCreativeFromTemplate.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetPlacementIdeas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateVideoLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateVideoLineItem.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.CreateAccount.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.TargetCustomCriteria.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.AssignAdvertisersToAdvertiserGroup.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.TargetCustomCriteria.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.AssignAdvertisersToAdvertiserGroup.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetKeywords.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateVideoLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateVideoLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateVideoLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeFromTemplate.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateVideoLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateVideoLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateCreativeFromTemplate.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAccountChanges.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateCreativeFromTemplate.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddExpressBusinesses.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateCustomTargetingKeysAndValues.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetAccountChanges.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetCreativeGroups.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddExpressBusinesses.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetPlacements.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateUserRole.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateVideoLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateMobileLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateMobileLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateMobileLineItem.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignStats.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateSpotlightActivity.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateLineItems.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetVideoCampaignStats.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateSpotlightActivity.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAllDisapprovedAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.UseSharedBiddingStrategy.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetReportFields.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetReportFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetAllDisapprovedAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetExpressBusinesses.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetExpressBusinesses.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAllDisapprovedAds.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.GetGeoTargets.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.SetProductSalesChannel.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdateCampaign.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateMobileLineItem.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.UpdateCampaign.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetVideoCampaignStats.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UseSharedBiddingStrategy.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetReportFields.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetExpressBusinesses.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateLineItems.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetTargetableLanguagesAndCarriers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateMobileLineItem.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetProductSalesChannel.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetTargetableLanguagesAndCarriers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetGeoTargets.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateMobileLineItem.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdateCampaign.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.GetGeoTargets.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetTargetableLanguagesAndCarriers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetGeoTargets.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UseSharedBiddingStrategy.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateRotationGroup.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateMobileLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.SetLineItemCustomFieldValue.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetCampaignsWithAwql.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.SetLineItemCustomFieldValue.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.SetLineItemCustomFieldValue.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.SetLineItemCustomFieldValue.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.SetLineItemCustomFieldValue.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddVideoCallToAction.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.UpdateExpressBusiness.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAllVideosAndImages.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddPromotion.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCallToAction.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateInStreamVideoCreative.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdateExpressBusiness.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeleteAdGroup.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.SetLineItemCustomFieldValue.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetAllVideosAndImages.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.SetLineItemCustomFieldValue.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdateExpressBusiness.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetCampaignsByLabel.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.DeleteAdGroup.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.RemoveAdGroup.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.SetLineItemCustomFieldValue.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeleteCampaign.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetCampaignsWithAwql.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.HandlePartialFailures.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaignCriteria.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateInStreamVideoCreative.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddVideoCampaignCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAllVideosAndImages.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.HandlePartialFailures.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPromotion.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetCampaignsWithAwql.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdateAdGroup.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.DeleteCampaign.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePartialFailures.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.RemoveCampaign.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddVideoCampaignCriteria.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateRotationGroup.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdateAdGroup.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddVideoCallToAction.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddPromotion.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.UpdateAdGroup.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroupCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddTargetingGroupCriteria.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateMobileCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.ActivateLineItem.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.HandlePolicyViolationError.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddLocationExtension.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAccountHierarchy.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddPlacements.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetPromotions.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaigns.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLicas.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddLocationExtension.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateFlashInpageCreative.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetTextAds.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.CreateLicas.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddVideoAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetTextAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacements.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreatePlacement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroups.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.RunDeferredReport.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddCampaigns.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetPromotions.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddAdGroupDemographicCriteria.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateMobileCreative.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetReports.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetReports.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreatePlacement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddTargetingGroup.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddAdGroupDemographicCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddProductScope.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetPromotions.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetAdGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.ActivateLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.ActivateLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.ActivateLineItem.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetChangeLogForAdvertiser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.ActivateLineItem.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddCampaignTargetingCriteria.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateFlashInpageCreative.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.ActivateLineItem.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.CreateLicas.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddVideoAd.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetChangeLogForAdvertiser.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAccountHierarchy.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidSimulations.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetTextAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddPlacements.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetAccountHierarchy.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.ActivateLineItem.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.RunDeferredReport.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTargetingGroup.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.PauseAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddAdGroupDemographicCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.HandlePolicyViolationError.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroup.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAdGroups.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTargetingGroupCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.PauseAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetAdGroupBidSimulations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.CreateLicas.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.PauseAd.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.CreateLicas.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddLocationExtension.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.CreateLicas.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductScope.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddCampaigns.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.ActivateLineItem.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddCampaignTargetingCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.CreateLicas.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAdGroupBidSimulations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateLicas.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.ValidateTextAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetAdGroupBidModifiers.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.ValidateTextAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetAccountAlerts.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdatePromotion.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.PromoteExperiment.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.PromoteExperiment.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAccountAlerts.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddShoppingCampaign.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.PromoteExperiment.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.UpdatePromotion.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdatePromotion.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeleteAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAccountAlerts.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidModifiers.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.ValidateTextAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.RemoveAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAdGroupBidModifiers.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.DeleteAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddShoppingCampaign.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetProductServices.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddKeywordsInBulk.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetThirdPartyRedirectAds.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201208.MakeTestNetwork.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeletePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201306.MakeTestNetwork.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAllDisapprovedAdsWithAwql.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetCampaignTargetingCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.RemoveKeyword.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdatePlacement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetThirdPartyRedirectAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacementsInBulk.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.AddAdvertiserUserFilter.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.AddAdvertiserUserFilter.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201211.MakeTestNetwork.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.RemovePlacement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.DeleteKeyword.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetCampaignTargetingCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetProductServices.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetThirdPartyRedirectAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywordsInBulk.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201302.MakeTestNetwork.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddPlacementsInBulk.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201308.MakeTestNetwork.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetCampaignTargetingCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddPlacementsInBulk.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddClickToDownloadAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddClickToDownloadAd.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdateKeyword.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddClickToDownloadAd.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201311.MakeTestNetwork.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddKeywordsInBulk.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeleteKeyword.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdateKeyword.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.MakeTestNetwork.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetAllDisapprovedAdsWithAwql.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.UpdatePlacement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdatePlacement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetProductServices.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201403.MakeTestNetwork.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.DeletePlacement.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAllDisapprovedAdsWithAwql.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.UpdateKeyword.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddCampaignLabels.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddAdGroupBidModifier.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.GetAvailablePermissions.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaigns.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetVideoCampaigns.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.GetAvailablePermissions.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetVideoCampaigns.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddAdGroupBidModifier.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAdWithUpgradedUrls.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddAdGroupBidModifier.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordBidSimulations.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.SetAdParameters.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.SetAdParameters.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetAdParameters.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetKeywordBidSimulations.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetKeywordBidSimulations.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddKeywords.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetKeywordCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddThirdPartyRedirectAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywords.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddAdGroups.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetTargetingGroups.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.FindVideos.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetBidModifier.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddAdGroups.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddThirdPartyRedirectAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddAdGroups.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetVideoCampaignCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.SetBidModifier.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.GetVideoCampaignCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetTargetingGroups.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddKeywords.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.FindVideos.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetTargetingGroups.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.FindVideos.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetKeywordCriteria.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.SetBidModifier.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.ModifyInStreamMediaFilesAndAds.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.ModifyInStreamMediaFilesAndAds.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.UploadInStreamAsset.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.UploadInStreamAsset.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.Authenticate.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.Authenticate.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddTextAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTextAds.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.ReplaceInStreamAsset.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.ReplaceInStreamAsset.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.UploadOfflineConversions.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UploadOfflineConversions.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201309.AddExperiment.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddExperiment.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UploadOfflineConversions.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddPlacesLocationExtension.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_20.RCReport.Run(), Google.Api.Ads.Dfa.Examples.CSharp.v1_19.RCReport.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetProductCategoryTaxonomy.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetProductCategoryTaxonomy.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductPartitionTree.Run(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddProductPartitionTree.Run().
AdsClient Google.Api.Ads.Common.Lib.AdsUser.GetService (ServiceSignature serviceSignature, string serverUrl) inline
Creates an object of the requested type of service.
Parameters
serviceSignature Signature of the service being requested.
serverUrl The server url for Ads service.
Returns
An object of the requested type of service. The caller should cast this object to the desired type.
AdsClient Google.Api.Ads.Common.Lib.AdsUser.GetService (ServiceSignature serviceSignature, Uri serverUrl) inline
Creates an object of the requested type of service.
Parameters
serviceSignature Signature of the service being requested.
serverUrl The server url for Ads service.
Returns
An object of the requested type of service. The caller should cast this object to the desired type.
References Google.Api.Ads.Common.Lib.ServiceSignature.Id, and Google.Api.Ads.Common.Lib.ServiceSignature.ServiceName.
ServiceFactory Google.Api.Ads.Common.Lib.AdsUser.GetServiceFactory (string serviceId) inline
Gets the service factory for a service.
Parameters
serviceId The service id.
Returns
The service factory instance, or null if the service is not yet registered.
abstract Type [] Google.Api.Ads.Common.Lib.AdsUser.GetServiceTypes () pure virtual
Gets all the service types to be registered against this user.
Returns
The type of all service classes to be registered.
Implemented in Google.Api.Ads.AdWords.Lib.AdWordsUser, Google.Api.Ads.Dfa.Lib.DfaUser, and Google.Api.Ads.Dfp.Lib.DfpUser.
void Google.Api.Ads.Common.Lib.AdsUser.RegisterService (string serviceId, ServiceFactory serviceFactory) inline
Register a service with AdsUser.
Parameters
serviceId A unique id for the service being registered.
serviceFactory The factory that will create this service.
void Google.Api.Ads.Common.Lib.AdsUser.RegisterServices (Type[] servicesFamilies) inline protected
Registers a family of services against this user.
Parameters
servicesFamilies The family of services that should be registered against this user.
Every family of services that should be registered with an AdsUser should be like follows:
public class vX {
  public Type factoryType = typeof(SomeServiceVxFactory);
  public readonly ServiceSignature Service1;
  public readonly ServiceSignature Service2;
}
The method uses reflection to
Find all the fields of type ServiceSignature.
Extract the factory type from factoryType field.
Register each found service type with the user.
References Google.Api.Ads.Common.Lib.ServiceSignature.Id.
void Google.Api.Ads.Common.Lib.AdsUser.SetHeadersFromConfig () inline protected
Set the user headers from App.config.
Property Documentation
AppConfig Google.Api.Ads.Common.Lib.AdsUser.Config get
Gets or sets the application configuration for this user.
Referenced by Google.Api.Ads.Dfa.Util.LoginUtil.GetAuthenticationToken().
List<SoapListener> Google.Api.Ads.Common.Lib.AdsUser.Listeners get
Gets the listeners.
AdsOAuthProvider Google.Api.Ads.Common.Lib.AdsUser.OAuthProvider get set
Gets or sets the OAuth provider.
The documentation for this class was generated from the following file:
c:/src/MyProjects/now/Common library base/experimental/combine-all/dist/github/src/Common/Lib/AdsUser.cs