Ads API .NET library: Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeFromTemplate Class Reference
Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeFromTemplate Class Reference
This code example creates a new template creative for a given advertiser. To determine which companies are advertisers, run GetCompaniesByStatement.cs. To determine which creatives already exist, run GetAllCreatives.cs. To determine which creative templates exist, run GetAllCreativeTemplates.cs.
Public Member Functions
override void Run (DfpUser user)
Run the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current time stamp.
Detailed Description
This code example creates a new template creative for a given advertiser. To determine which companies are advertisers, run GetCompaniesByStatement.cs. To determine which creatives already exist, run GetAllCreatives.cs. To determine which creative templates exist, run GetAllCreativeTemplates.cs.
Tags: CreativeService.createCreatives
Member Function Documentation
static void Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeFromTemplate.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeFromTemplate.Run (DfpUser user) inline virtual
Run the code example.
Parameters
user The DFP user object running the code example.
Implements Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfp.v201403.Creative.advertiserId, Google.Api.Ads.Dfp.v201403.AssetCreativeTemplateVariableValue.assetByteArray, Google.Api.Ads.Dfp.v201403.CreativeService.createCreatives(), Google.Api.Ads.Dfp.Lib.DfpService.v201403.CreativeService, Google.Api.Ads.Dfp.v201403.TemplateCreative.creativeTemplateId, Google.Api.Ads.Dfp.v201403.TemplateCreative.creativeTemplateVariableValues, Google.Api.Ads.Dfp.v201403.Creative.CreativeType, Google.Api.Ads.Dfp.v201403.AssetCreativeTemplateVariableValue.fileName, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfp.v201403.Size.height, Google.Api.Ads.Dfp.v201403.Creative.id, Google.Api.Ads.Dfp.v201403.Size.isAspectRatio, Google.Api.Ads.Dfp.v201403.Creative.name, Google.Api.Ads.Dfp.v201403.Creative.previewUrl, Google.Api.Ads.Dfp.v201403.Creative.size, Google.Api.Ads.Dfp.v201403.BaseCreativeTemplateVariableValue.uniqueName, Google.Api.Ads.Dfp.v201403.UrlCreativeTemplateVariableValue.value, Google.Api.Ads.Dfp.v201403.StringCreativeTemplateVariableValue.value, Google.Api.Ads.Dfp.v201403.LongCreativeTemplateVariableValue.value, and Google.Api.Ads.Dfp.v201403.Size.width.
Property Documentation
override string Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateCreativeFromTemplate.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfp/CSharp/v201403/CreativeService/CreateCreativeFromTemplate.cs