Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductScope Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductScope Class Reference
This code example restricts the products that will be included in the campaign by setting a ProductScope.
Public Member Functions
void Run (AdWordsUser user, long campaignId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example restricts the products that will be included in the campaign by setting a ProductScope.
Tags: CampaignCriterionService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductScope.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductScope.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductScope.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductScope.Run (AdWordsUser user, long campaignId) inline
Runs the code example.
Parameters
user The AdWords user.
campaignId The campaign id to add product scope.
References Google.Api.Ads.AdWords.Lib.AdWordsService.v201406.CampaignCriterionService, Google.Api.Ads.AdWords.v201406.CampaignCriterion.campaignId, Google.Api.Ads.AdWords.v201406.ProductCanonicalCondition.condition, Google.Api.Ads.AdWords.v201406.CampaignCriterion.criterion, Google.Api.Ads.AdWords.v201406.ProductScope.dimensions, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201406.Criterion.id, Google.Api.Ads.AdWords.v201406.CampaignCriterionService.mutate(), Google.Api.Ads.AdWords.v201406.CampaignCriterionOperation.operand, Google.Api.Ads.AdWords.v201406.ProductType.type, Google.Api.Ads.AdWords.v201406.ProductCustomAttribute.type, Google.Api.Ads.AdWords.v201406.ProductBiddingCategory.type, Google.Api.Ads.AdWords.v201406.CampaignCriterionReturnValue.value, Google.Api.Ads.AdWords.v201406.ProductType.value, Google.Api.Ads.AdWords.v201406.ProductOfferId.value, Google.Api.Ads.AdWords.v201406.ProductCustomAttribute.value, Google.Api.Ads.AdWords.v201406.ProductBrand.value, and Google.Api.Ads.AdWords.v201406.ProductBiddingCategory.value.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductScope.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductScope.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductScope.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201406/ShoppingCampaigns/AddProductScope.cs