Ads API .NET library: Google.Api.Ads.AdWords.Util.Reports.v201806.ReportQuery Class Reference
Google.Api.Ads.AdWords.Util.Reports.v201806.ReportQuery Class Reference
A reporting query, returned by ReportQueryBuilder
Inherits Google.Api.Ads.AdWords.Util.Reports.IReportQuery< TParent, TBuilder >.
Public Member Functions
ReportQuery (ReportQueryBuilder builder)
Initializes a new instance of the SelectQuery class.
override string ToString ()
Returns a string that represents this instance.
Static Public Member Functions
static implicit operator string (ReportQuery x)
Performs an implicit conversion from ReportQuery to string.
Properties
ReportQueryBuilder Builder [get]
Gets the builder.
Properties inherited from Google.Api.Ads.AdWords.Util.Reports.IReportQuery< TParent, TBuilder >
TBuilder Builder [get]
Gets the builder.
Detailed Description
A reporting query, returned by ReportQueryBuilder
Constructor & Destructor Documentation
Google.Api.Ads.AdWords.Util.Reports.v201806.ReportQuery.ReportQuery (ReportQueryBuilder builder) inline
Initializes a new instance of the SelectQuery class.
Parameters
builder The builder.
Member Function Documentation
static implicit Google.Api.Ads.AdWords.Util.Reports.v201806.ReportQuery.operator string (ReportQuery x) inline static
Performs an implicit conversion from ReportQuery to string.
Parameters
x The ReportQuery to convert.
Returns
The result of the conversion.
override string Google.Api.Ads.AdWords.Util.Reports.v201806.ReportQuery.ToString () inline
Returns a string that represents this instance.
Returns
A string that represents this instance.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201806.DownloadCriteriaReportWithAwql.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201806.StreamCriteriaReportResults.Run(), and Google.Api.Ads.AdWords.Examples.CSharp.v201806.StreamCriteriaReportToPoco.Run().
Property Documentation
ReportQueryBuilder Google.Api.Ads.AdWords.Util.Reports.v201806.ReportQuery.Builder get
Gets the builder.
The documentation for this class was generated from the following file:
dist/github/src/AdWords/Util/Reports/QueryBuilder/v201806/ReportQuery.cs