Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroupCriteria Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroupCriteria Class Reference
This code example illustrates how to create targeting group criteria.
Public Member Functions
void Run (AdWordsUser user, long campaignId, long targetingGroupId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example illustrates how to create targeting group criteria.
Tags: VideoTargetingGroupCriterionService.mutate
AdWords for Video API is a Beta feature.
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroupCriteria.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroupCriteria.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroupCriteria.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroupCriteria.Run (AdWordsUser user, long campaignId, long targetingGroupId) inline
Runs the code example.
Parameters
user The AdWords user.
campaignId The campaign ID.
targetingGroupId The targeting group ID.
References Google.Api.Ads.AdWords.v201402.AudienceAge.ageRange, Google.Api.Ads.AdWords.v201402.BaseCriterion.BaseCriterionType, Google.Api.Ads.AdWords.v201402.TargetingGroupCriterion.campaignId, Google.Api.Ads.AdWords.v201402.TargetingGroupCriterion.criterion, Google.Api.Ads.AdWords.v201402.AudienceGender.genderType, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.BaseCriterion.id, Google.Api.Ads.AdWords.v201402.AudienceInterest.interestId, Google.Api.Ads.AdWords.v201402.VideoTargetingGroupCriterionService.mutate(), Google.Api.Ads.AdWords.v201402.TargetingGroupCriterionOperation.operand, Google.Api.Ads.AdWords.v201402.TargetingGroupCriterion.targetingGroupId, Google.Api.Ads.AdWords.v201402.TargetingGroupCriterionReturnValue.value, Google.Api.Ads.AdWords.v201402.Topic.verticalId, and Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.VideoTargetingGroupCriterionService.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroupCriteria.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroupCriteria.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroupCriteria.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201402/AdWordsForVideo/AddTargetingGroupCriteria.cs