Ads API .NET library: Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreatePlacement Class Reference
Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreatePlacement Class Reference
This code example creates a placement in a given campaign. This code example requires the DFA site id and campaign id in which the placement will be created into. To create a campaign, run CreateCampaign.cs. To get DFA site id, run GetDfaSite.cs. To get a size id, run GetSize.cs. To get placement types, run GetPlacementTypes.cs. To get pricing types, run GetPricingTypes.cs.
Public Member Functions
override void Run (DfaUser user)
Run the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfa.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfa.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current timestamp as a string.
String GetHomeDir ()
Gets the current user's home directory.
Detailed Description
This code example creates a placement in a given campaign. This code example requires the DFA site id and campaign id in which the placement will be created into. To create a campaign, run CreateCampaign.cs. To get DFA site id, run GetDfaSite.cs. To get a size id, run GetSize.cs. To get placement types, run GetPlacementTypes.cs. To get pricing types, run GetPricingTypes.cs.
Tags: placement.savePlacement
Member Function Documentation
static void Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreatePlacement.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfa.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfa.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreatePlacement.Run (DfaUser user) inline virtual
Run the code example.
Parameters
user The Dfa user object running the code example.
Implements Google.Api.Ads.Dfa.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfa.v1_19.Placement.campaignId, Google.Api.Ads.Dfa.v1_19.Placement.dfaSiteId, Google.Api.Ads.Dfa.v1_19.PricingSchedule.endDate, Google.Api.Ads.Dfa.v1_19.PlacementRemoteService.getRegularPlacementTagOptions(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfa.v1_19.Base.id, Google.Api.Ads.Dfa.v1_19.SaveResult.id, Google.Api.Ads.Dfa.v1_19.Base.name, Google.Api.Ads.Dfa.Lib.DfaService.v1_19.PlacementRemoteService, Google.Api.Ads.Dfa.v1_19.Placement.placementType, Google.Api.Ads.Dfa.v1_19.Placement.pricingSchedule, Google.Api.Ads.Dfa.v1_19.PricingSchedule.pricingType, Google.Api.Ads.Dfa.v1_19.PlacementRemoteService.savePlacement(), Google.Api.Ads.Dfa.v1_19.Placement.sizeId, Google.Api.Ads.Dfa.v1_19.PricingSchedule.startDate, Google.Api.Ads.Dfa.v1_19.Placement.tagSettings, and Google.Api.Ads.Dfa.v1_19.TagSettings.tagTypes.
Property Documentation
override string Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreatePlacement.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfa/CSharp/v1_19/CreatePlacement.cs