Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidSimulations Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidSimulations Class Reference
This code example gets bid landscapes for an ad group. To get ad groups, run GetAdGroups.cs.
Public Member Functions
void Run (AdWordsUser user, long adGroupId)
Runs the specified user.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example gets bid landscapes for an ad group. To get ad groups, run GetAdGroups.cs.
Tags: DataService.getAdGroupBidLandscape
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidSimulations.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidSimulations.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidSimulations.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidSimulations.Run (AdWordsUser user, long adGroupId) inline
Runs the specified user.
Parameters
user The user.
adGroupId Id of the ad group for which bid simulations are retrieved.
References Google.Api.Ads.AdWords.v201406.BidLandscape.adGroupId, Google.Api.Ads.AdWords.v201406.BidLandscapeLandscapePoint.bid, Google.Api.Ads.AdWords.v201406.BidLandscapeLandscapePoint.clicks, Google.Api.Ads.AdWords.v201406.BidLandscapeLandscapePoint.cost, Google.Api.Ads.AdWords.Lib.AdWordsService.v201406.DataService, Google.Api.Ads.AdWords.v201406.BidLandscape.endDate, Google.Api.Ads.AdWords.v201406.AdGroupBidLandscapePage.entries, Google.Api.Ads.AdWords.v201406.Predicate.field, Google.Api.Ads.AdWords.v201406.Selector.fields, Google.Api.Ads.AdWords.v201406.DataService.getAdGroupBidLandscape(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201406.BidLandscapeLandscapePoint.impressions, Google.Api.Ads.AdWords.v201406.AdGroupBidLandscape.landscapeCurrent, Google.Api.Ads.AdWords.v201406.BidLandscape.landscapePoints, Google.Api.Ads.AdWords.v201406.BidLandscapeLandscapePoint.marginalCpc, Google.Api.Ads.AdWords.v201406.Money.microAmount, Google.Api.Ads.AdWords.v201406.Selector.predicates, Google.Api.Ads.AdWords.v201406.BidLandscape.startDate, Google.Api.Ads.AdWords.v201406.AdGroupBidLandscape.type, and Google.Api.Ads.AdWords.v201406.Predicate.values.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidSimulations.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidSimulations.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidSimulations.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201406/Optimization/GetAdGroupBidSimulations.cs