Ads API .NET library: Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities Class Reference
Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities Class Reference
Defines report utility functions for the client library.
Public Member Functions
ReportUtilities (AdWordsUser user)
Initializes a new instance of the ReportUtilities class.
ClientReport GetClientReport (string query, string format)
Downloads a report into memory.
ClientReport GetClientReport (string query, string format, bool?returnMoneyInMicros)
Downloads a report into memory.
ClientReport GetClientReport< T > (T reportDefinition)
Downloads a report into memory.
ClientReport GetClientReport< T > (T reportDefinition, bool?returnMoneyInMicros)
Downloads a report into memory.
ClientReport DownloadClientReport (string query, string format, string path)
Downloads a report to disk.
ClientReport DownloadClientReport (string query, string format, bool?returnMoneyInMicros, string path)
Downloads a report to disk.
ClientReport DownloadClientReport< T > (T reportDefinition, string path)
Downloads a report to disk.
ClientReport DownloadClientReport< T > (T reportDefinition, bool?returnMoneyInMicros, string path)
Downloads a report to disk.
Properties
string ReportVersion [get, set]
Gets or sets the reporting API version to use.
AdWordsUser User [get]
Returns the user associated with this object.
Detailed Description
Defines report utility functions for the client library.
Constructor & Destructor Documentation
Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities.ReportUtilities (AdWordsUser user) inline
Initializes a new instance of the ReportUtilities class.
Parameters
user AdWords user to be used along with this utilities object.
Member Function Documentation
ClientReport Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities.DownloadClientReport (string query, string format, string path) inline
Downloads a report to disk.
Parameters
query The AWQL query for report definition.
format The report format.
path The path to which report should be downloaded.
Returns
The client report.
References Google.Api.Ads.Common.Util.DeprecationUtilities.ShowDeprecationMessage().
ClientReport Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities.DownloadClientReport (string query, string format, bool? returnMoneyInMicros, string path) inline
Downloads a report to disk.
Parameters
query The AWQL query for report definition.
format The report format.
path The path to which report should be downloaded.
returnMoneyInMicros True, if the money values in the report should be returned as micros, False otherwise.
Returns
The client report.
References Google.Api.Ads.AdWords.Lib.AdWordsAppConfig.AdWordsApiServer, and Google.Api.Ads.Common.Util.DeprecationUtilities.ShowDeprecationMessage().
ClientReport Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities.DownloadClientReport< T > (T reportDefinition, string path) inline
Downloads a report to disk.
Parameters
reportDefinition The report definition.
path The path to which report should be downloaded.
Returns
The client report.
References Google.Api.Ads.Common.Util.DeprecationUtilities.ShowDeprecationMessage().
ClientReport Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities.DownloadClientReport< T > (T reportDefinition, bool? returnMoneyInMicros, string path) inline
Downloads a report to disk.
Parameters
reportDefinition The report definition.
returnMoneyInMicros True, if the money values in the report should be returned as micros, False otherwise.
path The path to which report should be downloaded.
Returns
The client report.
References Google.Api.Ads.AdWords.Lib.AdWordsAppConfig.AdWordsApiServer, and Google.Api.Ads.Common.Util.DeprecationUtilities.ShowDeprecationMessage().
ClientReport Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities.GetClientReport (string query, string format) inline
Downloads a report into memory.
Parameters
query The AWQL query for report definition. See https://developers.google.com/adwords/api/docs/guides/awql for AWQL documentation.
format The report format.
Returns
The client report.
References Google.Api.Ads.Common.Util.DeprecationUtilities.ShowDeprecationMessage().
ClientReport Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities.GetClientReport (string query, string format, bool? returnMoneyInMicros) inline
Downloads a report into memory.
Parameters
query The AWQL query for report definition. See https://developers.google.com/adwords/api/docs/guides/awql for AWQL documentation.
format The report format.
returnMoneyInMicros True, if the money values in the report should be returned as micros, False otherwise.
Returns
The client report.
References Google.Api.Ads.AdWords.Lib.AdWordsAppConfig.AdWordsApiServer, and Google.Api.Ads.Common.Util.DeprecationUtilities.ShowDeprecationMessage().
ClientReport Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities.GetClientReport< T > (T reportDefinition) inline
Downloads a report into memory.
Parameters
reportDefinition The report definition.
Returns
The client report.
References Google.Api.Ads.Common.Util.DeprecationUtilities.ShowDeprecationMessage().
ClientReport Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities.GetClientReport< T > (T reportDefinition, bool? returnMoneyInMicros) inline
Downloads a report into memory.
Parameters
reportDefinition The report definition.
returnMoneyInMicros True, if the money values in the report should be returned as micros, False otherwise.
Returns
The client report.
References Google.Api.Ads.AdWords.Lib.AdWordsAppConfig.AdWordsApiServer, and Google.Api.Ads.Common.Util.DeprecationUtilities.ShowDeprecationMessage().
Property Documentation
string Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities.ReportVersion get set
Gets or sets the reporting API version to use.
AdWordsUser Google.Api.Ads.AdWords.Util.Reports.Legacy.ReportUtilities.User get
Returns the user associated with this object.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/src/AdWords/Util/Reports/Legacy/ReportUtilities.cs