Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPromotion Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPromotion Class Reference
This code example adds a new promotion to an express business. To get promotions, run GetPromotions.cs.
Public Member Functions
void Run (AdWordsUser user, long businessId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example adds a new promotion to an express business. To get promotions, run GetPromotions.cs.
Tags: ExpressBusinessService.get, PromotionService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPromotion.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPromotion.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPromotion.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPromotion.Run (AdWordsUser user, long businessId) inline
Runs the code example.
Parameters
user The AdWords user.
businessId The AdWords Express business id.
References Google.Api.Ads.AdWords.v201409.Promotion.budget, Google.Api.Ads.AdWords.v201409.Promotion.callTrackingEnabled, Google.Api.Ads.AdWords.v201409.Promotion.creatives, Google.Api.Ads.AdWords.v201409.Promotion.criteria, Google.Api.Ads.AdWords.v201409.Promotion.destinationUrl, Google.Api.Ads.AdWords.v201409.ExpressBusinessPage.entries, Google.Api.Ads.AdWords.Headers.RequestHeader.expressBusinessId, Google.Api.Ads.AdWords.Lib.AdWordsService.v201409.ExpressBusinessService, Google.Api.Ads.AdWords.v201409.Predicate.field, Google.Api.Ads.AdWords.v201409.Selector.fields, Google.Api.Ads.AdWords.v201409.Proximity.geoPoint, Google.Api.Ads.AdWords.v201409.ExpressBusiness.geoPoint, Google.Api.Ads.AdWords.v201409.ExpressBusinessService.get(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetShortRandomString(), Google.Api.Ads.AdWords.v201409.Creative.headline, Google.Api.Ads.AdWords.v201409.Criterion.id, Google.Api.Ads.AdWords.v201409.Creative.line1, Google.Api.Ads.AdWords.v201409.Creative.line2, Google.Api.Ads.AdWords.v201409.Money.microAmount, Google.Api.Ads.AdWords.v201409.PromotionService.mutate(), Google.Api.Ads.AdWords.v201409.Promotion.name, Google.Api.Ads.AdWords.v201409.PromotionOperation.operand, Google.Api.Ads.AdWords.v201409.Selector.predicates, Google.Api.Ads.AdWords.Lib.AdWordsService.v201409.PromotionService, Google.Api.Ads.AdWords.v201409.Proximity.radiusDistanceUnits, Google.Api.Ads.AdWords.v201409.Proximity.radiusInUnits, Google.Api.Ads.AdWords.v201409.PromotionService.RequestHeader, Google.Api.Ads.AdWords.v201409.Promotion.status, Google.Api.Ads.AdWords.v201409.ProductService.text, and Google.Api.Ads.AdWords.v201409.Predicate.values.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPromotion.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPromotion.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPromotion.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201409/Express/AddPromotion.cs