Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker Class Reference
This code example adds an AdWords conversion tracker.
Public Member Functions
void Run (AdWordsUser user)
Runs the code example.
void Run (AdWordsUser user)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example adds an AdWords conversion tracker.
Tags: ConversionTrackerService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Run().
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException().
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Run (AdWordsUser user) inline
Runs the code example.
Parameters
user The AdWords user.
References Google.Api.Ads.AdWords.v201402.ConversionTracker.alwaysUseDefaultRevenueValue, Google.Api.Ads.AdWords.v201402.AdWordsConversionTracker.backgroundColor, Google.Api.Ads.AdWords.v201402.ConversionTracker.category, Google.Api.Ads.AdWords.v201402.AdWordsConversionTracker.conversionPageLanguage, Google.Api.Ads.AdWords.v201402.ConversionTracker.defaultRevenueValue, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetRandomString(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.ConversionTracker.id, Google.Api.Ads.AdWords.v201402.ConversionTracker.isProductAdsChargeable, Google.Api.Ads.AdWords.v201402.AdWordsConversionTracker.markupLanguage, Google.Api.Ads.AdWords.v201402.ConversionTrackerService.mutate(), Google.Api.Ads.AdWords.v201402.ConversionTracker.name, Google.Api.Ads.AdWords.v201402.ConversionTrackerOperation.operand, Google.Api.Ads.AdWords.v201402.ConversionTracker.productAdsChargeableConversionWindow, Google.Api.Ads.AdWords.v201402.ConversionTracker.status, Google.Api.Ads.AdWords.v201402.AdWordsConversionTracker.textFormat, Google.Api.Ads.AdWords.v201402.ConversionTrackerReturnValue.value, and Google.Api.Ads.AdWords.v201402.ConversionTracker.viewthroughLookbackWindow.
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Run (AdWordsUser user) inline
Runs the code example.
Parameters
user The AdWords user.
References Google.Api.Ads.AdWords.v201402.ConversionTracker.alwaysUseDefaultRevenueValue, Google.Api.Ads.AdWords.v201402.AdWordsConversionTracker.backgroundColor, Google.Api.Ads.AdWords.v201402.ConversionTracker.category, Google.Api.Ads.AdWords.v201402.AdWordsConversionTracker.conversionPageLanguage, Google.Api.Ads.AdWords.v201402.ConversionTracker.defaultRevenueValue, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetRandomString(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.ConversionTracker.id, Google.Api.Ads.AdWords.v201402.ConversionTracker.isProductAdsChargeable, Google.Api.Ads.AdWords.v201402.AdWordsConversionTracker.markupLanguage, Google.Api.Ads.AdWords.v201402.ConversionTrackerService.mutate(), Google.Api.Ads.AdWords.v201402.ConversionTracker.name, Google.Api.Ads.AdWords.v201402.ConversionTrackerOperation.operand, Google.Api.Ads.AdWords.v201402.ConversionTracker.productAdsChargeableConversionWindow, Google.Api.Ads.AdWords.v201402.ConversionTracker.status, Google.Api.Ads.AdWords.v201402.AdWordsConversionTracker.textFormat, Google.Api.Ads.AdWords.v201402.ConversionTrackerReturnValue.value, and Google.Api.Ads.AdWords.v201402.ConversionTracker.viewthroughLookbackWindow.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201402/Remarketing/AddConversionTracker.cs