Ads API .NET library: Google.Api.Ads.AdWords.Lib.AdWordsSoapClient Class Reference
Google.Api.Ads.AdWords.Lib.AdWordsSoapClient Class Reference
Base class for AdWords API services.
Public Attributes
const string SERVICE_NAME = "adwords"
Service name to be used when getting auth token for AdWords.
Protected Member Functions
override void InitForCall (string methodName, object[] parameters)
Initializes the service before MakeApiCall.
override void CleanupAfterCall (string methodName, object[] parameters)
Cleans up the service after MakeApiCall.
override ErrorHandler CreateErrorHandler ()
Creates the error handler.
override WebRequest GetWebRequest (Uri uri)
Creates a WebRequest instance for the specified url.
override Exception GetCustomException (SoapException exception)
Gets a custom exception that wraps the SOAP exception thrown by the server.
Protected Member Functions inherited from Google.Api.Ads.Common.Lib.AdsSoapClient
new object[] Invoke (string methodName, object[] parameters)
Invokes a SOAP service method synchronously using SOAP.
new IAsyncResult BeginInvoke (string methodName, object[] parameters, AsyncCallback callback, object asyncState)
Starts an asynchronous invocation of a SOAP service method using SOAP.
new object[] EndInvoke (IAsyncResult asyncResult)
Ends an asynchronous invocation of a SOAP service method using SOAP.
virtual object[] MakeApiCall (string methodName, object[] parameters)
This method makes the actual SOAP API call. It is a thin wrapper over SOAPHttpClientProtocol:Invoke, and provide things like protection from race condition.
override WebRequest GetWebRequest (Uri uri)
Creates a WebRequest instance for the specified url.
override WebResponse GetWebResponse (WebRequest request)
Returns a response from a synchronous request to an XML Web service method.
override WebResponse GetWebResponse (WebRequest request, IAsyncResult result)
Returns a response from an asynchronous request to a SOAP service method.
string GetDefaultNamespace ()
Gets the default XML namespace, based on the type of this object.
Additional Inherited Members
Static Protected Member Functions inherited from Google.Api.Ads.Common.Lib.AdsSoapClient
static XmlElement GetFaultNode (SoapException exception, string ns, string nodeName)
Extracts the fault xml node from soap exception.
Properties inherited from Google.Api.Ads.Common.Lib.AdsSoapClient
AdsUser User [get, set]
Gets or sets the AdsUser object that created this service.
ServiceSignature Signature [get, set]
Gets or sets the signature for this service.
WebRequest LastRequest [get, set]
Gets or sets the web request associated with this service's last API call.
WebResponse LastResponse [get, set]
Gets or sets the web response associated with this service's last API call.
Properties inherited from Google.Api.Ads.Common.Lib.AdsClient
string ConnectionGroupName [get, set]
Gets or sets the name of the connection group for the request.
ICredentials Credentials [get, set]
Gets or sets security credentials for client authentication.
bool PreAuthenticate [get, set]
Gets or sets whether pre-authentication is enabled.
Encoding RequestEncoding [get, set]
The System.Text.Encoding used to make the client request to the service.
int Timeout [get, set]
The timeout for the request.
string Url [get, set]
The url endpoint for the service.
bool UseDefaultCredentials [get, set]
Gets or sets whether this service should use the credentials from System.Net.CredentialCache.DefaultCredentials.
bool AllowAutoRedirect [get, set]
Gets or sets whether the client automatically follows server redirects.
X509CertificateCollection ClientCertificates [get]
Gets the collection of client certificates.
CookieContainer CookieContainer [get, set]
Gets or sets the collection of cookies.
bool EnableDecompression [get, set]
Gets or sets whether gzip compression is enabled.
IWebProxy Proxy [get, set]
Gets or sets proxy information for making a service request through a firewall.
bool UnsafeAuthenticatedConnectionSharing [get, set]
Gets or sets a value that indicates whether connection sharing is enabled when the client uses NTLM authentication to connect to the Web server that hosts the web service.
string UserAgent [get, set]
Gets or sets the value for the user agent header that is sent with each request.
AdsUser User [get, set]
Gets or sets the AdsUser object that created this service.
ServiceSignature Signature [get, set]
Gets or sets the signature for this service.
WebRequest LastRequest [get, set]
Gets or sets the web request associated with this service's last API call.
WebResponse LastResponse [get, set]
Gets or sets the web response associated with this service's last API call.
Detailed Description
Base class for AdWords API services.
Member Function Documentation
override void Google.Api.Ads.AdWords.Lib.AdWordsSoapClient.CleanupAfterCall (string methodName, object[] parameters) inline protected virtual
Cleans up the service after MakeApiCall.
Parameters
methodName Name of the method.
parameters The method parameters.
Reimplemented from Google.Api.Ads.Common.Lib.AdsSoapClient.
override ErrorHandler Google.Api.Ads.AdWords.Lib.AdWordsSoapClient.CreateErrorHandler () inline protected virtual
Creates the error handler.
Returns
The error handler instance.
Reimplemented from Google.Api.Ads.Common.Lib.AdsSoapClient.
override Exception Google.Api.Ads.AdWords.Lib.AdWordsSoapClient.GetCustomException (SoapException exception) inline protected virtual
Gets a custom exception that wraps the SOAP exception thrown by the server.
Parameters
exception SOAPException that was thrown by the server.
Returns
A custom exception object that wraps the SOAP exception.
Reimplemented from Google.Api.Ads.Common.Lib.AdsSoapClient.
References Google.Api.Ads.Common.Util.SerializationUtilities.DeserializeFromXmlTextCustomRootNs(), Google.Api.Ads.Common.Lib.ContextStore.GetValue(), and Google.Api.Ads.AdWords.Lib.AdWordsErrorHandler.IsOAuthTokenExpiredError().
override WebRequest Google.Api.Ads.AdWords.Lib.AdWordsSoapClient.GetWebRequest (Uri uri) inline protected
Creates a WebRequest instance for the specified url.
Parameters
uri The Uri to use when creating the WebRequest.
Returns
The WebRequest instance.
References Google.Api.Ads.Common.Lib.ContextStore.GetValue().
override void Google.Api.Ads.AdWords.Lib.AdWordsSoapClient.InitForCall (string methodName, object[] parameters) inline protected virtual
Initializes the service before MakeApiCall.
Parameters
methodName Name of the method.
parameters The method parameters.
Reimplemented from Google.Api.Ads.Common.Lib.AdsSoapClient.
References Google.Api.Ads.AdWords.Headers.RequestHeader.clientCustomerId, Google.Api.Ads.AdWords.Headers.RequestHeader.developerToken, Google.Api.Ads.AdWords.Headers.RequestHeader.expressBusinessIdSpecified, and Google.Api.Ads.AdWords.Headers.RequestHeader.pageIdSpecified.
Member Data Documentation
const string Google.Api.Ads.AdWords.Lib.AdWordsSoapClient.SERVICE_NAME = "adwords"
Service name to be used when getting auth token for AdWords.
The documentation for this class was generated from the following file:
/tmp/tmp.5ulTs6gGZA/dist/github/src/AdWords/Lib/AdWordsSoapClient.cs