Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetThirdPartyRedirectAds Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetThirdPartyRedirectAds Class Reference
This code example retrieves all third party redirect ads given an existing ad group. To add third party redirect ads to an existing ad group, run AddThirdPartyRedirectAd.cs.
Public Member Functions
void Run (AdWordsUser user, long adGroupId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example retrieves all third party redirect ads given an existing ad group. To add third party redirect ads to an existing ad group, run AddThirdPartyRedirectAd.cs.
Tags: AdGroupAdService.get
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetThirdPartyRedirectAds.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetThirdPartyRedirectAds.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetThirdPartyRedirectAds.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetThirdPartyRedirectAds.Run (AdWordsUser user, long adGroupId) inline
Runs the code example.
Parameters
user The AdWords user.
adGroupId Id of the ad group from which third party redirect ads are retrieved.
References Google.Api.Ads.AdWords.v201406.AdGroupAd.ad, Google.Api.Ads.AdWords.Lib.AdWordsService.v201406.AdGroupAdService, Google.Api.Ads.AdWords.v201406.Ad.displayUrl, Google.Api.Ads.AdWords.v201406.AdGroupAdPage.entries, Google.Api.Ads.AdWords.v201406.OrderBy.field, Google.Api.Ads.AdWords.v201406.Predicate.field, Google.Api.Ads.AdWords.v201406.Selector.fields, Google.Api.Ads.AdWords.v201406.AdGroupAdService.get(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201406.Ad.id, Google.Api.Ads.AdWords.v201406.Paging.numberResults, Google.Api.Ads.AdWords.v201406.Selector.ordering, Google.Api.Ads.AdWords.v201406.Selector.paging, Google.Api.Ads.AdWords.v201406.Selector.predicates, Google.Api.Ads.AdWords.v201406.RichMediaAd.snippet, Google.Api.Ads.AdWords.v201406.OrderBy.sortOrder, Google.Api.Ads.AdWords.v201406.Paging.startIndex, Google.Api.Ads.AdWords.v201406.AdGroupAd.status, Google.Api.Ads.AdWords.v201406.Page.totalNumEntries, Google.Api.Ads.AdWords.v201406.Ad.url, and Google.Api.Ads.AdWords.v201406.Predicate.values.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetThirdPartyRedirectAds.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetThirdPartyRedirectAds.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetThirdPartyRedirectAds.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdXBuyer/CSharp/v201406/BasicOperations/GetThirdPartyRedirectAds.cs