Ads API .NET library: Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLineItems Class Reference
Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLineItems Class Reference
This code example creates new line items. To determine which line items exist, run GetAllLineItems.cs. To determine which orders exist, run GetAllOrders.cs. To determine which placements exist, run GetAllPlacements.cs. To determine the IDs for locations, run GetAllCities.cs, GetAllCountries.cs, GetAllMetros.cs, GetAllRegions.cs and GetAllPostalCodes.
Public Member Functions
override void Run (DfpUser user)
Run the code examples.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current time stamp.
Detailed Description
This code example creates new line items. To determine which line items exist, run GetAllLineItems.cs. To determine which orders exist, run GetAllOrders.cs. To determine which placements exist, run GetAllPlacements.cs. To determine the IDs for locations, run GetAllCities.cs, GetAllCountries.cs, GetAllMetros.cs, GetAllRegions.cs and GetAllPostalCodes.
Tags: LineItemService.createLineItems
Member Function Documentation
static void Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLineItems.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLineItems.Run (DfpUser user) inline virtual
Run the code examples.
Parameters
user The DFP user object running the code examples.
Implements Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfp.v201405.LineItemSummary.allowOverbook, Google.Api.Ads.Dfp.v201405.BrowserTargeting.browsers, Google.Api.Ads.Dfp.v201405.TechnologyTargeting.browserTargeting, Google.Api.Ads.Dfp.v201405.LineItemSummary.costPerUnit, Google.Api.Ads.Dfp.v201405.LineItemSummary.costType, Google.Api.Ads.Dfp.v201405.LineItemService.createLineItems(), Google.Api.Ads.Dfp.v201405.LineItemSummary.creativePlaceholders, Google.Api.Ads.Dfp.v201405.LineItemSummary.creativeRotationType, Google.Api.Ads.Dfp.v201405.Money.currencyCode, Google.Api.Ads.Dfp.v201405.DayPart.dayOfWeek, Google.Api.Ads.Dfp.v201405.DayPartTargeting.dayParts, Google.Api.Ads.Dfp.v201405.Targeting.dayPartTargeting, Google.Api.Ads.Dfp.v201405.UserDomainTargeting.domains, Google.Api.Ads.Dfp.v201405.LineItemSummary.endDateTime, Google.Api.Ads.Dfp.v201405.DayPart.endTime, Google.Api.Ads.Dfp.v201405.GeoTargeting.excludedLocations, Google.Api.Ads.Dfp.Util.v201405.DateTimeUtilities.FromDateTime(), Google.Api.Ads.Dfp.v201405.Targeting.geoTargeting, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfp.v201405.Size.height, Google.Api.Ads.Dfp.v201405.TimeOfDay.hour, Google.Api.Ads.Dfp.v201405.Technology.id, Google.Api.Ads.Dfp.v201405.Location.id, Google.Api.Ads.Dfp.v201405.LineItemSummary.id, Google.Api.Ads.Dfp.v201405.Targeting.inventoryTargeting, Google.Api.Ads.Dfp.v201405.Size.isAspectRatio, Google.Api.Ads.Dfp.v201405.BrowserTargeting.isTargeted, Google.Api.Ads.Dfp.Lib.DfpService.v201405.LineItemService, Google.Api.Ads.Dfp.v201405.LineItemSummary.lineItemType, Google.Api.Ads.Dfp.v201405.Money.microAmount, Google.Api.Ads.Dfp.v201405.TimeOfDay.minute, Google.Api.Ads.Dfp.v201405.LineItemSummary.name, Google.Api.Ads.Dfp.v201405.LineItemSummary.orderId, Google.Api.Ads.Dfp.v201405.LineItemSummary.primaryGoal, Google.Api.Ads.Dfp.v201405.CreativePlaceholder.size, Google.Api.Ads.Dfp.v201405.LineItemSummary.startDateTimeType, Google.Api.Ads.Dfp.v201405.DayPart.startTime, Google.Api.Ads.Dfp.v201405.UserDomainTargeting.targeted, Google.Api.Ads.Dfp.v201405.GeoTargeting.targetedLocations, Google.Api.Ads.Dfp.v201405.InventoryTargeting.targetedPlacementIds, Google.Api.Ads.Dfp.v201405.LineItem.targeting, Google.Api.Ads.Dfp.v201405.Targeting.technologyTargeting, Google.Api.Ads.Dfp.v201405.DayPartTargeting.timeZone, Google.Api.Ads.Dfp.v201405.Goal.units, Google.Api.Ads.Dfp.v201405.Goal.unitType, Google.Api.Ads.Dfp.v201405.Targeting.userDomainTargeting, and Google.Api.Ads.Dfp.v201405.Size.width.
Property Documentation
override string Google.Api.Ads.Dfp.Examples.CSharp.v201405.CreateLineItems.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfp/CSharp/v201405/LineItemService/CreateLineItems.cs