Ads API .NET library: Google.Api.Ads.AdWords.v201809.Predicate Class Reference
Google.Api.Ads.AdWords.v201809.Predicate Class Reference
Specifies how an entity (eg. adgroup, campaign, criterion, ad) should be filtered.
Public Member Functions
override string ToString ()
Returns a string that represents this instance.
Static Public Member Functions
static Predicate Equals (string field, long value)
Adds a filter to select only items where the value of field is equal to value .
static Predicate Equals (string field, string value)
Adds a filter to select only items where the value of field is equal to value .
static Predicate NotEquals (string field, string value)
Adds a filter to select only items where the value of field is not equal to value .
static Predicate In (string field, List< string > values)
Adds a filter to select only items where the value of field is equal to one of the values provided in values .
static Predicate In (string field, string[] values)
Adds a filter to select only items where the value of field is equal of the values provided in values .
static Predicate NotIn (string field, string[] values)
Adds a filter to select only items where the value of field is not equal to any of the values provided in values .
static Predicate GreaterThan (string field, string value)
Adds a filter to select only items where the value of field is greater than value .
static Predicate GreaterThanEquals (string field, string value)
Adds a filter for items where field is greater than or equal to value .
static Predicate LessThan (string field, string value)
Adds a filter to select only items where the value of field is less than value .
static Predicate LessThanEquals (string field, string value)
Adds a filter to select only items where the value of field is less than or equal to value .
static Predicate StartsWith (string field, string value)
Adds a filter to select only items where the value of field starts with value .
static Predicate StartsWithIgnoreCase (string field, string value)
Adds a filter to select only items where the value of field starts with value when letter case is ignored.
static Predicate Contains (string field, string value)
Adds a filter to select only items where the value of field contains value .
static Predicate ContainsIgnoreCase (string field, string value)
Adds a filter to select only items where the value of field contains value when letter case is ignored.
static Predicate DoesNotContain (string field, string value)
Adds a filter to select only items where the value of field does not contain value .
static Predicate DoesNotContainIgnoreCase (string field, string value)
Adds a filter to select only items where the value of field does not contain value when letter case is ignored.
static Predicate ContainsAny (string field, string[] values)
Adds a filter to select only items where the value of field contains any of the values provided in values .
static Predicate ContainsAll (string field, string[] values)
Adds a filter to select only items where the value of field contains all of the values provided in values .
static Predicate ContainsNone (string field, string[] values)
Adds a filter to select only items where the value of field contains none of the values provided in values .
Public Attributes
PredicateOperator operator{get{return this.operatorField
The operator to use for filtering the data returned. This field is required and should not be
Properties
string field [get, set]
The field by which to filter the returned data. Possible values are marked Filterable on the entity's reference page. For example, for predicates for the CampaignService selector, refer to the filterable fields from the Campaign reference page. This field is required and should not be
this[System.Xml.Serialization.XmlIgnoreAttribute()][EditorBrowsable(EditorBrowsableState.Never)]
bool operatorSpecified [get, set]
string[] values [get, set]
The values by which to filter the field. The Operator::CONTAINS_ALL, Operator::CONTAINS_ANY, Operator::CONTAINS_NONE, Operator::IN and Operator::NOT_IN take multiple values. All others take a single value. This field must not contain
Detailed Description
Specifies how an entity (eg. adgroup, campaign, criterion, ad) should be filtered.
Specifies how an entity (eg. adgroup, campaign, criterion, ad) should be filtered.
Member Function Documentation
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.Contains (string field, string value) inline static
Adds a filter to select only items where the value of field contains value .
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field contains value .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.ContainsAll (string field, string[] values) inline static
Adds a filter to select only items where the value of field contains all of the values provided in values .
Parameters
field The field to filter on.
values The predicate value.
Returns
A new Predicate object that filters only items where the value of field contains all of the values provided in values .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.ContainsAny (string field, string[] values) inline static
Adds a filter to select only items where the value of field contains any of the values provided in values .
Parameters
field The field to filter on.
values The predicate value.
Returns
A new Predicate object that filters only items where the value of field contains any of the values provided in values .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.ContainsIgnoreCase (string field, string value) inline static
Adds a filter to select only items where the value of field contains value when letter case is ignored.
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field contains value when letter case is ignored.
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.ContainsNone (string field, string[] values) inline static
Adds a filter to select only items where the value of field contains none of the values provided in values .
Parameters
field The field to filter on.
values The predicate value.
Returns
A new Predicate object that filters only items where the value of field contains none of the values provided in values .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.DoesNotContain (string field, string value) inline static
Adds a filter to select only items where the value of field does not contain value .
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field does not contain value .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.DoesNotContainIgnoreCase (string field, string value) inline static
Adds a filter to select only items where the value of field does not contain value when letter case is ignored.
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field does not contain value when letter case is ignored.
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.Equals (string field, long value) inline static
Adds a filter to select only items where the value of field is equal to value .
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field is equal to value
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201809.LookupLocation.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201809.GetAllDisapprovedAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201809.GetKeywords.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201809.GetExpandedTextAds.Run(), and Google.Api.Ads.AdWords.Examples.CSharp.v201809.GetResponsiveSearchAds.Run().
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.Equals (string field, string value) inline static
Adds a filter to select only items where the value of field is equal to value .
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field is equal to value
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.GreaterThan (string field, string value) inline static
Adds a filter to select only items where the value of field is greater than value .
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field is greater than value .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.GreaterThanEquals (string field, string value) inline static
Adds a filter for items where field is greater than or equal to value .
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field is greater than or equal to value .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.In (string field, List< string > values) inline static
Adds a filter to select only items where the value of field is equal to one of the values provided in values .
Parameters
field The field to filter on.
values The predicate values.
Returns
A new Predicate object that filters only items where the value of field is equal to one of the values provided in values .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.In (string field, string[] values) inline static
Adds a filter to select only items where the value of field is equal of the values provided in values .
Parameters
field The field to filter on.
values The predicate values.
Returns
A new Predicate object that filters only items where the value of field is equal to one of the values provided in values .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.LessThan (string field, string value) inline static
Adds a filter to select only items where the value of field is less than value .
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field is less than value .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.LessThanEquals (string field, string value) inline static
Adds a filter to select only items where the value of field is less than or equal to value .
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field is less than or equal to value .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.NotEquals (string field, string value) inline static
Adds a filter to select only items where the value of field is not equal to value .
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field is not equal to value
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.NotIn (string field, string[] values) inline static
Adds a filter to select only items where the value of field is not equal to any of the values provided in values .
Parameters
field The field to filter on.
values The predicate values.
Returns
A new Predicate object that filters only items where the value of field is not equal to any of the values provided in values .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.StartsWith (string field, string value) inline static
Adds a filter to select only items where the value of field starts with value .
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field starts with value .
static Predicate Google.Api.Ads.AdWords.v201809.Predicate.StartsWithIgnoreCase (string field, string value) inline static
Adds a filter to select only items where the value of field starts with value when letter case is ignored.
Parameters
field The field to filter on.
value The predicate value.
Returns
A new Predicate object that filters only items where the value of field starts with value when letter case is ignored.
override string Google.Api.Ads.AdWords.v201809.Predicate.ToString () inline
Returns a string that represents this instance.
Returns
A string that represents this instance.
Member Data Documentation
PredicateOperator Google.Api.Ads.AdWords.v201809.Predicate.operator{get{return this.operatorField
The operator to use for filtering the data returned. This field is required and should not be
null.
Property Documentation
string Google.Api.Ads.AdWords.v201809.Predicate.field get set
The field by which to filter the returned data. Possible values are marked Filterable on the entity's reference page. For example, for predicates for the CampaignService selector, refer to the filterable fields from the Campaign reference page. This field is required and should not be
null.
this[System.Xml.Serialization.XmlIgnoreAttribute()] [EditorBrowsable(EditorBrowsableState.Never)] bool Google.Api.Ads.AdWords.v201809.Predicate.operatorSpecified get set
string [] Google.Api.Ads.AdWords.v201809.Predicate.values get set
The values by which to filter the field. The Operator::CONTAINS_ALL, Operator::CONTAINS_ANY, Operator::CONTAINS_NONE, Operator::IN and Operator::NOT_IN take multiple values. All others take a single value. This field must not contain
elements. This field is required and should not be null.
The documentation for this class was generated from the following files:
dist/github/src/AdWords/v201809/AdWordsApi.cs
dist/github/src/AdWords/v201809/Predicate.cs