Ads API .NET library: Google.Api.Ads.AdWords.Util.Reports.v201802.SelectQuery Class Reference
Google.Api.Ads.AdWords.Util.Reports.v201802.SelectQuery Class Reference
A select query, returned by SelectQueryBuilder
Inherits Google.Api.Ads.AdWords.Util.Reports.ISelectQuery< TParent, TBuilder, TPage >.
Public Member Functions
SelectQuery (SelectQueryBuilder builder)
Initializes a new instance of the SelectQuery class.
SelectQuery Limit (uint startIndex, uint numberResults)
Adds a LIMIT clause to the query.
bool HasNextPage (Page page)
Determines whether the query has next page.
SelectQuery NextPage (Page page)
Advances the query by a page.
override string ToString ()
Returns a string that represents this instance.
SelectQuery DefaultLimit ()
Adds a LIMIT clause to the query with default values.
Public Member Functions inherited from Google.Api.Ads.AdWords.Util.Reports.ISelectQuery< TParent, TBuilder, TPage >
bool HasNextPage (TPage page)
Determines whether the query has next page.
TParent NextPage (TPage page)
Advances the query by a page.
Public Member Functions inherited from Google.Api.Ads.AdWords.Util.Reports.ILimitBuilder< TParent >
TParent Limit (uint startIndex, uint numberResults)
Adds a LIMIT clause to the query.
TParent DefaultLimit ()
Adds a LIMIT clause to the query with default values.
Static Public Member Functions
static implicit operator string (SelectQuery x)
Performs an implicit conversion from SelectQuery to string.
Properties
SelectQueryBuilder Builder [get]
Gets the builder.
Properties inherited from Google.Api.Ads.AdWords.Util.Reports.ISelectQuery< TParent, TBuilder, TPage >
TBuilder Builder [get]
Gets the builder.
Detailed Description
A select query, returned by SelectQueryBuilder
Constructor & Destructor Documentation
Google.Api.Ads.AdWords.Util.Reports.v201802.SelectQuery.SelectQuery (SelectQueryBuilder builder) inline
Initializes a new instance of the SelectQuery class.
Parameters
builder The builder.
Member Function Documentation
SelectQuery Google.Api.Ads.AdWords.Util.Reports.v201802.SelectQuery.DefaultLimit () inline
Adds a LIMIT clause to the query with default values.
Returns
The parent builder for call chaining.
bool Google.Api.Ads.AdWords.Util.Reports.v201802.SelectQuery.HasNextPage (Page page) inline
Determines whether the query has next page.
Parameters
page The page.
Returns
True if there's a next page, false otherwise.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201802.GetCampaignsWithAwql.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201802.GetAllDisapprovedAdsWithAwql.Run(), and Google.Api.Ads.AdWords.Examples.CSharp.v201802.GetKeywordBidSimulations.Run().
SelectQuery Google.Api.Ads.AdWords.Util.Reports.v201802.SelectQuery.Limit (uint startIndex, uint numberResults) inline
Adds a LIMIT clause to the query.
Parameters
startIndex The start index.
numberResults The number of results.
Returns
The parent builder for call chaining.
SelectQuery Google.Api.Ads.AdWords.Util.Reports.v201802.SelectQuery.NextPage (Page page) inline
Advances the query by a page.
Parameters
page The page.
Returns
The parent builder for call chaining.
static implicit Google.Api.Ads.AdWords.Util.Reports.v201802.SelectQuery.operator string (SelectQuery x) inline static
Performs an implicit conversion from SelectQuery to string.
Parameters
x The SelectQuery to convert.
Returns
The result of the conversion.
override string Google.Api.Ads.AdWords.Util.Reports.v201802.SelectQuery.ToString () inline
Returns a string that represents this instance.
Returns
A string that represents this instance.
Property Documentation
SelectQueryBuilder Google.Api.Ads.AdWords.Util.Reports.v201802.SelectQuery.Builder get
Gets the builder.
The documentation for this class was generated from the following file:
dist/github/src/AdWords/Util/Reports/QueryBuilder/v201802/SelectQuery.cs