Ads API .NET library: Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAudienceSegments Class Reference
Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAudienceSegments Class Reference
This code example creates new rule based first party audience segments. To determine which audience segments exist, run GetAllAudienceSegments.cs.
Public Member Functions
override void Run (DfpUser user)
Run the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current time stamp.
Detailed Description
This code example creates new rule based first party audience segments. To determine which audience segments exist, run GetAllAudienceSegments.cs.
Tags: AudienceSegmentService.createAudienceSegments
Member Function Documentation
static void Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAudienceSegments.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAudienceSegments.Run (DfpUser user) inline virtual
Run the code example.
Parameters
user The DFP user object running the code example.
Implements Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfp.v201403.AdUnitTargeting.adUnitId, Google.Api.Ads.Dfp.Lib.DfpService.v201403.AudienceSegmentService, Google.Api.Ads.Dfp.v201403.CustomCriteriaSet.children, Google.Api.Ads.Dfp.v201403.AudienceSegmentService.createAudienceSegments(), Google.Api.Ads.Dfp.v201403.FirstPartyAudienceSegmentRule.customCriteriaRule, Google.Api.Ads.Dfp.v201403.AudienceSegment.description, Google.Api.Ads.Dfp.v201403.Network.effectiveRootAdUnitId, Google.Api.Ads.Dfp.v201403.NetworkService.getCurrentNetwork(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfp.v201403.AudienceSegment.id, Google.Api.Ads.Dfp.v201403.AdUnitTargeting.includeDescendants, Google.Api.Ads.Dfp.v201403.FirstPartyAudienceSegmentRule.inventoryRule, Google.Api.Ads.Dfp.v201403.CustomCriteria.keyId, Google.Api.Ads.Dfp.v201403.CustomCriteriaSet.logicalOperator, Google.Api.Ads.Dfp.v201403.RuleBasedFirstPartyAudienceSegmentSummary.membershipExpirationDays, Google.Api.Ads.Dfp.v201403.AudienceSegment.name, Google.Api.Ads.Dfp.Lib.DfpService.v201403.NetworkService, Google.Api.Ads.Dfp.v201403.RuleBasedFirstPartyAudienceSegmentSummary.pageViews, Google.Api.Ads.Dfp.v201403.RuleBasedFirstPartyAudienceSegmentSummary.recencyDays, Google.Api.Ads.Dfp.v201403.RuleBasedFirstPartyAudienceSegment.rule, Google.Api.Ads.Dfp.v201403.InventoryTargeting.targetedAdUnits, Google.Api.Ads.Dfp.v201403.AudienceSegment.type, and Google.Api.Ads.Dfp.v201403.CustomCriteria.valueIds.
Property Documentation
override string Google.Api.Ads.Dfp.Examples.CSharp.v201403.CreateAudienceSegments.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfp/CSharp/v201403/AudienceSegmentService/CreateAudienceSegments.cs