Ads API .NET library: Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateFlashInpageCreative Class Reference
Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateFlashInpageCreative Class Reference
This code example creates a "Flash InPage" creative in a given advertiser or campaign. If no campaign is specified then the creative is created in the advertiser provided. To get assets file names, run CreateHTMLAsset.cs and CreateImageAsset.cs. To get a size id, run GetSize.cs. To get a creative type id, run GetCreativeType.cs.
Public Member Functions
override void Run (DfaUser user)
Run the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfa.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfa.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current timestamp as a string.
String GetHomeDir ()
Gets the current user's home directory.
Detailed Description
This code example creates a "Flash InPage" creative in a given advertiser or campaign. If no campaign is specified then the creative is created in the advertiser provided. To get assets file names, run CreateHTMLAsset.cs and CreateImageAsset.cs. To get a size id, run GetSize.cs. To get a creative type id, run GetCreativeType.cs.
Tags: creative.saveCreative
Member Function Documentation
static void Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateFlashInpageCreative.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfa.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfa.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateFlashInpageCreative.Run (DfaUser user) inline virtual
Run the code example.
Parameters
user The Dfa user object running the code example.
Implements Google.Api.Ads.Dfa.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfa.v1_20.CreativeBase.active, Google.Api.Ads.Dfa.v1_20.CreativeBase.advertiserId, Google.Api.Ads.Dfa.v1_20.HTMLCreativeAsset.assetFilename, Google.Api.Ads.Dfa.v1_20.FlashInpageCreative.backupImageAsset, Google.Api.Ads.Dfa.v1_20.FlashInpageCreative.backupImageTargetWindow, Google.Api.Ads.Dfa.v1_20.FlashInpageCreative.codeLocked, Google.Api.Ads.Dfa.Lib.DfaService.v1_20.CreativeRemoteService, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfa.v1_20.Base.id, Google.Api.Ads.Dfa.v1_20.SaveResult.id, Google.Api.Ads.Dfa.v1_20.Base.name, Google.Api.Ads.Dfa.v1_20.TargetWindow.option, Google.Api.Ads.Dfa.v1_20.FlashInpageCreative.parentFlashAsset, Google.Api.Ads.Dfa.v1_20.CreativeRemoteService.saveCreative(), Google.Api.Ads.Dfa.v1_20.CreativeBase.sizeId, Google.Api.Ads.Dfa.v1_20.CreativeBase.typeId, and Google.Api.Ads.Dfa.v1_20.FlashInpageCreative.wmode.
Property Documentation
override string Google.Api.Ads.Dfa.Examples.CSharp.v1_20.CreateFlashInpageCreative.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfa/CSharp/v1_20/CreateFlashInpageCreative.cs