Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError Class Reference
This code example adds a text ad, and shows how to handle a policy violation.
Public Member Functions
void Run (AdWordsUser user, long adGroupId)
Runs the code example.
void Run (AdWordsUser user, long adGroupId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example adds a text ad, and shows how to handle a policy violation.
Tags: AdGroupAdService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Run().
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException().
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Run (AdWordsUser user, long adGroupId) inline
Runs the code example.
Parameters
user The AdWords user.
adGroupId Id of the ad group to which ads are added.
References Google.Api.Ads.AdWords.v201402.AdGroupAd.ad, Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.AdGroupAdService, Google.Api.Ads.AdWords.v201402.AdGroupAd.adGroupId, Google.Api.Ads.AdWords.Lib.AdWordsApiException.ApiException, Google.Api.Ads.AdWords.v201402.RichMediaAd.certifiedVendorFormatId, Google.Api.Ads.AdWords.v201402.RichMediaAd.dimensions, Google.Api.Ads.AdWords.v201402.Ad.displayUrl, Google.Api.Ads.AdWords.v201402.ApiError.fieldPath, Google.Api.Ads.AdWords.Util.ErrorUtilities.GetOperationIndex(), Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetRandomString(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.Dimensions.height, Google.Api.Ads.AdWords.v201402.Ad.id, Google.Api.Ads.AdWords.v201402.RichMediaAd.impressionBeaconUrl, Google.Api.Ads.AdWords.v201402.ThirdPartyRedirectAd.isCookieTargeted, Google.Api.Ads.AdWords.v201402.PolicyViolationError.isExemptable, Google.Api.Ads.AdWords.v201402.ThirdPartyRedirectAd.isTagged, Google.Api.Ads.AdWords.v201402.ThirdPartyRedirectAd.isUserInterestTargeted, Google.Api.Ads.AdWords.v201402.PolicyViolationError.key, Google.Api.Ads.AdWords.v201402.ExemptionRequest.key, Google.Api.Ads.AdWords.v201402.AdGroupAdService.mutate(), Google.Api.Ads.AdWords.v201402.RichMediaAd.name, Google.Api.Ads.AdWords.v201402.AdGroupAdOperation.operand, Google.Api.Ads.AdWords.v201402.AdGroupAdService.RequestHeader, Google.Api.Ads.AdWords.v201402.RichMediaAd.snippet, Google.Api.Ads.AdWords.v201402.Ad.url, Google.Api.Ads.AdWords.Headers.RequestHeader.validateOnly, Google.Api.Ads.AdWords.v201402.AdGroupAdReturnValue.value, and Google.Api.Ads.AdWords.v201402.Dimensions.width.
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Run (AdWordsUser user, long adGroupId) inline
Runs the code example.
Parameters
user The AdWords user.
adGroupId Id of the ad group to which ads are added.
References Google.Api.Ads.AdWords.v201402.AdGroupAd.ad, Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.AdGroupAdService, Google.Api.Ads.AdWords.v201402.AdGroupAd.adGroupId, Google.Api.Ads.AdWords.Lib.AdWordsApiException.ApiException, Google.Api.Ads.AdWords.v201402.TextAd.description1, Google.Api.Ads.AdWords.v201402.TextAd.description2, Google.Api.Ads.AdWords.v201402.Ad.displayUrl, Google.Api.Ads.AdWords.v201402.ApiError.fieldPath, Google.Api.Ads.AdWords.Util.ErrorUtilities.GetOperationIndex(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.TextAd.headline, Google.Api.Ads.AdWords.v201402.Ad.id, Google.Api.Ads.AdWords.v201402.PolicyViolationError.isExemptable, Google.Api.Ads.AdWords.v201402.PolicyViolationError.key, Google.Api.Ads.AdWords.v201402.ExemptionRequest.key, Google.Api.Ads.AdWords.v201402.AdGroupAdService.mutate(), Google.Api.Ads.AdWords.v201402.AdGroupAdOperation.operand, Google.Api.Ads.AdWords.v201402.AdGroupAdService.RequestHeader, Google.Api.Ads.AdWords.v201402.Ad.url, Google.Api.Ads.AdWords.Headers.RequestHeader.validateOnly, and Google.Api.Ads.AdWords.v201402.AdGroupAdReturnValue.value.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201402/ErrorHandling/HandlePolicyViolationError.cs