Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment Class Reference
This code example creates an experiment using a query percentage of 10, which defines what fraction of auctions should go to the control split (90%) vs. the experiment split (10%), then adds experimental bid changes for criteria and ad groups. To get campaigns, run GetCampaigns.cs. To get ad groups, run GetAdGroups.cs. To get criteria, run GetKeywords.cs.
Public Member Functions
void Run (AdWordsUser user, long campaignId, long adGroupId, long criterionId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example creates an experiment using a query percentage of 10, which defines what fraction of auctions should go to the control split (90%) vs. the experiment split (10%), then adds experimental bid changes for criteria and ad groups. To get campaigns, run GetCampaigns.cs. To get ad groups, run GetAdGroups.cs. To get criteria, run GetKeywords.cs.
Tags: ExperimentService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment.Run (AdWordsUser user, long campaignId, long adGroupId, long criterionId) inline
Runs the code example.
Parameters
user The AdWords user.
campaignId Id of the campaign to which experiments are added.
adGroupId Id of the ad group to which experiments are added.
criterionId Id of the criterion for which experiments are added.
References Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.AdGroupCriterionService, Google.Api.Ads.AdWords.v201402.AdGroupCriterion.adGroupId, Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.AdGroupService, Google.Api.Ads.AdWords.v201402.Experiment.campaignId, Google.Api.Ads.AdWords.v201402.AdGroupCriterion.criterion, Google.Api.Ads.AdWords.v201402.Criterion.CriterionType, Google.Api.Ads.AdWords.v201402.Experiment.endDateTime, Google.Api.Ads.AdWords.v201402.BiddableAdGroupCriterionExperimentData.experimentBidMultiplier, Google.Api.Ads.AdWords.v201402.AdGroupExperimentData.experimentBidMultipliers, Google.Api.Ads.AdWords.v201402.AdGroup.experimentData, Google.Api.Ads.AdWords.v201402.BiddableAdGroupCriterion.experimentData, Google.Api.Ads.AdWords.v201402.AdGroupExperimentData.experimentDeltaStatus, Google.Api.Ads.AdWords.v201402.BiddableAdGroupCriterionExperimentData.experimentDeltaStatus, Google.Api.Ads.AdWords.v201402.AdGroupExperimentData.experimentId, Google.Api.Ads.AdWords.v201402.BiddableAdGroupCriterionExperimentData.experimentId, Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.ExperimentService, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetRandomString(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.Criterion.id, Google.Api.Ads.AdWords.v201402.Experiment.id, Google.Api.Ads.AdWords.v201402.AdGroup.id, Google.Api.Ads.AdWords.v201402.ManualCPCAdGroupExperimentBidMultipliers.maxCpcMultiplier, Google.Api.Ads.AdWords.v201402.ManualCPCAdGroupCriterionExperimentBidMultiplier.maxCpcMultiplier, Google.Api.Ads.AdWords.v201402.BidMultiplier.multiplier, Google.Api.Ads.AdWords.v201402.ExperimentService.mutate(), Google.Api.Ads.AdWords.v201402.AdGroupCriterionService.mutate(), Google.Api.Ads.AdWords.v201402.AdGroupService.mutate(), Google.Api.Ads.AdWords.v201402.Experiment.name, Google.Api.Ads.AdWords.v201402.AdGroup.name, Google.Api.Ads.AdWords.v201402.ExperimentOperation.operand, Google.Api.Ads.AdWords.v201402.AdGroupOperation.operand, Google.Api.Ads.AdWords.v201402.AdGroupCriterionOperation.operand, Google.Api.Ads.AdWords.v201402.Experiment.queryPercentage, Google.Api.Ads.AdWords.v201402.Experiment.startDateTime, Google.Api.Ads.AdWords.v201402.Experiment.status, Google.Api.Ads.AdWords.v201402.AdGroup.status, Google.Api.Ads.AdWords.v201402.ExperimentReturnValue.value, Google.Api.Ads.AdWords.v201402.AdGroupCriterionReturnValue.value, and Google.Api.Ads.AdWords.v201402.AdGroupReturnValue.value.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201402/CampaignManagement/AddExperiment.cs