Ads API .NET library: Google.Api.Ads.AdManager.Util.v202402.DateTimeUtilities Class Reference
Google.Api.Ads.AdManager.Util.v202402.DateTimeUtilities Class Reference
A utility class that allows you to build Datetime objects from strings.
Static Public Member Functions
static AdManagerDateTime FromString (string dateString, string timeZoneId)
Converts the string in format yyyyMMdd HH:mm:ss to a DateTime object with the specified time zone.
static AdManagerDateTime FromDateTime (System.DateTime dateTime, string timeZoneId)
Converts a System.DateTime object to a AdManager DateTime object with the specified timeZoneId. Does not perform time zone conversion. This means the returned DateTime value may not represent the same instant as the System.DateTime value.
static string ToString (AdManagerDateTime dateTime, string patternText)
Formats the value of the DFP date time using the specified NodaTime compatibleformat.
static string ToString (AdManagerDateTime dateTime, string patternText, IFormatProvider formatProvider)
Formats the value of the DFP date time using the specified NodaTime compatibleformat.
Detailed Description
A utility class that allows you to build Datetime objects from strings.
Member Function Documentation
static AdManagerDateTime Google.Api.Ads.AdManager.Util.v202402.DateTimeUtilities.FromDateTime (System.DateTime dateTime, string timeZoneId) inline static
Converts a System.DateTime object to a AdManager DateTime object with the specified timeZoneId. Does not perform time zone conversion. This means the returned DateTime value may not represent the same instant as the System.DateTime value.
Parameters
dateTime The DateTime object.
timeZoneId The timeZoneId to use.
Returns
A AdManager Datetime object.
Referenced by Google.Api.Ads.AdManager.Examples.CSharp.v202402.GetAvailabilityForecast.Run(), Google.Api.Ads.AdManager.Examples.CSharp.v202402.GetTrafficData.Run(), Google.Api.Ads.AdManager.Examples.CSharp.v202402.GetMcmEarnings.Run(), Google.Api.Ads.AdManager.Examples.CSharp.v202402.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.AdManager.Examples.CSharp.v202402.GetOrdersStartingSoon.Run(), and Google.Api.Ads.AdManager.Examples.CSharp.v202402.GetRecentlyModifiedContent.Run().
static AdManagerDateTime Google.Api.Ads.AdManager.Util.v202402.DateTimeUtilities.FromString (string dateString, string timeZoneId) inline static
Converts the string in format yyyyMMdd HH:mm:ss to a DateTime object with the specified time zone.
Parameters
dateString The date string.
timeZoneId The timeZoneId to set.
Returns
A AdManager Datetime object.
static string Google.Api.Ads.AdManager.Util.v202402.DateTimeUtilities.ToString (AdManagerDateTime dateTime, string patternText) inline static
Formats the value of the DFP date time using the specified NodaTime compatibleformat.
Referenced by Google.Api.Ads.AdManager.Examples.CSharp.v202402.GetAvailabilityForecast.Run().
static string Google.Api.Ads.AdManager.Util.v202402.DateTimeUtilities.ToString (AdManagerDateTime dateTime, string patternText, IFormatProvider formatProvider) inline static
Formats the value of the DFP date time using the specified NodaTime compatibleformat.
The documentation for this class was generated from the following file:
dist/github/src/AdManager/Util/v202402/DateTimeUtilities.cs