Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension Class Reference
This code example adds a feed that syncs feed items from a Google Places account and associates the feed with a customer.
Public Member Functions
void Run (AdWordsUser user, string placesEmailAddress, string placesAccessToken)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example adds a feed that syncs feed items from a Google Places account and associates the feed with a customer.
Tags: CustomerFeedService.mutate, FeedItemService.mutate Tags: FeedMappingService.mutate, FeedService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension.Run (AdWordsUser user, string placesEmailAddress, string placesAccessToken) inline
Runs the code example.
Parameters
user The AdWords user.
placesEmailAddress The email address for Google Places account.
placesAccessToken The OAuth2 access token for Google Places account.
References Google.Api.Ads.AdWords.Lib.AdWordsApiException.ApiException, Google.Api.Ads.AdWords.v201406.ConstantOperand.booleanValue, Google.Api.Ads.AdWords.Lib.AdWordsService.v201406.CustomerFeedService, Google.Api.Ads.Common.Lib.ErrorHandler.DoExponentialBackoff(), Google.Api.Ads.AdWords.v201406.PlacesLocationFeedData.emailAddress, Google.Api.Ads.AdWords.v201406.ApiException.errors, Google.Api.Ads.AdWords.v201406.CustomerFeed.feedId, Google.Api.Ads.AdWords.Lib.AdWordsService.v201406.FeedService, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetRandomString(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Common.Lib.ErrorHandler.HaveMoreRetryAttemptsLeft(), Google.Api.Ads.AdWords.v201406.OAuthInfo.httpAuthorizationHeader, Google.Api.Ads.AdWords.v201406.OAuthInfo.httpMethod, Google.Api.Ads.AdWords.v201406.OAuthInfo.httpRequestUrl, Google.Api.Ads.AdWords.v201406.Feed.id, Google.Api.Ads.Common.Lib.ErrorHandler.IncrementRetriedAttempts(), Google.Api.Ads.AdWords.v201406.Function.lhsOperand, Google.Api.Ads.AdWords.v201406.CustomerFeed.matchingFunction, Google.Api.Ads.AdWords.v201406.CustomerFeedService.mutate(), Google.Api.Ads.AdWords.v201406.FeedService.mutate(), Google.Api.Ads.AdWords.v201406.Feed.name, Google.Api.Ads.AdWords.v201406.PlacesLocationFeedData.oAuthInfo, Google.Api.Ads.AdWords.v201406.CustomerFeedOperation.operand, Google.Api.Ads.AdWords.v201406.FeedOperation.operand, Google.Api.Ads.AdWords.v201406.Feed.origin, Google.Api.Ads.AdWords.v201406.CustomerFeed.placeholderTypes, Google.Api.Ads.Common.Lib.AppConfigBase.RetryCount, Google.Api.Ads.AdWords.v201406.Feed.systemFeedGenerationData, Google.Api.Ads.AdWords.v201406.ConstantOperand.type, Google.Api.Ads.AdWords.v201406.CustomerFeedReturnValue.value, and Google.Api.Ads.AdWords.v201406.FeedReturnValue.value.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201406/AdvancedOperations/AddPlacesLocationExtension.cs