Ads API .NET library: Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateRotationGroup Class Reference
Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateRotationGroup Class Reference
This code example creates a rotation group ad in a given campaign. To get ad types run GetAdTypes.cs. Start and end date for the ad must be within campaign start and end dates. To create creatives, run CreateCreatives.cs. To get available placements, run GetPlacement.cs. To get a size id, run GetSize.cs.
Public Member Functions
override void Run (DfaUser user)
Run the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfa.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfa.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current timestamp as a string.
String GetHomeDir ()
Gets the current user's home directory.
Detailed Description
This code example creates a rotation group ad in a given campaign. To get ad types run GetAdTypes.cs. Start and end date for the ad must be within campaign start and end dates. To create creatives, run CreateCreatives.cs. To get available placements, run GetPlacement.cs. To get a size id, run GetSize.cs.
Tags: ad.saveAd
Member Function Documentation
static void Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateRotationGroup.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfa.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfa.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateRotationGroup.Run (DfaUser user) inline virtual
Run the code example.
Parameters
user The Dfa user object running the code example.
Implements Google.Api.Ads.Dfa.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfa.v1_19.AdBase.active, Google.Api.Ads.Dfa.v1_19.PlacementAssignment.active, Google.Api.Ads.Dfa.v1_19.CreativeAssignment.active, Google.Api.Ads.Dfa.Lib.DfaService.v1_19.AdRemoteService, Google.Api.Ads.Dfa.v1_19.AdBase.archived, Google.Api.Ads.Dfa.v1_19.AdBase.campaignId, Google.Api.Ads.Dfa.v1_19.CreativeAssignment.clickThroughUrl, Google.Api.Ads.Dfa.v1_19.RotationGroup.creativeAssignments, Google.Api.Ads.Dfa.v1_19.CreativeAssignment.creativeId, Google.Api.Ads.Dfa.v1_19.ClickThroughUrl.defaultLandingPageUsed, Google.Api.Ads.Dfa.v1_19.AdBase.endTime, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfa.v1_19.Base.id, Google.Api.Ads.Dfa.v1_19.SaveResult.id, Google.Api.Ads.Dfa.v1_19.ClickThroughUrl.landingPageId, Google.Api.Ads.Dfa.v1_19.Base.name, Google.Api.Ads.Dfa.v1_19.AdBase.placementAssignments, Google.Api.Ads.Dfa.v1_19.PlacementAssignment.placementId, Google.Api.Ads.Dfa.v1_19.TargetableAdBase.priority, Google.Api.Ads.Dfa.v1_19.TargetableAdBase.ratio, Google.Api.Ads.Dfa.v1_19.RotationGroup.rotationType, Google.Api.Ads.Dfa.v1_19.AdRemoteService.saveAd(), Google.Api.Ads.Dfa.v1_19.AdBase.sizeId, Google.Api.Ads.Dfa.v1_19.AdBase.startTime, and Google.Api.Ads.Dfa.v1_19.AdBase.typeId.
Property Documentation
override string Google.Api.Ads.Dfa.Examples.CSharp.v1_19.CreateRotationGroup.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfa/CSharp/v1_19/CreateRotationGroup.cs