Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities Class Reference
Utility class for assisting in running code examples.
Static Public Member Functions
static string GetRandomString ()
Gets a random string. Useful for generating unique names for campaigns, ad groups, etc.
static string GetShortRandomString ()
Gets a random string. Useful for generating unique names for campaigns, ad groups, etc.
static string FormatException (Exception ex)
Formats the exception as a printable message.
static String GetHomeDir ()
Gets the current user's home directory.
static List< object > GetParameters (MethodInfo methodInfo)
Gets the parameters for running the code example.
static string GetRandomString ()
Gets a random string. Useful for generating unique names for campaigns, ad groups, etc.
static string GetShortRandomString ()
Gets a random string. Useful for generating unique names for campaigns, ad groups, etc.
static string FormatException (Exception ex)
Formats the exception as a printable message.
static String GetHomeDir ()
Gets the current user's home directory.
static List< object > GetParameters (MethodInfo methodInfo)
Gets the parameters for running the code example.
Detailed Description
Utility class for assisting in running code examples.
Member Function Documentation
static string Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException (Exception ex) inline static
Formats the exception as a printable message.
Parameters
ex The exception.
Returns
The formatted exception string.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.PauseAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.PauseAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.PauseAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.EstimateKeywordTraffic.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.EstimateKeywordTraffic.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.EstimateKeywordTraffic.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddAudience.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddAudience.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddAudience.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddConversionTracker.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddConversionTracker.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DownloadCriteriaReport.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.DownloadCriteriaReport.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.DownloadCriteriaReport.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAllDisapprovedAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetReportFields.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetReportFields.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetReportFields.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.LookupLocation.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.LookupLocation.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.LookupLocation.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAllDisapprovedAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetAllDisapprovedAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddCampaignLabels.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddCampaignLabels.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeleteAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePartialFailures.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.HandlePartialFailures.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.RemovePlacement.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.RemoveKeyword.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.RemovePlacement.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.RemoveCampaign.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.HandlePartialFailures.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeleteAdGroup.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeleteCampaign.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeleteKeyword.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAdGroups.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroups.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetAdGroups.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetCampaigns.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetCampaigns.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.UploadImage.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UploadImage.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UploadImage.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywords.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAdGroupBidSimulations.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidSimulations.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetAdGroupBidSimulations.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetKeywords.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywords.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordIdeas.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.UpdatePlacement.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetKeywordIdeas.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywordIdeas.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetPlacementIdeas.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetPlacementIdeas.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetTextAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetTextAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetTextAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.CreateAccount.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.CreateAccount.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetCampaigns.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdateAdGroup.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DownloadCriteriaReportWithAwql.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdateAdGroup.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.DownloadCriteriaReportWithAwql.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.DownloadCriteriaReportWithAwql.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.UpdateAdGroup.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdateCampaign.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdateCampaign.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.UpdateCampaign.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdateKeyword.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdateKeyword.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.UpdateKeyword.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaignTargetingCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddCampaignTargetingCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddCampaignTargetingCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddLocationExtension.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddLocationExtension.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddLocationExtension.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.CreateAccount.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddAdGroupDemographicCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.RemoveAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.RemoveAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.RemoveAdGroup.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddAdGroupDemographicCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.RemoveAdGroup.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.RemoveCampaign.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.RemoveKeyword.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddAdGroupDemographicCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetCampaignsByLabel.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetCampaignsByLabel.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddPlacements.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacements.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPlacements.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeletePlacement.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetPlacements.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetPlacements.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetPlacements.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdatePlacement.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdatePlacement.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.UploadOfflineConversions.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.UseSharedBiddingStrategy.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetAdParameters.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.ValidateTextAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.ValidateTextAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetAllDisapprovedAdsWithAwql.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.HandlePolicyViolationError.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.HandlePolicyViolationError.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UploadOfflineConversions.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAllDisapprovedAdsWithAwql.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetAccountChanges.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddAdGroupBidModifier.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetCampaignsWithAwql.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAllVideosAndImages.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAllVideosAndImages.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetAllVideosAndImages.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetCampaignsWithAwql.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetTargetableLanguagesAndCarriers.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetCampaignsWithAwql.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordBidSimulations.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetKeywordBidSimulations.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetTargetableLanguagesAndCarriers.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetThirdPartyRedirectAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetThirdPartyRedirectAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddAdGroupBidModifier.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.SetAdParameters.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.SetAdParameters.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAdGroupBidModifiers.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.PromoteExperiment.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAccountChanges.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAdGroupBidModifiers.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetAdGroupBidModifiers.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetCampaignTargetingCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetCampaignTargetingCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetCampaignTargetingCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetTargetableLanguagesAndCarriers.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UploadOfflineConversions.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddAdGroupBidModifier.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetKeywordBidSimulations.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAllDisapprovedAdsWithAwql.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAccountChanges.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.PromoteExperiment.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.PromoteExperiment.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UseSharedBiddingStrategy.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UseSharedBiddingStrategy.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetThirdPartyRedirectAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.ValidateTextAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAccountAlerts.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddClickToDownloadAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetAccountHierarchy.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAccountHierarchy.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetAccountAlerts.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddClickToDownloadAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.SetBidModifier.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetAccountHierarchy.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddClickToDownloadAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetBidModifier.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.SetBidModifier.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddPlacementsInBulk.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddAdCustomizers.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAdWithUpgradedUrls.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddKeywordsInBulk.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacementsInBulk.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddAdCustomizers.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddTextAdWithUpgradedUrls.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddKeywordsInBulk.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPlacementsInBulk.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywordsInBulk.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddRuleBasedRemarketingList.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandleRateExceededError.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.HandleRateExceededError.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.HandleRateExceededError.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddCampaigns.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddCampaigns.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaigns.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddExperiment.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddExperiment.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddAdGroups.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddKeywords.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddKeywords.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddKeywords.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddThirdPartyRedirectAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddAdGroups.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddAdGroups.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddThirdPartyRedirectAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddTextAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTextAds.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.SetProductSalesChannel.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.SetProductSalesChannel.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroup.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetBudgetSuggestion.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroupCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTargetingGroupCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetBudgetSuggestion.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddVideoAd.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignStats.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTargetingGroup.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetVideoCampaignStats.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddVideoCampaign.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdatePromotion.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetProductServices.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.UpdateExpressBusiness.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCallToAction.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPromotion.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetProductServices.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaignCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddShoppingCampaign.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddPromotion.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExpressBusinesses.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddExpressBusinesses.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddExpressBusinesses.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdateExpressBusiness.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPromotion.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdateExpressBusiness.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdatePromotion.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddShoppingCampaign.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetProductServices.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.UpdatePromotion.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddVideoCallToAction.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddShoppingCampaign.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddVideoCampaignCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetExpressBusinesses.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetPromotions.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetPromotions.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetExpressBusinesses.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetExpressBusinesses.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddProductScope.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductScope.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetPromotions.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddProductScope.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetKeywordCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetVideoCampaignCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetTargetingGroups.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetTargetingGroups.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetVideoCampaigns.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetKeywordCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.FindVideos.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignCriteria.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.FindVideos.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaigns.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPlacesLocationExtension.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddPlacesLocationExtension.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddSiteLinks.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddSiteLinks.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddSiteLinks.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetProductCategoryTaxonomy.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetProductCategoryTaxonomy.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.GetProductCategoryTaxonomy.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddProductPartitionTree.Main(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddProductPartitionTree.Main(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddProductPartitionTree.Main().
static string Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException (Exception ex) inline static
Formats the exception as a printable message.
Parameters
ex The exception.
Returns
The formatted exception string.
static String Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetHomeDir () inline static
Gets the current user's home directory.
Returns
The current user's home directory.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.DownloadCriteriaReport.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.DownloadCriteriaReport.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.DownloadCriteriaReport.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.DownloadCriteriaReportWithAwql.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.DownloadCriteriaReportWithAwql.Run(), and Google.Api.Ads.AdWords.Examples.CSharp.v201409.DownloadCriteriaReportWithAwql.Run().
static String Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetHomeDir () inline static
Gets the current user's home directory.
Returns
The current user's home directory.
static List<object> Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetParameters (MethodInfo methodInfo) inline static
Gets the parameters for running the code example.
Parameters
methodInfo The method info for Run method in code example.
Returns
An array of parameters for running the code example.
static List<object> Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetParameters (MethodInfo methodInfo) inline static
Gets the parameters for running the code example.
Parameters
methodInfo The method info for Run method in code example.
Returns
An array of parameters for running the code example.
static string Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetRandomString () inline static
Gets a random string. Useful for generating unique names for campaigns, ad groups, etc.
Returns
The current timestamp as a string.
static string Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetRandomString () inline static
Gets a random string. Useful for generating unique names for campaigns, ad groups, etc.
Returns
The current timestamp as a string.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddAudience.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddAudience.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddAudience.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddConversionTracker.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddConversionTracker.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddConversionTracker.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddVideoCampaign.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddVideoCampaign.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UseSharedBiddingStrategy.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UseSharedBiddingStrategy.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.UseSharedBiddingStrategy.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddCampaigns.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTargetingGroup.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.HandlePolicyViolationError.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.HandlePolicyViolationError.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.HandlePolicyViolationError.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddCampaigns.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddTargetingGroup.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddCampaigns.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddThirdPartyRedirectAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddAdGroups.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddAdGroups.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddThirdPartyRedirectAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddThirdPartyRedirectAds.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddAdGroups.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddExperiment.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExperiment.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddExperiment.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPlacesLocationExtension.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPlacesLocationExtension.Run(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddPlacesLocationExtension.Run().
static string Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetShortRandomString () inline static
Gets a random string. Useful for generating unique names for campaigns, ad groups, etc.
Returns
The current timestamp as a string.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddExpressBusinesses.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddExpressBusinesses.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddExpressBusinesses.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.UpdateExpressBusiness.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201409.AddPromotion.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddPromotion.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201402.AddPromotion.Run(), Google.Api.Ads.AdWords.Examples.CSharp.v201406.UpdateExpressBusiness.Run(), and Google.Api.Ads.AdWords.Examples.CSharp.v201409.UpdateExpressBusiness.Run().
static string Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.GetShortRandomString () inline static
Gets a random string. Useful for generating unique names for campaigns, ad groups, etc.
Returns
The current timestamp as a string.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/ExampleUtilities.cs