Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201402.EstimateKeywordTraffic Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201402.EstimateKeywordTraffic Class Reference
This code example gets keyword traffic estimates.
Public Member Functions
void Run (AdWordsUser user)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example gets keyword traffic estimates.
Tags: TrafficEstimatorService.get
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.EstimateKeywordTraffic.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201402.EstimateKeywordTraffic.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.EstimateKeywordTraffic.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.EstimateKeywordTraffic.Run (AdWordsUser user) inline
Runs the code example.
Parameters
user The AdWords user.
References Google.Api.Ads.AdWords.v201402.CampaignEstimateRequest.adGroupEstimateRequests, Google.Api.Ads.AdWords.v201402.CampaignEstimate.adGroupEstimates, Google.Api.Ads.AdWords.v201402.StatsEstimate.averageCpc, Google.Api.Ads.AdWords.v201402.StatsEstimate.averagePosition, Google.Api.Ads.AdWords.v201402.TrafficEstimatorSelector.campaignEstimateRequests, Google.Api.Ads.AdWords.v201402.TrafficEstimatorResult.campaignEstimates, Google.Api.Ads.AdWords.v201402.StatsEstimate.clicksPerDay, Google.Api.Ads.AdWords.v201402.CampaignEstimateRequest.criteria, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.Criterion.id, Google.Api.Ads.AdWords.v201402.KeywordEstimateRequest.isNegative, Google.Api.Ads.AdWords.v201402.KeywordEstimateRequest.keyword, Google.Api.Ads.AdWords.v201402.AdGroupEstimateRequest.keywordEstimateRequests, Google.Api.Ads.AdWords.v201402.AdGroupEstimate.keywordEstimates, Google.Api.Ads.AdWords.v201402.Keyword.matchType, Google.Api.Ads.AdWords.v201402.KeywordEstimate.max, Google.Api.Ads.AdWords.v201402.AdGroupEstimateRequest.maxCpc, Google.Api.Ads.AdWords.v201402.Money.microAmount, Google.Api.Ads.AdWords.v201402.KeywordEstimate.min, Google.Api.Ads.AdWords.v201402.Keyword.text, Google.Api.Ads.AdWords.v201402.StatsEstimate.totalCost, and Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.TrafficEstimatorService.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.EstimateKeywordTraffic.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201402.EstimateKeywordTraffic.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.EstimateKeywordTraffic.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201402/Optimization/EstimateKeywordTraffic.cs