Ads API .NET library: Google.Api.Ads.Dfp.Util.v201408.StatementBuilder Class Reference
Google.Api.Ads.Dfp.Util.v201408.StatementBuilder Class Reference
A utility class that allows for statements to be constructed in parts. Typical usage is:
Public Member Functions
StatementBuilder ()
Constructs a statement builder for partial query building.
StatementBuilder (string query)
Constructs a statement builder with a complete query.
StatementBuilder Select (String columns)
Sets the statement SELECT clause in the form of "a,b". Only necessary for statements being sent to the PublisherQueryLanguageService. The "SELECT " keyword will be ignored.
StatementBuilder From (String table)
Sets the statement FROM clause in the form of "table". Only necessary for statements being sent to the PublisherQueryLanguageService. The "FROM " keyword will be ignored.
StatementBuilder Where (String conditions)
Sets the statement WHERE clause in the form of
StatementBuilder Limit (Int32 count)
Sets the statement LIMIT clause in the form of
StatementBuilder Offset (Int32 count)
Sets the statement OFFSET clause in the form of
StatementBuilder IncreaseOffsetBy (Int32 amount)
Increases the offset by the given amount.
int GetOffset ()
Gets the curent offset
StatementBuilder RemoveLimitAndOffset ()
Removes the limit and offset from the query.
StatementBuilder OrderBy (String orderBy)
Sets the statement ORDER BY clause in the form of
StatementBuilder AddValue (string key, string value)
Adds a new string value to the list of query parameters.
StatementBuilder AddValue (string key, bool value)
Adds a new boolean value to the list of query parameters.
StatementBuilder AddValue (string key, decimal value)
Adds a new decimal value to the list of query parameters.
StatementBuilder AddValue (string key, DateTime value)
Adds a new DateTime value to the list of query parameters.
StatementBuilder AddValue (string key, Date value)
Adds a new Date value to the list of query parameters.
Statement ToStatement ()
Gets the Statement representing the state of this statement builder.
Public Attributes
const int SUGGESTED_PAGE_LIMIT = 500
Protected Attributes
string query
string select
string from
string where
int limit = null
int offset = null
string orderBy
Properties
string Query [get, set]
Gets or sets the statement query.
Detailed Description
A utility class that allows for statements to be constructed in parts. Typical usage is:
StatementBuilder statementBuilder = new StatementBuilder() .Where("lastModifiedTime > :yesterday AND type = :type") .OrderBy("name DESC") .Limit(200) .Offset(20) .AddValue("yesterday", DateTimeUtilities.FromDateTime(System.DateTime.Now.AddDays(-1))) .AddValue("type", "Type"); Statement statement = statementBuilder.ToStatement(); // ... statementBuilder.increaseOffsetBy(20); statement = statementBuilder.ToStatement();
Constructor & Destructor Documentation
Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.StatementBuilder () inline
Constructs a statement builder for partial query building.
Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.StatementBuilder (string query) inline
Constructs a statement builder with a complete query.
Parameters
query The query string.
Member Function Documentation
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.AddValue (string key, string value) inline
Adds a new string value to the list of query parameters.
Parameters
key The parameter name.
value The parameter value.
Returns
The statement builder, for chaining method calls.
References Google.Api.Ads.Dfp.v201408.TextValue.value.
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitSizes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunInventoryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.PopulateFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.TargetCustomCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.SetLineItemCustomFieldValue.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLineItem.Run().
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.AddValue (string key, bool value) inline
Adds a new boolean value to the list of query parameters.
Parameters
key The parameter name.
value The parameter value.
Returns
The statement builder, for chaining method calls.
References Google.Api.Ads.Dfp.v201408.BooleanValue.value.
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.AddValue (string key, decimal value) inline
Adds a new decimal value to the list of query parameters.
Parameters
key The parameter name.
value The parameter value.
Returns
The statement builder, for chaining method calls.
References Google.Api.Ads.Dfp.v201408.NumberValue.value.
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.AddValue (string key, DateTime value) inline
Adds a new DateTime value to the list of query parameters.
Parameters
key The parameter name.
value The parameter value.
Returns
The statement builder, for chaining method calls.
References Google.Api.Ads.Dfp.v201408.DateTimeValue.value.
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.AddValue (string key, Date value) inline
Adds a new Date value to the list of query parameters.
Parameters
key The parameter name.
value The parameter value.
Returns
The statement builder, for chaining method calls.
References Google.Api.Ads.Dfp.v201408.DateValue.value.
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.From (String table) inline
Sets the statement FROM clause in the form of "table". Only necessary for statements being sent to the PublisherQueryLanguageService. The "FROM " keyword will be ignored.
Parameters
table The statement from clause without "FROM"
Returns
The statement builder, for chaining method calls.
References Google.Api.Ads.Dfp.Util.PreconditionUtilities.CheckArgumentNotNull().
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201408.FetchMatchTables.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemsUsingPql.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets.Run().
int Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.GetOffset () inline
Gets the curent offset
Returns
The current offset
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingValuesByStatement.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLineItem.Run().
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.IncreaseOffsetBy (Int32 amount) inline
Increases the offset by the given amount.
Parameters
amount the amount to increase the offset
Returns
The statement builder, for chaining method calls.
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemsUsingPql.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLineItem.Run().
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.Limit (Int32 count) inline
Sets the statement LIMIT clause in the form of
"LIMIT &lt;count&gt;"
Parameters
count the statement limit
Returns
The statement builder, for chaining method calls.
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.PopulateFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.FetchMatchTables.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemsUsingPql.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.TargetCustomCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.SetLineItemCustomFieldValue.Run().
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.Offset (Int32 count) inline
Sets the statement OFFSET clause in the form of
"OFFSET &lt;count&gt;"
Parameters
count the statement offset
Returns
The statement builder, for chaining method calls.
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.OrderBy (String orderBy) inline
Sets the statement ORDER BY clause in the form of
"ORDER BY &lt;property&gt; [ASC | DESC]" e.g. "type ASC, lastModifiedDateTime DESC". The "ORDER BY " keyword will be ignored.
Parameters
orderBy the statement order by without "ORDER BY"
Returns
The statement builder, for chaining method calls.
References Google.Api.Ads.Dfp.Util.PreconditionUtilities.CheckArgumentNotNull().
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.PopulateFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.FetchMatchTables.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemsUsingPql.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.TargetCustomCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.SetLineItemCustomFieldValue.Run().
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.RemoveLimitAndOffset () inline
Removes the limit and offset from the query.
Returns
The statement builder, for chaining method calls.
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReportWithCustomFields.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLineItem.Run().
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.Select (String columns) inline
Sets the statement SELECT clause in the form of "a,b". Only necessary for statements being sent to the PublisherQueryLanguageService. The "SELECT " keyword will be ignored.
Parameters
columns The statement serlect clause without "SELECT".
Returns
The statement builder, for chaining method calls.
References Google.Api.Ads.Dfp.Util.PreconditionUtilities.CheckArgumentNotNull().
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201408.FetchMatchTables.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemsUsingPql.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets.Run().
Statement Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.ToStatement () inline
Gets the Statement representing the state of this statement builder.
Returns
The statement.
References Google.Api.Ads.Dfp.v201408.Statement.query, and Google.Api.Ads.Dfp.v201408.Statement.values.
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitSizes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunInventoryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.PopulateFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemsUsingPql.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.TargetCustomCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.SetLineItemCustomFieldValue.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLineItem.Run().
StatementBuilder Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.Where (String conditions) inline
Sets the statement WHERE clause in the form of
"WHERE &lt;condition&gt; {[AND | OR] &lt;condition&gt; ...}" e.g. "a = b OR b = c". The "WHERE " keyword will be ignored.
Parameters
conditions The statement query without "WHERE"
Returns
The statement builder, for chaining method calls.
References Google.Api.Ads.Dfp.Util.PreconditionUtilities.CheckArgumentNotNull().
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitSizes.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunInventoryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.PopulateFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateUserTeamAssociations.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunDeliveryReport.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCustomTargetingKeys.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.TargetCustomCriteria.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.SetLineItemCustomFieldValue.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLineItem.Run().
Member Data Documentation
string Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.from protected
int Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.limit = null protected
int Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.offset = null protected
string Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.orderBy protected
string Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.query protected
string Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.select protected
const int Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.SUGGESTED_PAGE_LIMIT = 500
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllOrders.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllUsers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreativeTemplates.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativeTemplatesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllTeams.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeleteUserTeamAssociation.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCompaniesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCreativesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLicasByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.UpdateCompanies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveCreativeWrappers.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUninvitedContacts.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetPlacementsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContent.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUsersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetUserTeamAssociationsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetFirstPartyAudienceSegments.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveOrder.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllActivityGroups.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetActiveActivities.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingKeysByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAdUnitsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeActivateAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.FetchMatchTables.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateLicas.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllContentMetadataKeyHierarchies.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetRecentlyUpdatedLineItems.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetOrdersByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivatePlacement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.ApproveSuggestedAdUnits.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetTeamsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetLabelsByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomTargetingKeysAndValues.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateActiveLabels.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetSuggestedUnitByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.DeactivateUser.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetContentByCategory.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.RunReportWithCustomFields.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.CopyImageCreatives.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetCustomTargetingValuesByStatement.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetAllLineItemsUsingPql.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201408.GetGeoTargets.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201408.ActivateLineItem.Run().
string Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.where protected
Property Documentation
string Google.Api.Ads.Dfp.Util.v201408.StatementBuilder.Query get set
Gets or sets the statement query.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/src/Dfp/Util/v201408/StatementBuilder.cs