Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeletePlacement Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeletePlacement Class Reference
This code example deletes a placement using the 'REMOVE' operator. To get placements, run GetPlacements.cs.
Public Member Functions
void Run (AdWordsUser user, long adGroupId, long placementId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example deletes a placement using the 'REMOVE' operator. To get placements, run GetPlacements.cs.
Tags: AdGroupCriterionService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeletePlacement.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeletePlacement.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeletePlacement.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeletePlacement.Run (AdWordsUser user, long adGroupId, long placementId) inline
Runs the code example.
Parameters
user The AdWords user.
adGroupId Id of the ad group that contains the placement.
placementId Id of the placement to be deleted.
References Google.Api.Ads.AdWords.Lib.AdWordsService.v201402.AdGroupCriterionService, Google.Api.Ads.AdWords.v201402.AdGroupCriterion.adGroupId, Google.Api.Ads.AdWords.v201402.AdGroupCriterion.criterion, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201402.Criterion.id, Google.Api.Ads.AdWords.v201402.AdGroupCriterionService.mutate(), Google.Api.Ads.AdWords.v201402.AdGroupCriterionOperation.operand, and Google.Api.Ads.AdWords.v201402.AdGroupCriterionReturnValue.value.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeletePlacement.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeletePlacement.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201402.DeletePlacement.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdXBuyer/CSharp/v201402/BasicOperations/DeletePlacement.cs