Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetBudgetSuggestion Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetBudgetSuggestion Class Reference
This code example shows how to retrieve an AdWords Express budget suggestion.
Public Member Functions
void Run (AdWordsUser user)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example shows how to retrieve an AdWords Express budget suggestion.
Tags: BudgetSuggestionService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetBudgetSuggestion.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetBudgetSuggestion.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetBudgetSuggestion.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetBudgetSuggestion.Run (AdWordsUser user) inline
Runs the code example.
Parameters
user The AdWords user.
References Google.Api.Ads.AdWords.v201409.BudgetSuggestion.budgetQuantiles, Google.Api.Ads.AdWords.Lib.AdWordsService.v201409.BudgetSuggestionService, Google.Api.Ads.AdWords.v201409.BudgetSuggestion.cpc, Google.Api.Ads.AdWords.v201409.BudgetSuggestion.cpm, Google.Api.Ads.AdWords.v201409.BudgetSuggestionSelector.criteria, Google.Api.Ads.AdWords.v201409.BudgetSuggestionService.get(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201409.Criterion.id, Google.Api.Ads.AdWords.v201409.BudgetSuggestion.impressions, Google.Api.Ads.AdWords.v201409.BudgetSuggestion.maxBudget, Google.Api.Ads.AdWords.v201409.BudgetSuggestion.maxCpc, Google.Api.Ads.AdWords.v201409.Money.microAmount, Google.Api.Ads.AdWords.v201409.BudgetSuggestion.minBudget, Google.Api.Ads.AdWords.v201409.BudgetSuggestion.minCpc, and Google.Api.Ads.AdWords.v201409.BudgetSuggestion.suggestedBudget.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetBudgetSuggestion.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetBudgetSuggestion.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201409.GetBudgetSuggestion.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201409/Express/GetBudgetSuggestion.cs