Ads API .NET library: Google.Api.Ads.Dfp.Util.v201405.PqlUtilities Class Reference
Google.Api.Ads.Dfp.Util.v201405.PqlUtilities Class Reference
A utility class for handling PQL objects.
Static Public Member Functions
static object GetValue (Value value)
Gets the underlying value of the Value object.
static List< String[]> ResultSetToStringArrayList (ResultSet resultSet)
Gets the result set as list of string arrays.
static String ResultSetToString (ResultSet resultSet)
Gets the result set as a table represenation in the form of:
static String[] GetColumnLabels (ResultSet resultSet)
Gets the column labels for the result set.
static object[] GetRowValues (Row row)
Gets the row values for a row of the result set in the form of an object array.
static String[] GetRowStringValues (Row row)
Gets the row values for a row of the result set in a the form of a string array.
Detailed Description
A utility class for handling PQL objects.
Member Function Documentation
static String [] Google.Api.Ads.Dfp.Util.v201405.PqlUtilities.GetColumnLabels (ResultSet resultSet) inline static
Gets the column labels for the result set.
Parameters
resultSet The result set to get the column labels for.
Returns
The string array of column labels.
References Google.Api.Ads.Dfp.v201405.ColumnType.labelName.
static String [] Google.Api.Ads.Dfp.Util.v201405.PqlUtilities.GetRowStringValues (Row row) inline static
Gets the row values for a row of the result set in a the form of a string array.
null values are interperted as empty strings.
Parameters
row The row to get the values for.
Returns
The string array of the row values.
static object [] Google.Api.Ads.Dfp.Util.v201405.PqlUtilities.GetRowValues (Row row) inline static
Gets the row values for a row of the result set in the form of an object array.
Parameters
row The row to get the values for.
Returns
The object array of the row values.
static object Google.Api.Ads.Dfp.Util.v201405.PqlUtilities.GetValue (Value value) inline static
Gets the underlying value of the Value object.
The Value object to get the value from.
Returns
The underlying value.
static String Google.Api.Ads.Dfp.Util.v201405.PqlUtilities.ResultSetToString (ResultSet resultSet) inline static
Gets the result set as a table represenation in the form of:
+-------+-------+-------+
|column1|column2|column3|
+-------+-------+-------+
|value1 |value2 |value3 |
+-------+-------+-------+
|value1 |value2 |value3 |
+-------+-------+-------+
Parameters
resultSet The result set to display as a string
Returns
The string represenation of result set as a table.
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItemsUsingPql.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetGeoTargets.Run().
static List<String[]> Google.Api.Ads.Dfp.Util.v201405.PqlUtilities.ResultSetToStringArrayList (ResultSet resultSet) inline static
Gets the result set as list of string arrays.
Parameters
resultSet The result set to convert to a string array list.
Returns
A list of string arrays representing the result set.
References Google.Api.Ads.Dfp.v201405.ResultSet.rows.
Referenced by Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetLineItemsNamedLike.Run(), Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetAllLineItemsUsingPql.Run(), and Google.Api.Ads.Dfp.Examples.CSharp.v201405.GetGeoTargets.Run().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/src/Dfp/Util/v201405/PqlUtilities.cs