Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignStats Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignStats Class Reference
This code example illustrates how to retrieve stats for a video campaign.
Public Member Functions
void Run (AdWordsUser user, long campaignId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example illustrates how to retrieve stats for a video campaign.
Tags: VideoCampaignService.get
AdWords for Video API is a Beta feature.
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignStats.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignStats.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignStats.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignStats.Run (AdWordsUser user, long campaignId) inline
Runs the code example.
Parameters
user The AdWords user.
campaignId The campaign ID.
References Google.Api.Ads.AdWords.v201406.StatsSelector.dateRange, Google.Api.Ads.AdWords.v201406.VideoCampaignPage.entries, Google.Api.Ads.AdWords.v201406.VideoCampaignService.get(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201406.VideoCampaign.id, Google.Api.Ads.AdWords.v201406.VideoCampaignSelector.ids, Google.Api.Ads.AdWords.v201406.SegmentKey.Item, Google.Api.Ads.AdWords.v201406.DateRange.max, Google.Api.Ads.AdWords.v201406.StatsSelector.metrics, Google.Api.Ads.AdWords.v201406.DateRange.min, Google.Api.Ads.AdWords.v201406.VideoCampaign.name, Google.Api.Ads.AdWords.v201406.VideoCampaignSelector.paging, Google.Api.Ads.AdWords.v201406.StatsSelector.segmentationDimensions, Google.Api.Ads.AdWords.v201406.VideoCampaign.segmentedStats, Google.Api.Ads.AdWords.v201406.StatsSelector.segmentedSummaryType, Google.Api.Ads.AdWords.v201406.VideoEntityStats.segmentKey, Google.Api.Ads.AdWords.v201406.VideoCampaign.stats, Google.Api.Ads.AdWords.v201406.VideoCampaignSelector.statsSelector, Google.Api.Ads.AdWords.v201406.VideoCampaign.status, Google.Api.Ads.AdWords.v201406.VideoCampaignPage.summaryStats, Google.Api.Ads.AdWords.v201406.VideoEntityStats.summaryType, Google.Api.Ads.AdWords.v201406.StatsSelector.summaryTypes, and Google.Api.Ads.AdWords.Lib.AdWordsService.v201406.VideoCampaignService.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignStats.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignStats.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.GetVideoCampaignStats.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201406/AdWordsForVideo/GetVideoCampaignStats.cs