Ads API .NET library: Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAdWithUpgradedUrls Class Reference
Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAdWithUpgradedUrls Class Reference
This code example adds a text ad that uses upgraded URLs. This example will only work if your account is a test account or is whitelisted for this feature.
Public Member Functions
void Run (AdWordsUser user, long adGroupId)
Runs the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.AdWords.Examples.CSharp.ExampleBase
abstract string Description [get]
Returns a description about the code example.
Detailed Description
This code example adds a text ad that uses upgraded URLs. This example will only work if your account is a test account or is whitelisted for this feature.
Tags: AdGroupAdService.mutate
Member Function Documentation
static void Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAdWithUpgradedUrls.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAdWithUpgradedUrls.Description, Google.Api.Ads.AdWords.Examples.CSharp.ExampleUtilities.FormatException(), and Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAdWithUpgradedUrls.Run().
void Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAdWithUpgradedUrls.Run (AdWordsUser user, long adGroupId) inline
Runs the code example.
Parameters
user The AdWords user.
adGroupId ID of the ad group to which ad is added.
References Google.Api.Ads.AdWords.v201406.AdGroupAd.ad, Google.Api.Ads.AdWords.Lib.AdWordsService.v201406.AdGroupAdService, Google.Api.Ads.AdWords.v201406.AdGroupAd.adGroupId, Google.Api.Ads.AdWords.v201406.TextAd.description1, Google.Api.Ads.AdWords.v201406.TextAd.description2, Google.Api.Ads.AdWords.v201406.Ad.displayUrl, Google.Api.Ads.AdWords.v201406.Ad.finalMobileUrls, Google.Api.Ads.AdWords.v201406.Ad.finalUrls, Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.AdWords.v201406.TextAd.headline, Google.Api.Ads.AdWords.v201406.Ad.id, Google.Api.Ads.AdWords.v201406.CustomParameter.key, Google.Api.Ads.AdWords.v201406.AdGroupAdService.mutate(), Google.Api.Ads.AdWords.v201406.AdGroupAdOperation.operand, Google.Api.Ads.AdWords.v201406.CustomParameters.parameters, Google.Api.Ads.AdWords.v201406.AdGroupAd.status, Google.Api.Ads.AdWords.v201406.Ad.trackingUrlTemplate, Google.Api.Ads.AdWords.v201406.Ad.urlCustomParameters, Google.Api.Ads.AdWords.v201406.CustomParameter.value, and Google.Api.Ads.AdWords.v201406.AdGroupAdReturnValue.value.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAdWithUpgradedUrls.Main().
Property Documentation
override string Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAdWithUpgradedUrls.Description get
Returns a description about the code example.
Referenced by Google.Api.Ads.AdWords.Examples.CSharp.v201406.AddTextAdWithUpgradedUrls.Main().
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/AdWords/CSharp/v201406/AdvancedOperations/AddTextAdWithUpgradedUrls.cs