Ads API .NET library: Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateVideoLineItem Class Reference
Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateVideoLineItem Class Reference
This code example creates a new line item to serve to video content. To determine which line items exist, run GetAllLineItems.cs. To determine which orders exist, run GetAllOrders.cs. To create a video ad unit, run CreateVideoAdUnit.cs. To create criteria for categories, run CreateCustomTargetingKeysAndValues.cs.
Public Member Functions
override void Run (DfpUser user)
Run the code example.
Static Public Member Functions
static void Main (string[] args)
Main method, to run this code example as a standalone application.
Properties
override string Description [get]
Returns a description about the code example.
Properties inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
abstract string Description [get]
Returns a description about the code example.
Additional Inherited Members
Protected Member Functions inherited from Google.Api.Ads.Dfp.Examples.CSharp.SampleBase
string _T (string prompt)
string GetTimeStamp ()
Gets the current time stamp.
Detailed Description
This code example creates a new line item to serve to video content. To determine which line items exist, run GetAllLineItems.cs. To determine which orders exist, run GetAllOrders.cs. To create a video ad unit, run CreateVideoAdUnit.cs. To create criteria for categories, run CreateCustomTargetingKeysAndValues.cs.
Tags: LineItemService.createLineItems
Member Function Documentation
static void Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateVideoLineItem.Main (string[] args) inline static
Main method, to run this code example as a standalone application.
Parameters
args The command line arguments.
References Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Description, and Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.Run().
override void Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateVideoLineItem.Run (DfpUser user) inline virtual
Run the code example.
Parameters
user The DFP user object running the code example.
Implements Google.Api.Ads.Dfp.Examples.CSharp.SampleBase.
References Google.Api.Ads.Dfp.v201408.AdUnitTargeting.adUnitId, Google.Api.Ads.Dfp.v201408.LineItemSummary.allowOverbook, Google.Api.Ads.Dfp.v201408.CustomCriteriaSet.children, Google.Api.Ads.Dfp.v201408.LineItemSummary.companionDeliveryOption, Google.Api.Ads.Dfp.v201408.CreativePlaceholder.companions, Google.Api.Ads.Dfp.v201408.LineItemSummary.costPerUnit, Google.Api.Ads.Dfp.v201408.LineItemSummary.costType, Google.Api.Ads.Dfp.v201408.LineItemService.createLineItems(), Google.Api.Ads.Dfp.v201408.LineItemSummary.creativePlaceholders, Google.Api.Ads.Dfp.v201408.LineItemSummary.creativeRotationType, Google.Api.Ads.Dfp.v201408.Money.currencyCode, Google.Api.Ads.Dfp.v201408.Targeting.customTargeting, Google.Api.Ads.Dfp.v201408.LineItemSummary.endDateTime, Google.Api.Ads.Dfp.v201408.LineItemSummary.environmentType, Google.Api.Ads.Dfp.Util.v201408.DateTimeUtilities.FromString(), Google.Api.Ads.Common.Lib.AdsUser.GetService(), Google.Api.Ads.Dfp.v201408.Goal.goalType, Google.Api.Ads.Dfp.v201408.Size.height, Google.Api.Ads.Dfp.v201408.LineItemSummary.id, Google.Api.Ads.Dfp.v201408.AdUnitTargeting.includeDescendants, Google.Api.Ads.Dfp.v201408.Targeting.inventoryTargeting, Google.Api.Ads.Dfp.v201408.Size.isAspectRatio, Google.Api.Ads.Dfp.v201408.CustomCriteria.keyId, Google.Api.Ads.Dfp.Lib.DfpService.v201408.LineItemService, Google.Api.Ads.Dfp.v201408.LineItemSummary.lineItemType, Google.Api.Ads.Dfp.v201408.Money.microAmount, Google.Api.Ads.Dfp.v201408.LineItemSummary.name, Google.Api.Ads.Dfp.v201408.LineItemSummary.orderId, Google.Api.Ads.Dfp.v201408.VideoPosition.positionType, Google.Api.Ads.Dfp.v201408.LineItemSummary.primaryGoal, Google.Api.Ads.Dfp.v201408.CreativePlaceholder.size, Google.Api.Ads.Dfp.v201408.LineItemSummary.startDateTimeType, Google.Api.Ads.Dfp.v201408.InventoryTargeting.targetedAdUnits, Google.Api.Ads.Dfp.v201408.VideoPositionTargeting.targetedPositions, Google.Api.Ads.Dfp.v201408.LineItem.targeting, Google.Api.Ads.Dfp.v201408.Goal.units, Google.Api.Ads.Dfp.v201408.Goal.unitType, Google.Api.Ads.Dfp.v201408.CustomCriteria.valueIds, Google.Api.Ads.Dfp.v201408.VideoPositionTarget.videoPosition, Google.Api.Ads.Dfp.v201408.Targeting.videoPositionTargeting, and Google.Api.Ads.Dfp.v201408.Size.width.
Property Documentation
override string Google.Api.Ads.Dfp.Examples.CSharp.v201408.CreateVideoLineItem.Description get
Returns a description about the code example.
The documentation for this class was generated from the following file:
C:/Users/jimper/Desktop/adsapi/dist/github/examples/Dfp/CSharp/v201408/LineItemService/CreateVideoLineItem.cs