//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
//
namespace com.google.api.adwords.v200902.AdGroupAdService {
  using System;
  using System.Diagnostics;
  using System.Web.Services;
  using System.ComponentModel;
  using System.Xml.Serialization;
  using System.Web.Services.Protocols;

  using com.google.api.adwords.v200902;

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Web.Services.WebServiceBindingAttribute(Name = "AdGroupAdServiceSoapBinding", Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListReturnValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Operation))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Media))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Stats))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Page))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatsSelector))]
  public partial class AdGroupAdService : System.Web.Services.Protocols.SoapHttpClientProtocol {

    private RequestHeader requestHeaderField;

    private ResponseHeader responseHeaderField;

    private System.Threading.SendOrPostCallback getOperationCompleted;

    private System.Threading.SendOrPostCallback mutateOperationCompleted;

    /// <remarks/>
    public AdGroupAdService() {
      this.Url = "https://adwords-sandbox.google.com/api/adwords/cm/v200902/AdGroupAdService";
    }

    public RequestHeader RequestHeader {
      get {
        return this.requestHeaderField;
      }
      set {
        this.requestHeaderField = value;
      }
    }

    public ResponseHeader ResponseHeader {
      get {
        return this.responseHeaderField;
      }
      set {
        this.responseHeaderField = value;
      }
    }

    /// <remarks/>
    public event getCompletedEventHandler getCompleted;

    /// <remarks/>
    public event mutateCompletedEventHandler mutateCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.Out)]
    [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://adwords.google.com/api/adwords/cm/v200902", ResponseNamespace = "https://adwords.google.com/api/adwords/cm/v200902", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("rval")]
    public AdGroupAdPage get(AdGroupAdSelector selector) {
      object[] results = this.Invoke("get", new object[] {
                        selector});
      return ((AdGroupAdPage) (results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult Beginget(AdGroupAdSelector selector, System.AsyncCallback callback, object asyncState) {
      return this.BeginInvoke("get", new object[] {
                        selector}, callback, asyncState);
    }

    /// <remarks/>
    public AdGroupAdPage Endget(System.IAsyncResult asyncResult) {
      object[] results = this.EndInvoke(asyncResult);
      return ((AdGroupAdPage) (results[0]));
    }

    /// <remarks/>
    public void getAsync(AdGroupAdSelector selector) {
      this.getAsync(selector, null);
    }

    /// <remarks/>
    public void getAsync(AdGroupAdSelector selector, object userState) {
      if ((this.getOperationCompleted == null)) {
        this.getOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOperationCompleted);
      }
      this.InvokeAsync("get", new object[] {
                        selector}, this.getOperationCompleted, userState);
    }

    private void OngetOperationCompleted(object arg) {
      if ((this.getCompleted != null)) {
        System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs) (arg));
        this.getCompleted(this, new getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
      }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.Out)]
    [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://adwords.google.com/api/adwords/cm/v200902", ResponseNamespace = "https://adwords.google.com/api/adwords/cm/v200902", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("rval")]
    public AdGroupAdReturnValue mutate([System.Xml.Serialization.XmlElementAttribute("operations")] AdGroupAdOperation[] operations) {
      object[] results = this.Invoke("mutate", new object[] {
                        operations});
      return ((AdGroupAdReturnValue) (results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult Beginmutate(AdGroupAdOperation[] operations, System.AsyncCallback callback, object asyncState) {
      return this.BeginInvoke("mutate", new object[] {
                        operations}, callback, asyncState);
    }

    /// <remarks/>
    public AdGroupAdReturnValue Endmutate(System.IAsyncResult asyncResult) {
      object[] results = this.EndInvoke(asyncResult);
      return ((AdGroupAdReturnValue) (results[0]));
    }

    /// <remarks/>
    public void mutateAsync(AdGroupAdOperation[] operations) {
      this.mutateAsync(operations, null);
    }

    /// <remarks/>
    public void mutateAsync(AdGroupAdOperation[] operations, object userState) {
      if ((this.mutateOperationCompleted == null)) {
        this.mutateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmutateOperationCompleted);
      }
      this.InvokeAsync("mutate", new object[] {
                        operations}, this.mutateOperationCompleted, userState);
    }

    private void OnmutateOperationCompleted(object arg) {
      if ((this.mutateCompleted != null)) {
        System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs) (arg));
        this.mutateCompleted(this, new mutateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
      }
    }

    /// <remarks/>
    public new void CancelAsync(object userState) {
      base.CancelAsync(userState);
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdGroupAdReturnValue))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class ListReturnValue {

    private string listReturnValueTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ListReturnValue.Type")]
    public string ListReturnValueType {
      get {
        return this.listReturnValueTypeField;
      }
      set {
        this.listReturnValueTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class AdGroupAdReturnValue : ListReturnValue {

    private AdGroupAd[] valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("value")]
    public AdGroupAd[] value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class AdGroupAd {

    private AdGroupId adGroupIdField;

    private Ad adField;

    private AdGroupAdStatus statusField;

    private bool statusFieldSpecified;

    private AdStats statsField;

    /// <remarks/>
    public AdGroupId adGroupId {
      get {
        return this.adGroupIdField;
      }
      set {
        this.adGroupIdField = value;
      }
    }

    /// <remarks/>
    public Ad ad {
      get {
        return this.adField;
      }
      set {
        this.adField = value;
      }
    }

    /// <remarks/>
    public AdGroupAdStatus status {
      get {
        return this.statusField;
      }
      set {
        this.statusField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
      get {
        return this.statusFieldSpecified;
      }
      set {
        this.statusFieldSpecified = value;
      }
    }

    /// <remarks/>
    public AdStats stats {
      get {
        return this.statsField;
      }
      set {
        this.statsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class AdGroupId {

    private long idField;

    private bool idFieldSpecified;

    private string adGroupIdTypeField;

    /// <remarks/>
    public long id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
      get {
        return this.idFieldSpecified;
      }
      set {
        this.idFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdGroupId.Type")]
    public string AdGroupIdType {
      get {
        return this.adGroupIdTypeField;
      }
      set {
        this.adGroupIdTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImageAd))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextAd))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class Ad {

    private AdId idField;

    private string urlField;

    private string displayUrlField;

    private AdApprovalStatus approvalStatusField;

    private bool approvalStatusFieldSpecified;

    private string[] disapprovalReasonsField;

    private AdStats statsField;

    private string adTypeField;

    /// <remarks/>
    public AdId id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    public string url {
      get {
        return this.urlField;
      }
      set {
        this.urlField = value;
      }
    }

    /// <remarks/>
    public string displayUrl {
      get {
        return this.displayUrlField;
      }
      set {
        this.displayUrlField = value;
      }
    }

    /// <remarks/>
    public AdApprovalStatus approvalStatus {
      get {
        return this.approvalStatusField;
      }
      set {
        this.approvalStatusField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool approvalStatusSpecified {
      get {
        return this.approvalStatusFieldSpecified;
      }
      set {
        this.approvalStatusFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("disapprovalReasons")]
    public string[] disapprovalReasons {
      get {
        return this.disapprovalReasonsField;
      }
      set {
        this.disapprovalReasonsField = value;
      }
    }

    /// <remarks/>
    public AdStats stats {
      get {
        return this.statsField;
      }
      set {
        this.statsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ad.Type")]
    public string AdType {
      get {
        return this.adTypeField;
      }
      set {
        this.adTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class AdId {

    private long idField;

    private bool idFieldSpecified;

    /// <remarks/>
    public long id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
      get {
        return this.idFieldSpecified;
      }
      set {
        this.idFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Ad.ApprovalStatus", Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public enum AdApprovalStatus {

    /// <remarks/>
    APPROVED,

    /// <remarks/>
    FAMILY_SAFE,

    /// <remarks/>
    NON_FAMILY_SAFE,

    /// <remarks/>
    PORN,

    /// <remarks/>
    UNCHECKED,

    /// <remarks/>
    AUTO_GENERATED,

    /// <remarks/>
    NOT_READY_FOR_APPROVAL,

    /// <remarks/>
    SUSPICIOUS,

    /// <remarks/>
    FORBIDDEN,

    /// <remarks/>
    DISABLED,

    /// <remarks/>
    DISAPPROVED,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class AdStats : Stats {

    private double percentServedField;

    private bool percentServedFieldSpecified;

    /// <remarks/>
    public double percentServed {
      get {
        return this.percentServedField;
      }
      set {
        this.percentServedField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool percentServedSpecified {
      get {
        return this.percentServedFieldSpecified;
      }
      set {
        this.percentServedFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdStats))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class Stats {

    private Date startDateField;

    private Date endDateField;

    private StatsNetwork networkField;

    private bool networkFieldSpecified;

    private long clicksField;

    private bool clicksFieldSpecified;

    private long impressionsField;

    private bool impressionsFieldSpecified;

    private Money costField;

    private double averagePositionField;

    private bool averagePositionFieldSpecified;

    private Money averageCpcField;

    private Money averageCpmField;

    private double ctrField;

    private bool ctrFieldSpecified;

    private long conversionsField;

    private bool conversionsFieldSpecified;

    private double conversionRateField;

    private bool conversionRateFieldSpecified;

    private Money costPerConversionField;

    private string statsTypeField;

    /// <remarks/>
    public Date startDate {
      get {
        return this.startDateField;
      }
      set {
        this.startDateField = value;
      }
    }

    /// <remarks/>
    public Date endDate {
      get {
        return this.endDateField;
      }
      set {
        this.endDateField = value;
      }
    }

    /// <remarks/>
    public StatsNetwork network {
      get {
        return this.networkField;
      }
      set {
        this.networkField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool networkSpecified {
      get {
        return this.networkFieldSpecified;
      }
      set {
        this.networkFieldSpecified = value;
      }
    }

    /// <remarks/>
    public long clicks {
      get {
        return this.clicksField;
      }
      set {
        this.clicksField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool clicksSpecified {
      get {
        return this.clicksFieldSpecified;
      }
      set {
        this.clicksFieldSpecified = value;
      }
    }

    /// <remarks/>
    public long impressions {
      get {
        return this.impressionsField;
      }
      set {
        this.impressionsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool impressionsSpecified {
      get {
        return this.impressionsFieldSpecified;
      }
      set {
        this.impressionsFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Money cost {
      get {
        return this.costField;
      }
      set {
        this.costField = value;
      }
    }

    /// <remarks/>
    public double averagePosition {
      get {
        return this.averagePositionField;
      }
      set {
        this.averagePositionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averagePositionSpecified {
      get {
        return this.averagePositionFieldSpecified;
      }
      set {
        this.averagePositionFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Money averageCpc {
      get {
        return this.averageCpcField;
      }
      set {
        this.averageCpcField = value;
      }
    }

    /// <remarks/>
    public Money averageCpm {
      get {
        return this.averageCpmField;
      }
      set {
        this.averageCpmField = value;
      }
    }

    /// <remarks/>
    public double ctr {
      get {
        return this.ctrField;
      }
      set {
        this.ctrField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ctrSpecified {
      get {
        return this.ctrFieldSpecified;
      }
      set {
        this.ctrFieldSpecified = value;
      }
    }

    /// <remarks/>
    public long conversions {
      get {
        return this.conversionsField;
      }
      set {
        this.conversionsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conversionsSpecified {
      get {
        return this.conversionsFieldSpecified;
      }
      set {
        this.conversionsFieldSpecified = value;
      }
    }

    /// <remarks/>
    public double conversionRate {
      get {
        return this.conversionRateField;
      }
      set {
        this.conversionRateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conversionRateSpecified {
      get {
        return this.conversionRateFieldSpecified;
      }
      set {
        this.conversionRateFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Money costPerConversion {
      get {
        return this.costPerConversionField;
      }
      set {
        this.costPerConversionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Stats.Type")]
    public string StatsType {
      get {
        return this.statsTypeField;
      }
      set {
        this.statsTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class Date {

    private int yearField;

    private bool yearFieldSpecified;

    private int monthField;

    private bool monthFieldSpecified;

    private int dayField;

    private bool dayFieldSpecified;

    /// <remarks/>
    public int year {
      get {
        return this.yearField;
      }
      set {
        this.yearField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool yearSpecified {
      get {
        return this.yearFieldSpecified;
      }
      set {
        this.yearFieldSpecified = value;
      }
    }

    /// <remarks/>
    public int month {
      get {
        return this.monthField;
      }
      set {
        this.monthField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool monthSpecified {
      get {
        return this.monthFieldSpecified;
      }
      set {
        this.monthFieldSpecified = value;
      }
    }

    /// <remarks/>
    public int day {
      get {
        return this.dayField;
      }
      set {
        this.dayField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool daySpecified {
      get {
        return this.dayFieldSpecified;
      }
      set {
        this.dayFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Stats.Network", Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public enum StatsNetwork {

    /// <remarks/>
    SEARCH,

    /// <remarks/>
    GOOGLE_SEARCH,

    /// <remarks/>
    SEARCH_NETWORK,

    /// <remarks/>
    CONTENT,

    /// <remarks/>
    CONTENT_KEYWORD_BID,

    /// <remarks/>
    CONTENT_PLACEMENT_BID,

    /// <remarks/>
    ALL,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class Money {

    private string currencyCodeField;

    private long microAmountField;

    private bool microAmountFieldSpecified;

    /// <remarks/>
    public string currencyCode {
      get {
        return this.currencyCodeField;
      }
      set {
        this.currencyCodeField = value;
      }
    }

    /// <remarks/>
    public long microAmount {
      get {
        return this.microAmountField;
      }
      set {
        this.microAmountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool microAmountSpecified {
      get {
        return this.microAmountFieldSpecified;
      }
      set {
        this.microAmountFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class ImageAd : Ad {

    private Image imageField;

    private string nameField;

    /// <remarks/>
    public Image image {
      get {
        return this.imageField;
      }
      set {
        this.imageField = value;
      }
    }

    /// <remarks/>
    public string name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class Image : Media {

    private byte[] dataField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] data {
      get {
        return this.dataField;
      }
      set {
        this.dataField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Image))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class Media {

    private long mediaIdField;

    private bool mediaIdFieldSpecified;

    private long referenceIdField;

    private bool referenceIdFieldSpecified;

    private Media_Size_DimensionsMapEntry[] dimensionsField;

    private Media_Size_StringMapEntry[] urlsField;

    private MediaMimeType mimeTypeField;

    private bool mimeTypeFieldSpecified;

    private string sourceUrlField;

    private string mediaTypeField;

    /// <remarks/>
    public long mediaId {
      get {
        return this.mediaIdField;
      }
      set {
        this.mediaIdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool mediaIdSpecified {
      get {
        return this.mediaIdFieldSpecified;
      }
      set {
        this.mediaIdFieldSpecified = value;
      }
    }

    /// <remarks/>
    public long referenceId {
      get {
        return this.referenceIdField;
      }
      set {
        this.referenceIdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool referenceIdSpecified {
      get {
        return this.referenceIdFieldSpecified;
      }
      set {
        this.referenceIdFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dimensions")]
    public Media_Size_DimensionsMapEntry[] dimensions {
      get {
        return this.dimensionsField;
      }
      set {
        this.dimensionsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("urls")]
    public Media_Size_StringMapEntry[] urls {
      get {
        return this.urlsField;
      }
      set {
        this.urlsField = value;
      }
    }

    /// <remarks/>
    public MediaMimeType mimeType {
      get {
        return this.mimeTypeField;
      }
      set {
        this.mimeTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool mimeTypeSpecified {
      get {
        return this.mimeTypeFieldSpecified;
      }
      set {
        this.mimeTypeFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string sourceUrl {
      get {
        return this.sourceUrlField;
      }
      set {
        this.sourceUrlField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Media.Type")]
    public string MediaType {
      get {
        return this.mediaTypeField;
      }
      set {
        this.mediaTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class Media_Size_DimensionsMapEntry {

    private MediaSize keyField;

    private bool keyFieldSpecified;

    private Dimensions valueField;

    /// <remarks/>
    public MediaSize key {
      get {
        return this.keyField;
      }
      set {
        this.keyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keySpecified {
      get {
        return this.keyFieldSpecified;
      }
      set {
        this.keyFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Dimensions value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Media.Size", Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public enum MediaSize {

    /// <remarks/>
    FULL,

    /// <remarks/>
    SHRUNKEN,

    /// <remarks/>
    PREVIEW,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class Dimensions {

    private int widthField;

    private bool widthFieldSpecified;

    private int heightField;

    private bool heightFieldSpecified;

    /// <remarks/>
    public int width {
      get {
        return this.widthField;
      }
      set {
        this.widthField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool widthSpecified {
      get {
        return this.widthFieldSpecified;
      }
      set {
        this.widthFieldSpecified = value;
      }
    }

    /// <remarks/>
    public int height {
      get {
        return this.heightField;
      }
      set {
        this.heightField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool heightSpecified {
      get {
        return this.heightFieldSpecified;
      }
      set {
        this.heightFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class Media_Size_StringMapEntry {

    private MediaSize keyField;

    private bool keyFieldSpecified;

    private string valueField;

    /// <remarks/>
    public MediaSize key {
      get {
        return this.keyField;
      }
      set {
        this.keyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keySpecified {
      get {
        return this.keyFieldSpecified;
      }
      set {
        this.keyFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Media.MimeType", Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public enum MediaMimeType {

    /// <remarks/>
    IMAGE_JPEG,

    /// <remarks/>
    IMAGE_GIF,

    /// <remarks/>
    IMAGE_PNG,

    /// <remarks/>
    FLASH,

    /// <remarks/>
    TEXT_HTML,

    /// <remarks/>
    PDF,

    /// <remarks/>
    MSWORD,

    /// <remarks/>
    MSEXCEL,

    /// <remarks/>
    RTF,

    /// <remarks/>
    AUDIO_WAV,

    /// <remarks/>
    AUDIO_MP3,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class TextAd : Ad {

    private string headlineField;

    private string description1Field;

    private string description2Field;

    /// <remarks/>
    public string headline {
      get {
        return this.headlineField;
      }
      set {
        this.headlineField = value;
      }
    }

    /// <remarks/>
    public string description1 {
      get {
        return this.description1Field;
      }
      set {
        this.description1Field = value;
      }
    }

    /// <remarks/>
    public string description2 {
      get {
        return this.description2Field;
      }
      set {
        this.description2Field = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "AdGroupAd.Status", Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public enum AdGroupAdStatus {

    /// <remarks/>
    ENABLED,

    /// <remarks/>
    PAUSED,

    /// <remarks/>
    DISABLED,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class PolicyViolationKey {

    private string policyNameField;

    private string violatingTextField;

    /// <remarks/>
    public string policyName {
      get {
        return this.policyNameField;
      }
      set {
        this.policyNameField = value;
      }
    }

    /// <remarks/>
    public string violatingText {
      get {
        return this.violatingTextField;
      }
      set {
        this.violatingTextField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class ExemptionRequest {

    private PolicyViolationKey keyField;

    /// <remarks/>
    public PolicyViolationKey key {
      get {
        return this.keyField;
      }
      set {
        this.keyField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdGroupAdOperation))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public abstract partial class Operation {

    private Operator operatorField;

    private bool operatorFieldSpecified;

    private string operationTypeField;

    /// <remarks/>
    public Operator @operator {
      get {
        return this.operatorField;
      }
      set {
        this.operatorField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool operatorSpecified {
      get {
        return this.operatorFieldSpecified;
      }
      set {
        this.operatorFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Operation.Type")]
    public string OperationType {
      get {
        return this.operationTypeField;
      }
      set {
        this.operationTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public enum Operator {

    /// <remarks/>
    ADD,

    /// <remarks/>
    REMOVE,

    /// <remarks/>
    SET,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class AdGroupAdOperation : Operation {

    private AdGroupAd operandField;

    private ExemptionRequest[] exemptionRequestsField;

    /// <remarks/>
    public AdGroupAd operand {
      get {
        return this.operandField;
      }
      set {
        this.operandField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("exemptionRequests")]
    public ExemptionRequest[] exemptionRequests {
      get {
        return this.exemptionRequestsField;
      }
      set {
        this.exemptionRequestsField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdGroupAdPage))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public abstract partial class Page {

    private string pageTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Page.Type")]
    public string PageType {
      get {
        return this.pageTypeField;
      }
      set {
        this.pageTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class AdGroupAdPage : Page {

    private AdStats disabledSummaryStatsField;

    private AdGroupAd[] entriesField;

    private AdStats[] summaryStatsField;

    private AdStats includedSummaryStatsField;

    /// <remarks/>
    public AdStats disabledSummaryStats {
      get {
        return this.disabledSummaryStatsField;
      }
      set {
        this.disabledSummaryStatsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("entries")]
    public AdGroupAd[] entries {
      get {
        return this.entriesField;
      }
      set {
        this.entriesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("summaryStats")]
    public AdStats[] summaryStats {
      get {
        return this.summaryStatsField;
      }
      set {
        this.summaryStatsField = value;
      }
    }

    /// <remarks/>
    public AdStats includedSummaryStats {
      get {
        return this.includedSummaryStatsField;
      }
      set {
        this.includedSummaryStatsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class DateRange {

    private Date minField;

    private Date maxField;

    /// <remarks/>
    public Date min {
      get {
        return this.minField;
      }
      set {
        this.minField = value;
      }
    }

    /// <remarks/>
    public Date max {
      get {
        return this.maxField;
      }
      set {
        this.maxField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdStatsSelector))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class StatsSelector {

    private DateRange dateRangeField;

    private string statsSelectorTypeField;

    /// <remarks/>
    public DateRange dateRange {
      get {
        return this.dateRangeField;
      }
      set {
        this.dateRangeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StatsSelector.Type")]
    public string StatsSelectorType {
      get {
        return this.statsSelectorTypeField;
      }
      set {
        this.statsSelectorTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class AdStatsSelector : StatsSelector {
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class CampaignId {

    private long idField;

    private bool idFieldSpecified;

    private string campaignIdTypeField;

    /// <remarks/>
    public long id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
      get {
        return this.idFieldSpecified;
      }
      set {
        this.idFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CampaignId.Type")]
    public string CampaignIdType {
      get {
        return this.campaignIdTypeField;
      }
      set {
        this.campaignIdTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class AdGroupAdIdFilter {

    private CampaignId campaignIdField;

    private AdGroupId adGroupIdField;

    /// <remarks/>
    public CampaignId campaignId {
      get {
        return this.campaignIdField;
      }
      set {
        this.campaignIdField = value;
      }
    }

    /// <remarks/>
    public AdGroupId adGroupId {
      get {
        return this.adGroupIdField;
      }
      set {
        this.adGroupIdField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200902")]
  public partial class AdGroupAdSelector {

    private AdGroupAdIdFilter[] adGroupAdIdFiltersField;

    private AdStatsSelector statsSelectorField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adGroupAdIdFilters")]
    public AdGroupAdIdFilter[] adGroupAdIdFilters {
      get {
        return this.adGroupAdIdFiltersField;
      }
      set {
        this.adGroupAdIdFiltersField = value;
      }
    }

    /// <remarks/>
    public AdStatsSelector statsSelector {
      get {
        return this.statsSelectorField;
      }
      set {
        this.statsSelectorField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  public delegate void getCompletedEventHandler(object sender, getCompletedEventArgs e);

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  public partial class getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

    private object[] results;

    internal getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
      :
            base(exception, cancelled, userState) {
      this.results = results;
    }

    /// <remarks/>
    public AdGroupAdPage Result {
      get {
        this.RaiseExceptionIfNecessary();
        return ((AdGroupAdPage) (this.results[0]));
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  public delegate void mutateCompletedEventHandler(object sender, mutateCompletedEventArgs e);

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  public partial class mutateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

    private object[] results;

    internal mutateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
      :
            base(exception, cancelled, userState) {
      this.results = results;
    }

    /// <remarks/>
    public AdGroupAdReturnValue Result {
      get {
        this.RaiseExceptionIfNecessary();
        return ((AdGroupAdReturnValue) (this.results[0]));
      }
    }
  }
}
