// Copyright 2015, Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;
using System.Reflection;

namespace Google.Api.Ads.AdWords.Util.Selectors
{
    /// <summary>
    /// Base class for all the fields classes in autogenerated code.
    /// </summary>
    public class BaseFields
    {
        /// <summary>
        /// Gets all columns.
        /// </summary>
        /// <param name="type">The type.</param>
        /// <returns>The list of all columns</returns>
        protected static Field[] GetAllFields(Type type)
        {
            List<Field> retval = new List<Field>();
            FieldInfo[] fields = type.GetFields(BindingFlags.Static | BindingFlags.Public |
                BindingFlags.FlattenHierarchy);
            foreach (FieldInfo field in fields)
            {
                if (field.FieldType == typeof(Field))
                {
                    Field f = (Field) field.GetValue(null);
                    retval.Add(f);
                }
            }

            return retval.ToArray();
        }
    }
}
