//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
//
namespace com.google.api.adwords.v200906.AdGroupCriterionService {
  using System.Diagnostics;
  using System.Web.Services;
  using System.ComponentModel;
  using System.Web.Services.Protocols;
  using System;
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Web.Services.WebServiceBindingAttribute(Name = "AdGroupCriterionServiceSoapBinding", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListReturnValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Operation))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComparableValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Page))]
  public partial class AdGroupCriterionService : System.Web.Services.Protocols.SoapHttpClientProtocol {

    private RequestHeader requestHeaderField;

    private ResponseHeader responseHeaderField;

    private System.Threading.SendOrPostCallback getOperationCompleted;

    private System.Threading.SendOrPostCallback mutateOperationCompleted;

    /// <remarks/>
    public AdGroupCriterionService() {
      this.Url = "http://localhost";
    }

    public RequestHeader RequestHeader {
      get {
        return this.requestHeaderField;
      }
      set {
        this.requestHeaderField = value;
      }
    }

    public ResponseHeader ResponseHeader {
      get {
        return this.responseHeaderField;
      }
      set {
        this.responseHeaderField = value;
      }
    }

    /// <remarks/>
    public event getCompletedEventHandler getCompleted;

    /// <remarks/>
    public event mutateCompletedEventHandler mutateCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.Out)]
    [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://adwords.google.com/api/adwords/cm/v200906", ResponseNamespace = "https://adwords.google.com/api/adwords/cm/v200906", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("rval")]
    public AdGroupCriterionPage get(AdGroupCriterionSelector selector) {
      object[] results = this.Invoke("get", new object[] {
                        selector});
      return ((AdGroupCriterionPage) (results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult Beginget(AdGroupCriterionSelector selector, System.AsyncCallback callback, object asyncState) {
      return this.BeginInvoke("get", new object[] {
                        selector}, callback, asyncState);
    }

    /// <remarks/>
    public AdGroupCriterionPage Endget(System.IAsyncResult asyncResult) {
      object[] results = this.EndInvoke(asyncResult);
      return ((AdGroupCriterionPage) (results[0]));
    }

    /// <remarks/>
    public void getAsync(AdGroupCriterionSelector selector) {
      this.getAsync(selector, null);
    }

    /// <remarks/>
    public void getAsync(AdGroupCriterionSelector selector, object userState) {
      if ((this.getOperationCompleted == null)) {
        this.getOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOperationCompleted);
      }
      this.InvokeAsync("get", new object[] {
                        selector}, this.getOperationCompleted, userState);
    }

    private void OngetOperationCompleted(object arg) {
      if ((this.getCompleted != null)) {
        System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs) (arg));
        this.getCompleted(this, new getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
      }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.Out)]
    [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://adwords.google.com/api/adwords/cm/v200906", ResponseNamespace = "https://adwords.google.com/api/adwords/cm/v200906", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("rval")]
    public AdGroupCriterionReturnValue mutate([System.Xml.Serialization.XmlElementAttribute("operations")] AdGroupCriterionOperation[] operations) {
      object[] results = this.Invoke("mutate", new object[] {
                        operations});
      return ((AdGroupCriterionReturnValue) (results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult Beginmutate(AdGroupCriterionOperation[] operations, System.AsyncCallback callback, object asyncState) {
      return this.BeginInvoke("mutate", new object[] {
                        operations}, callback, asyncState);
    }

    /// <remarks/>
    public AdGroupCriterionReturnValue Endmutate(System.IAsyncResult asyncResult) {
      object[] results = this.EndInvoke(asyncResult);
      return ((AdGroupCriterionReturnValue) (results[0]));
    }

    /// <remarks/>
    public void mutateAsync(AdGroupCriterionOperation[] operations) {
      this.mutateAsync(operations, null);
    }

    /// <remarks/>
    public void mutateAsync(AdGroupCriterionOperation[] operations, object userState) {
      if ((this.mutateOperationCompleted == null)) {
        this.mutateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmutateOperationCompleted);
      }
      this.InvokeAsync("mutate", new object[] {
                        operations}, this.mutateOperationCompleted, userState);
    }

    private void OnmutateOperationCompleted(object arg) {
      if ((this.mutateCompleted != null)) {
        System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs) (arg));
        this.mutateCompleted(this, new mutateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
      }
    }

    /// <remarks/>
    public new void CancelAsync(object userState) {
      base.CancelAsync(userState);
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdGroupCriterionReturnValue))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class ListReturnValue {

    private string listReturnValueTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ListReturnValue.Type")]
    public string ListReturnValueType {
      get {
        return this.listReturnValueTypeField;
      }
      set {
        this.listReturnValueTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdGroupCriterionReturnValue : ListReturnValue {

    private AdGroupCriterion[] valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("value")]
    public AdGroupCriterion[] value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(BiddableAdGroupCriterion))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(NegativeAdGroupCriterion))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdGroupCriterion {

    private long adGroupIdField;

    private bool adGroupIdFieldSpecified;

    private Criterion criterionField;

    private string adGroupCriterionTypeField;

    /// <remarks/>
    public long adGroupId {
      get {
        return this.adGroupIdField;
      }
      set {
        this.adGroupIdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool adGroupIdSpecified {
      get {
        return this.adGroupIdFieldSpecified;
      }
      set {
        this.adGroupIdFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Criterion criterion {
      get {
        return this.criterionField;
      }
      set {
        this.criterionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdGroupCriterion.Type")]
    public string AdGroupCriterionType {
      get {
        return this.adGroupCriterionTypeField;
      }
      set {
        this.adGroupCriterionTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Placement))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Keyword))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Criterion {

    private long idField;

    private bool idFieldSpecified;

    private string criterionTypeField;

    /// <remarks/>
    public long id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
      get {
        return this.idFieldSpecified;
      }
      set {
        this.idFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Criterion.Type")]
    public string CriterionType {
      get {
        return this.criterionTypeField;
      }
      set {
        this.criterionTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Placement : Criterion {

    private string urlField;

    /// <remarks/>
    public string url {
      get {
        return this.urlField;
      }
      set {
        this.urlField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Keyword : Criterion {

    private string textField;

    private KeywordMatchType matchTypeField;

    private bool matchTypeFieldSpecified;

    /// <remarks/>
    public string text {
      get {
        return this.textField;
      }
      set {
        this.textField = value;
      }
    }

    /// <remarks/>
    public KeywordMatchType matchType {
      get {
        return this.matchTypeField;
      }
      set {
        this.matchTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool matchTypeSpecified {
      get {
        return this.matchTypeFieldSpecified;
      }
      set {
        this.matchTypeFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum KeywordMatchType {

    /// <remarks/>
    EXACT,

    /// <remarks/>
    PHRASE,

    /// <remarks/>
    BROAD,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class BiddableAdGroupCriterion : AdGroupCriterion {

    private UserStatus userStatusField;

    private bool userStatusFieldSpecified;

    private SystemServingStatus systemServingStatusField;

    private bool systemServingStatusFieldSpecified;

    private ApprovalStatus approvalStatusField;

    private bool approvalStatusFieldSpecified;

    private string destinationUrlField;

    private AdGroupCriterionBids bidsField;

    private Bid firstPageCpcField;

    private QualityInfo qualityInfoField;

    /// <remarks/>
    public UserStatus userStatus {
      get {
        return this.userStatusField;
      }
      set {
        this.userStatusField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userStatusSpecified {
      get {
        return this.userStatusFieldSpecified;
      }
      set {
        this.userStatusFieldSpecified = value;
      }
    }

    /// <remarks/>
    public SystemServingStatus systemServingStatus {
      get {
        return this.systemServingStatusField;
      }
      set {
        this.systemServingStatusField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool systemServingStatusSpecified {
      get {
        return this.systemServingStatusFieldSpecified;
      }
      set {
        this.systemServingStatusFieldSpecified = value;
      }
    }

    /// <remarks/>
    public ApprovalStatus approvalStatus {
      get {
        return this.approvalStatusField;
      }
      set {
        this.approvalStatusField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool approvalStatusSpecified {
      get {
        return this.approvalStatusFieldSpecified;
      }
      set {
        this.approvalStatusFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string destinationUrl {
      get {
        return this.destinationUrlField;
      }
      set {
        this.destinationUrlField = value;
      }
    }

    /// <remarks/>
    public AdGroupCriterionBids bids {
      get {
        return this.bidsField;
      }
      set {
        this.bidsField = value;
      }
    }

    /// <remarks/>
    public Bid firstPageCpc {
      get {
        return this.firstPageCpcField;
      }
      set {
        this.firstPageCpcField = value;
      }
    }

    /// <remarks/>
    public QualityInfo qualityInfo {
      get {
        return this.qualityInfoField;
      }
      set {
        this.qualityInfoField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum UserStatus {

    /// <remarks/>
    ACTIVE,

    /// <remarks/>
    DELETED,

    /// <remarks/>
    PAUSED,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum SystemServingStatus {

    /// <remarks/>
    ELIGIBLE,

    /// <remarks/>
    RARELY_SERVED,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum ApprovalStatus {

    /// <remarks/>
    APPROVED,

    /// <remarks/>
    PENDING_REVIEW,

    /// <remarks/>
    UNDER_REVIEW,

    /// <remarks/>
    DISAPPROVED,
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManualCPCAdGroupCriterionBids))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManualCPMAdGroupCriterionBids))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(BudgetOptimizerAdGroupCriterionBids))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConversionOptimizerAdGroupCriterionBids))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class AdGroupCriterionBids {

    private string adGroupCriterionBidsTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdGroupCriterionBids.Type")]
    public string AdGroupCriterionBidsType {
      get {
        return this.adGroupCriterionBidsTypeField;
      }
      set {
        this.adGroupCriterionBidsTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class ManualCPCAdGroupCriterionBids : AdGroupCriterionBids {

    private Bid maxCpcField;

    private BidSource bidSourceField;

    private bool bidSourceFieldSpecified;

    private PositionPreferenceAdGroupCriterionBids positionPreferenceBidsField;

    /// <remarks/>
    public Bid maxCpc {
      get {
        return this.maxCpcField;
      }
      set {
        this.maxCpcField = value;
      }
    }

    /// <remarks/>
    public BidSource bidSource {
      get {
        return this.bidSourceField;
      }
      set {
        this.bidSourceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bidSourceSpecified {
      get {
        return this.bidSourceFieldSpecified;
      }
      set {
        this.bidSourceFieldSpecified = value;
      }
    }

    /// <remarks/>
    public PositionPreferenceAdGroupCriterionBids positionPreferenceBids {
      get {
        return this.positionPreferenceBidsField;
      }
      set {
        this.positionPreferenceBidsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Bid {

    private Money amountField;

    /// <remarks/>
    public Money amount {
      get {
        return this.amountField;
      }
      set {
        this.amountField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Money : ComparableValue {

    private long microAmountField;

    private bool microAmountFieldSpecified;

    /// <remarks/>
    public long microAmount {
      get {
        return this.microAmountField;
      }
      set {
        this.microAmountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool microAmountSpecified {
      get {
        return this.microAmountFieldSpecified;
      }
      set {
        this.microAmountFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(NumberValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(LongValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Money))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class ComparableValue {

    private string comparableValueTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ComparableValue.Type")]
    public string ComparableValueType {
      get {
        return this.comparableValueTypeField;
      }
      set {
        this.comparableValueTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(LongValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleValue))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class NumberValue : ComparableValue {
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class LongValue : NumberValue {

    private long numberField;

    private bool numberFieldSpecified;

    /// <remarks/>
    public long number {
      get {
        return this.numberField;
      }
      set {
        this.numberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numberSpecified {
      get {
        return this.numberFieldSpecified;
      }
      set {
        this.numberFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class DoubleValue : NumberValue {

    private double numberField;

    private bool numberFieldSpecified;

    /// <remarks/>
    public double number {
      get {
        return this.numberField;
      }
      set {
        this.numberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numberSpecified {
      get {
        return this.numberFieldSpecified;
      }
      set {
        this.numberFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum BidSource {

    /// <remarks/>
    ADGROUP,

    /// <remarks/>
    CRITERION,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class PositionPreferenceAdGroupCriterionBids {

    private Bid proxyMaxCpcField;

    private int preferredPositionField;

    private bool preferredPositionFieldSpecified;

    private int bottomPositionField;

    private bool bottomPositionFieldSpecified;

    /// <remarks/>
    public Bid proxyMaxCpc {
      get {
        return this.proxyMaxCpcField;
      }
      set {
        this.proxyMaxCpcField = value;
      }
    }

    /// <remarks/>
    public int preferredPosition {
      get {
        return this.preferredPositionField;
      }
      set {
        this.preferredPositionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool preferredPositionSpecified {
      get {
        return this.preferredPositionFieldSpecified;
      }
      set {
        this.preferredPositionFieldSpecified = value;
      }
    }

    /// <remarks/>
    public int bottomPosition {
      get {
        return this.bottomPositionField;
      }
      set {
        this.bottomPositionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bottomPositionSpecified {
      get {
        return this.bottomPositionFieldSpecified;
      }
      set {
        this.bottomPositionFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class ManualCPMAdGroupCriterionBids : AdGroupCriterionBids {

    private Bid maxCpmField;

    private BidSource bidSourceField;

    private bool bidSourceFieldSpecified;

    /// <remarks/>
    public Bid maxCpm {
      get {
        return this.maxCpmField;
      }
      set {
        this.maxCpmField = value;
      }
    }

    /// <remarks/>
    public BidSource bidSource {
      get {
        return this.bidSourceField;
      }
      set {
        this.bidSourceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bidSourceSpecified {
      get {
        return this.bidSourceFieldSpecified;
      }
      set {
        this.bidSourceFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class BudgetOptimizerAdGroupCriterionBids : AdGroupCriterionBids {

    private Bid proxyBidField;

    /// <remarks/>
    public Bid proxyBid {
      get {
        return this.proxyBidField;
      }
      set {
        this.proxyBidField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class ConversionOptimizerAdGroupCriterionBids : AdGroupCriterionBids {
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class QualityInfo {

    private bool isKeywordAdRelevanceAcceptableField;

    private bool isKeywordAdRelevanceAcceptableFieldSpecified;

    private bool isLandingPageQualityAcceptableField;

    private bool isLandingPageQualityAcceptableFieldSpecified;

    private bool isLandingPageLatencyAcceptableField;

    private bool isLandingPageLatencyAcceptableFieldSpecified;

    private int qualityScoreField;

    private bool qualityScoreFieldSpecified;

    /// <remarks/>
    public bool isKeywordAdRelevanceAcceptable {
      get {
        return this.isKeywordAdRelevanceAcceptableField;
      }
      set {
        this.isKeywordAdRelevanceAcceptableField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isKeywordAdRelevanceAcceptableSpecified {
      get {
        return this.isKeywordAdRelevanceAcceptableFieldSpecified;
      }
      set {
        this.isKeywordAdRelevanceAcceptableFieldSpecified = value;
      }
    }

    /// <remarks/>
    public bool isLandingPageQualityAcceptable {
      get {
        return this.isLandingPageQualityAcceptableField;
      }
      set {
        this.isLandingPageQualityAcceptableField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isLandingPageQualityAcceptableSpecified {
      get {
        return this.isLandingPageQualityAcceptableFieldSpecified;
      }
      set {
        this.isLandingPageQualityAcceptableFieldSpecified = value;
      }
    }

    /// <remarks/>
    public bool isLandingPageLatencyAcceptable {
      get {
        return this.isLandingPageLatencyAcceptableField;
      }
      set {
        this.isLandingPageLatencyAcceptableField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isLandingPageLatencyAcceptableSpecified {
      get {
        return this.isLandingPageLatencyAcceptableFieldSpecified;
      }
      set {
        this.isLandingPageLatencyAcceptableFieldSpecified = value;
      }
    }

    /// <remarks/>
    public int qualityScore {
      get {
        return this.qualityScoreField;
      }
      set {
        this.qualityScoreField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool qualityScoreSpecified {
      get {
        return this.qualityScoreFieldSpecified;
      }
      set {
        this.qualityScoreFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class NegativeAdGroupCriterion : AdGroupCriterion {
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class PolicyViolationKey {

    private string policyNameField;

    private string violatingTextField;

    /// <remarks/>
    public string policyName {
      get {
        return this.policyNameField;
      }
      set {
        this.policyNameField = value;
      }
    }

    /// <remarks/>
    public string violatingText {
      get {
        return this.violatingTextField;
      }
      set {
        this.violatingTextField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class ExemptionRequest {

    private PolicyViolationKey keyField;

    /// <remarks/>
    public PolicyViolationKey key {
      get {
        return this.keyField;
      }
      set {
        this.keyField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdGroupCriterionOperation))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class Operation {

    private Operator operatorField;

    private bool operatorFieldSpecified;

    private string operationTypeField;

    /// <remarks/>
    public Operator @operator {
      get {
        return this.operatorField;
      }
      set {
        this.operatorField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool operatorSpecified {
      get {
        return this.operatorFieldSpecified;
      }
      set {
        this.operatorFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Operation.Type")]
    public string OperationType {
      get {
        return this.operationTypeField;
      }
      set {
        this.operationTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum Operator {

    /// <remarks/>
    ADD,

    /// <remarks/>
    REMOVE,

    /// <remarks/>
    SET,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdGroupCriterionOperation : Operation {

    private AdGroupCriterion operandField;

    private ExemptionRequest[] exemptionRequestsField;

    /// <remarks/>
    public AdGroupCriterion operand {
      get {
        return this.operandField;
      }
      set {
        this.operandField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("exemptionRequests")]
    public ExemptionRequest[] exemptionRequests {
      get {
        return this.exemptionRequestsField;
      }
      set {
        this.exemptionRequestsField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdGroupCriterionPage))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class Page {

    private int totalNumEntriesField;

    private bool totalNumEntriesFieldSpecified;

    private string pageTypeField;

    /// <remarks/>
    public int totalNumEntries {
      get {
        return this.totalNumEntriesField;
      }
      set {
        this.totalNumEntriesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalNumEntriesSpecified {
      get {
        return this.totalNumEntriesFieldSpecified;
      }
      set {
        this.totalNumEntriesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Page.Type")]
    public string PageType {
      get {
        return this.pageTypeField;
      }
      set {
        this.pageTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdGroupCriterionPage : Page {

    private AdGroupCriterion[] entriesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("entries")]
    public AdGroupCriterion[] entries {
      get {
        return this.entriesField;
      }
      set {
        this.entriesField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Paging {

    private int startIndexField;

    private bool startIndexFieldSpecified;

    private int numberResultsField;

    private bool numberResultsFieldSpecified;

    /// <remarks/>
    public int startIndex {
      get {
        return this.startIndexField;
      }
      set {
        this.startIndexField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startIndexSpecified {
      get {
        return this.startIndexFieldSpecified;
      }
      set {
        this.startIndexFieldSpecified = value;
      }
    }

    /// <remarks/>
    public int numberResults {
      get {
        return this.numberResultsField;
      }
      set {
        this.numberResultsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numberResultsSpecified {
      get {
        return this.numberResultsFieldSpecified;
      }
      set {
        this.numberResultsFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class DateRange {

    private string minField;

    private string maxField;

    /// <remarks/>
    public string min {
      get {
        return this.minField;
      }
      set {
        this.minField = value;
      }
    }

    /// <remarks/>
    public string max {
      get {
        return this.maxField;
      }
      set {
        this.maxField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class StatsSelector {

    private DateRange dateRangeField;

    /// <remarks/>
    public DateRange dateRange {
      get {
        return this.dateRangeField;
      }
      set {
        this.dateRangeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdGroupCriterionIdFilter {

    private long campaignIdField;

    private bool campaignIdFieldSpecified;

    private long adGroupIdField;

    private bool adGroupIdFieldSpecified;

    private long criterionIdField;

    private bool criterionIdFieldSpecified;

    /// <remarks/>
    public long campaignId {
      get {
        return this.campaignIdField;
      }
      set {
        this.campaignIdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool campaignIdSpecified {
      get {
        return this.campaignIdFieldSpecified;
      }
      set {
        this.campaignIdFieldSpecified = value;
      }
    }

    /// <remarks/>
    public long adGroupId {
      get {
        return this.adGroupIdField;
      }
      set {
        this.adGroupIdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool adGroupIdSpecified {
      get {
        return this.adGroupIdFieldSpecified;
      }
      set {
        this.adGroupIdFieldSpecified = value;
      }
    }

    /// <remarks/>
    public long criterionId {
      get {
        return this.criterionIdField;
      }
      set {
        this.criterionIdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool criterionIdSpecified {
      get {
        return this.criterionIdFieldSpecified;
      }
      set {
        this.criterionIdFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdGroupCriterionSelector {

    private AdGroupCriterionIdFilter[] idFiltersField;

    private CriterionUse criterionUseField;

    private bool criterionUseFieldSpecified;

    private UserStatus[] userStatusesField;

    private StatsSelector statsSelectorField;

    private Paging pagingField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("idFilters")]
    public AdGroupCriterionIdFilter[] idFilters {
      get {
        return this.idFiltersField;
      }
      set {
        this.idFiltersField = value;
      }
    }

    /// <remarks/>
    public CriterionUse criterionUse {
      get {
        return this.criterionUseField;
      }
      set {
        this.criterionUseField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool criterionUseSpecified {
      get {
        return this.criterionUseFieldSpecified;
      }
      set {
        this.criterionUseFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("userStatuses")]
    public UserStatus[] userStatuses {
      get {
        return this.userStatusesField;
      }
      set {
        this.userStatusesField = value;
      }
    }

    /// <remarks/>
    public StatsSelector statsSelector {
      get {
        return this.statsSelectorField;
      }
      set {
        this.statsSelectorField = value;
      }
    }

    /// <remarks/>
    public Paging paging {
      get {
        return this.pagingField;
      }
      set {
        this.pagingField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum CriterionUse {

    /// <remarks/>
    BIDDABLE,

    /// <remarks/>
    NEGATIVE,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  public delegate void getCompletedEventHandler(object sender, getCompletedEventArgs e);

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  public partial class getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

    private object[] results;

    internal getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
      :
            base(exception, cancelled, userState) {
      this.results = results;
    }

    /// <remarks/>
    public AdGroupCriterionPage Result {
      get {
        this.RaiseExceptionIfNecessary();
        return ((AdGroupCriterionPage) (this.results[0]));
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  public delegate void mutateCompletedEventHandler(object sender, mutateCompletedEventArgs e);

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  public partial class mutateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

    private object[] results;

    internal mutateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
      :
            base(exception, cancelled, userState) {
      this.results = results;
    }

    /// <remarks/>
    public AdGroupCriterionReturnValue Result {
      get {
        this.RaiseExceptionIfNecessary();
        return ((AdGroupCriterionReturnValue) (this.results[0]));
      }
    }
  }
}
