//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace com.google.api.adwords.v200906.AdGroupAdService {
  using System.Diagnostics;
  using System.Web.Services;
  using System.ComponentModel;
  using System.Web.Services.Protocols;
  using System;
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Web.Services.WebServiceBindingAttribute(Name = "AdGroupAdServiceSoapBinding", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListReturnValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Operation))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComparableValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Stats))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Target))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Media))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Page))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatsSelector))]
  public partial class AdGroupAdService : System.Web.Services.Protocols.SoapHttpClientProtocol {

    private RequestHeader requestHeaderField;

    private ResponseHeader responseHeaderField;

    private System.Threading.SendOrPostCallback getOperationCompleted;

    private System.Threading.SendOrPostCallback mutateOperationCompleted;

    /// <remarks/>
    public AdGroupAdService() {
      this.Url = "https://adwords-sandbox.google.com/api/adwords/cm/v200906/AdGroupAdService";
    }

    public RequestHeader RequestHeader {
      get {
        return this.requestHeaderField;
      }
      set {
        this.requestHeaderField = value;
      }
    }

    public ResponseHeader ResponseHeader {
      get {
        return this.responseHeaderField;
      }
      set {
        this.responseHeaderField = value;
      }
    }

    /// <remarks/>
    public event getCompletedEventHandler getCompleted;

    /// <remarks/>
    public event mutateCompletedEventHandler mutateCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.Out)]
    [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://adwords.google.com/api/adwords/cm/v200906", ResponseNamespace = "https://adwords.google.com/api/adwords/cm/v200906", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("rval")]
    public AdGroupAdPage get(AdGroupAdSelector selector) {
      object[] results = this.Invoke("get", new object[] {
                        selector});
      return ((AdGroupAdPage) (results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult Beginget(AdGroupAdSelector selector, System.AsyncCallback callback, object asyncState) {
      return this.BeginInvoke("get", new object[] {
                        selector}, callback, asyncState);
    }

    /// <remarks/>
    public AdGroupAdPage Endget(System.IAsyncResult asyncResult) {
      object[] results = this.EndInvoke(asyncResult);
      return ((AdGroupAdPage) (results[0]));
    }

    /// <remarks/>
    public void getAsync(AdGroupAdSelector selector) {
      this.getAsync(selector, null);
    }

    /// <remarks/>
    public void getAsync(AdGroupAdSelector selector, object userState) {
      if ((this.getOperationCompleted == null)) {
        this.getOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOperationCompleted);
      }
      this.InvokeAsync("get", new object[] {
                        selector}, this.getOperationCompleted, userState);
    }

    private void OngetOperationCompleted(object arg) {
      if ((this.getCompleted != null)) {
        System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs) (arg));
        this.getCompleted(this, new getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
      }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.Out)]
    [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://adwords.google.com/api/adwords/cm/v200906", ResponseNamespace = "https://adwords.google.com/api/adwords/cm/v200906", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("rval")]
    public AdGroupAdReturnValue mutate([System.Xml.Serialization.XmlElementAttribute("operations")] AdGroupAdOperation[] operations) {
      object[] results = this.Invoke("mutate", new object[] {
                        operations});
      return ((AdGroupAdReturnValue) (results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult Beginmutate(AdGroupAdOperation[] operations, System.AsyncCallback callback, object asyncState) {
      return this.BeginInvoke("mutate", new object[] {
                        operations}, callback, asyncState);
    }

    /// <remarks/>
    public AdGroupAdReturnValue Endmutate(System.IAsyncResult asyncResult) {
      object[] results = this.EndInvoke(asyncResult);
      return ((AdGroupAdReturnValue) (results[0]));
    }

    /// <remarks/>
    public void mutateAsync(AdGroupAdOperation[] operations) {
      this.mutateAsync(operations, null);
    }

    /// <remarks/>
    public void mutateAsync(AdGroupAdOperation[] operations, object userState) {
      if ((this.mutateOperationCompleted == null)) {
        this.mutateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmutateOperationCompleted);
      }
      this.InvokeAsync("mutate", new object[] {
                        operations}, this.mutateOperationCompleted, userState);
    }

    private void OnmutateOperationCompleted(object arg) {
      if ((this.mutateCompleted != null)) {
        System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs) (arg));
        this.mutateCompleted(this, new mutateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
      }
    }

    /// <remarks/>
    public new void CancelAsync(object userState) {
      base.CancelAsync(userState);
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdGroupAdReturnValue))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class ListReturnValue {

    private string listReturnValueTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ListReturnValue.Type")]
    public string ListReturnValueType {
      get {
        return this.listReturnValueTypeField;
      }
      set {
        this.listReturnValueTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdGroupAdReturnValue : ListReturnValue {

    private AdGroupAd[] valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("value")]
    public AdGroupAd[] value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdGroupAd {

    private long adGroupIdField;

    private bool adGroupIdFieldSpecified;

    private Ad adField;

    private AdGroupAdStatus statusField;

    private bool statusFieldSpecified;

    private AdStats statsField;

    /// <remarks/>
    public long adGroupId {
      get {
        return this.adGroupIdField;
      }
      set {
        this.adGroupIdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool adGroupIdSpecified {
      get {
        return this.adGroupIdFieldSpecified;
      }
      set {
        this.adGroupIdFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Ad ad {
      get {
        return this.adField;
      }
      set {
        this.adField = value;
      }
    }

    /// <remarks/>
    public AdGroupAdStatus status {
      get {
        return this.statusField;
      }
      set {
        this.statusField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
      get {
        return this.statusFieldSpecified;
      }
      set {
        this.statusFieldSpecified = value;
      }
    }

    /// <remarks/>
    public AdStats stats {
      get {
        return this.statsField;
      }
      set {
        this.statsField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(LocalBusinessAd))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImageAd))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(MobileImageAd))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextAd))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(MobileAd))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Ad {

    private long idField;

    private bool idFieldSpecified;

    private string urlField;

    private string displayUrlField;

    private AdApprovalStatus approvalStatusField;

    private bool approvalStatusFieldSpecified;

    private string[] disapprovalReasonsField;

    private string adTypeField;

    /// <remarks/>
    public long id {
      get {
        return this.idField;
      }
      set {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
      get {
        return this.idFieldSpecified;
      }
      set {
        this.idFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string url {
      get {
        return this.urlField;
      }
      set {
        this.urlField = value;
      }
    }

    /// <remarks/>
    public string displayUrl {
      get {
        return this.displayUrlField;
      }
      set {
        this.displayUrlField = value;
      }
    }

    /// <remarks/>
    public AdApprovalStatus approvalStatus {
      get {
        return this.approvalStatusField;
      }
      set {
        this.approvalStatusField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool approvalStatusSpecified {
      get {
        return this.approvalStatusFieldSpecified;
      }
      set {
        this.approvalStatusFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("disapprovalReasons")]
    public string[] disapprovalReasons {
      get {
        return this.disapprovalReasonsField;
      }
      set {
        this.disapprovalReasonsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ad.Type")]
    public string AdType {
      get {
        return this.adTypeField;
      }
      set {
        this.adTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Ad.ApprovalStatus", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum AdApprovalStatus {

    /// <remarks/>
    APPROVED,

    /// <remarks/>
    FAMILY_SAFE,

    /// <remarks/>
    NON_FAMILY_SAFE,

    /// <remarks/>
    PORN,

    /// <remarks/>
    UNCHECKED,

    /// <remarks/>
    AUTO_GENERATED,

    /// <remarks/>
    NOT_READY_FOR_APPROVAL,

    /// <remarks/>
    SUSPICIOUS,

    /// <remarks/>
    FORBIDDEN,

    /// <remarks/>
    DISABLED,

    /// <remarks/>
    DISAPPROVED,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class LocalBusinessAd : Ad {

    private string fullBusinessNameField;

    private string phoneNumberField;

    private string streetAddressField;

    private string cityField;

    private string regionField;

    private string regionCodeField;

    private string postalCodeField;

    private string countryCodeField;

    private string businessNameField;

    private string description1Field;

    private string description2Field;

    private ProximityTarget targetField;

    private Image businessImageField;

    private Image iconField;

    /// <remarks/>
    public string fullBusinessName {
      get {
        return this.fullBusinessNameField;
      }
      set {
        this.fullBusinessNameField = value;
      }
    }

    /// <remarks/>
    public string phoneNumber {
      get {
        return this.phoneNumberField;
      }
      set {
        this.phoneNumberField = value;
      }
    }

    /// <remarks/>
    public string streetAddress {
      get {
        return this.streetAddressField;
      }
      set {
        this.streetAddressField = value;
      }
    }

    /// <remarks/>
    public string city {
      get {
        return this.cityField;
      }
      set {
        this.cityField = value;
      }
    }

    /// <remarks/>
    public string region {
      get {
        return this.regionField;
      }
      set {
        this.regionField = value;
      }
    }

    /// <remarks/>
    public string regionCode {
      get {
        return this.regionCodeField;
      }
      set {
        this.regionCodeField = value;
      }
    }

    /// <remarks/>
    public string postalCode {
      get {
        return this.postalCodeField;
      }
      set {
        this.postalCodeField = value;
      }
    }

    /// <remarks/>
    public string countryCode {
      get {
        return this.countryCodeField;
      }
      set {
        this.countryCodeField = value;
      }
    }

    /// <remarks/>
    public string businessName {
      get {
        return this.businessNameField;
      }
      set {
        this.businessNameField = value;
      }
    }

    /// <remarks/>
    public string description1 {
      get {
        return this.description1Field;
      }
      set {
        this.description1Field = value;
      }
    }

    /// <remarks/>
    public string description2 {
      get {
        return this.description2Field;
      }
      set {
        this.description2Field = value;
      }
    }

    /// <remarks/>
    public ProximityTarget target {
      get {
        return this.targetField;
      }
      set {
        this.targetField = value;
      }
    }

    /// <remarks/>
    public Image businessImage {
      get {
        return this.businessImageField;
      }
      set {
        this.businessImageField = value;
      }
    }

    /// <remarks/>
    public Image icon {
      get {
        return this.iconField;
      }
      set {
        this.iconField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class ProximityTarget : GeoTarget {

    private GeoPoint geoPointField;

    private ProximityTargetDistanceUnits radiusDistanceUnitsField;

    private bool radiusDistanceUnitsFieldSpecified;

    private double radiusInUnitsField;

    private bool radiusInUnitsFieldSpecified;

    private Address addressField;

    private bool allowServiceOfAddressField;

    private bool allowServiceOfAddressFieldSpecified;

    /// <remarks/>
    public GeoPoint geoPoint {
      get {
        return this.geoPointField;
      }
      set {
        this.geoPointField = value;
      }
    }

    /// <remarks/>
    public ProximityTargetDistanceUnits radiusDistanceUnits {
      get {
        return this.radiusDistanceUnitsField;
      }
      set {
        this.radiusDistanceUnitsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool radiusDistanceUnitsSpecified {
      get {
        return this.radiusDistanceUnitsFieldSpecified;
      }
      set {
        this.radiusDistanceUnitsFieldSpecified = value;
      }
    }

    /// <remarks/>
    public double radiusInUnits {
      get {
        return this.radiusInUnitsField;
      }
      set {
        this.radiusInUnitsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool radiusInUnitsSpecified {
      get {
        return this.radiusInUnitsFieldSpecified;
      }
      set {
        this.radiusInUnitsFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Address address {
      get {
        return this.addressField;
      }
      set {
        this.addressField = value;
      }
    }

    /// <remarks/>
    public bool allowServiceOfAddress {
      get {
        return this.allowServiceOfAddressField;
      }
      set {
        this.allowServiceOfAddressField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool allowServiceOfAddressSpecified {
      get {
        return this.allowServiceOfAddressFieldSpecified;
      }
      set {
        this.allowServiceOfAddressFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class GeoPoint {

    private int latitudeInMicroDegreesField;

    private bool latitudeInMicroDegreesFieldSpecified;

    private int longitudeInMicroDegreesField;

    private bool longitudeInMicroDegreesFieldSpecified;

    /// <remarks/>
    public int latitudeInMicroDegrees {
      get {
        return this.latitudeInMicroDegreesField;
      }
      set {
        this.latitudeInMicroDegreesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeInMicroDegreesSpecified {
      get {
        return this.latitudeInMicroDegreesFieldSpecified;
      }
      set {
        this.latitudeInMicroDegreesFieldSpecified = value;
      }
    }

    /// <remarks/>
    public int longitudeInMicroDegrees {
      get {
        return this.longitudeInMicroDegreesField;
      }
      set {
        this.longitudeInMicroDegreesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeInMicroDegreesSpecified {
      get {
        return this.longitudeInMicroDegreesFieldSpecified;
      }
      set {
        this.longitudeInMicroDegreesFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ProximityTarget.DistanceUnits", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum ProximityTargetDistanceUnits {

    /// <remarks/>
    KILOMETERS,

    /// <remarks/>
    MILES,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Address {

    private string streetAddressField;

    private string streetAddress2Field;

    private string cityNameField;

    private string provinceCodeField;

    private string provinceNameField;

    private string postalCodeField;

    private string countryCodeField;

    /// <remarks/>
    public string streetAddress {
      get {
        return this.streetAddressField;
      }
      set {
        this.streetAddressField = value;
      }
    }

    /// <remarks/>
    public string streetAddress2 {
      get {
        return this.streetAddress2Field;
      }
      set {
        this.streetAddress2Field = value;
      }
    }

    /// <remarks/>
    public string cityName {
      get {
        return this.cityNameField;
      }
      set {
        this.cityNameField = value;
      }
    }

    /// <remarks/>
    public string provinceCode {
      get {
        return this.provinceCodeField;
      }
      set {
        this.provinceCodeField = value;
      }
    }

    /// <remarks/>
    public string provinceName {
      get {
        return this.provinceNameField;
      }
      set {
        this.provinceNameField = value;
      }
    }

    /// <remarks/>
    public string postalCode {
      get {
        return this.postalCodeField;
      }
      set {
        this.postalCodeField = value;
      }
    }

    /// <remarks/>
    public string countryCode {
      get {
        return this.countryCodeField;
      }
      set {
        this.countryCodeField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProximityTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProvinceTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(MetroTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(CityTarget))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class GeoTarget : Target {

    private bool excludedField;

    private bool excludedFieldSpecified;

    /// <remarks/>
    public bool excluded {
      get {
        return this.excludedField;
      }
      set {
        this.excludedField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool excludedSpecified {
      get {
        return this.excludedFieldSpecified;
      }
      set {
        this.excludedFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(GeoTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProximityTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProvinceTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(MetroTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(CityTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(DemographicTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenderTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgeTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlatformTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(NetworkTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(LanguageTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdScheduleTarget))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class Target {

    private string targetTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target.Type")]
    public string TargetType {
      get {
        return this.targetTypeField;
      }
      set {
        this.targetTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenderTarget))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgeTarget))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class DemographicTarget : Target {

    private int bidModifierField;

    private bool bidModifierFieldSpecified;

    /// <remarks/>
    public int bidModifier {
      get {
        return this.bidModifierField;
      }
      set {
        this.bidModifierField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bidModifierSpecified {
      get {
        return this.bidModifierFieldSpecified;
      }
      set {
        this.bidModifierFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class GenderTarget : DemographicTarget {

    private GenderTargetGender genderField;

    private bool genderFieldSpecified;

    /// <remarks/>
    public GenderTargetGender gender {
      get {
        return this.genderField;
      }
      set {
        this.genderField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool genderSpecified {
      get {
        return this.genderFieldSpecified;
      }
      set {
        this.genderFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "GenderTarget.Gender", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum GenderTargetGender {

    /// <remarks/>
    MALE,

    /// <remarks/>
    FEMALE,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AgeTarget : DemographicTarget {

    private AgeTargetAge ageField;

    private bool ageFieldSpecified;

    /// <remarks/>
    public AgeTargetAge age {
      get {
        return this.ageField;
      }
      set {
        this.ageField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ageSpecified {
      get {
        return this.ageFieldSpecified;
      }
      set {
        this.ageFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "AgeTarget.Age", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum AgeTargetAge {

    /// <remarks/>
    AGE_0_17,

    /// <remarks/>
    AGE_18_24,

    /// <remarks/>
    AGE_25_34,

    /// <remarks/>
    AGE_35_44,

    /// <remarks/>
    AGE_45_54,

    /// <remarks/>
    AGE_55_64,

    /// <remarks/>
    AGE_65_PLUS,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class PlatformTarget : Target {

    private PlatformType platformTypeField;

    private bool platformTypeFieldSpecified;

    /// <remarks/>
    public PlatformType platformType {
      get {
        return this.platformTypeField;
      }
      set {
        this.platformTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool platformTypeSpecified {
      get {
        return this.platformTypeFieldSpecified;
      }
      set {
        this.platformTypeFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum PlatformType {

    /// <remarks/>
    DESKTOP,

    /// <remarks/>
    HIGH_END_MOBILE,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class NetworkTarget : Target {

    private NetworkCoverageType networkCoverageTypeField;

    private bool networkCoverageTypeFieldSpecified;

    /// <remarks/>
    public NetworkCoverageType networkCoverageType {
      get {
        return this.networkCoverageTypeField;
      }
      set {
        this.networkCoverageTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool networkCoverageTypeSpecified {
      get {
        return this.networkCoverageTypeFieldSpecified;
      }
      set {
        this.networkCoverageTypeFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum NetworkCoverageType {

    /// <remarks/>
    GOOGLE_SEARCH,

    /// <remarks/>
    SEARCH_NETWORK,

    /// <remarks/>
    CONTENT_NETWORK,

    /// <remarks/>
    CONTENT_CONTEXTUAL,

    /// <remarks/>
    CPA_REFERRAL,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class LanguageTarget : Target {

    private string languageCodeField;

    /// <remarks/>
    public string languageCode {
      get {
        return this.languageCodeField;
      }
      set {
        this.languageCodeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdScheduleTarget : Target {

    private DayOfWeek dayOfWeekField;

    private bool dayOfWeekFieldSpecified;

    private int startHourField;

    private bool startHourFieldSpecified;

    private MinuteOfHour startMinuteField;

    private bool startMinuteFieldSpecified;

    private int endHourField;

    private bool endHourFieldSpecified;

    private MinuteOfHour endMinuteField;

    private bool endMinuteFieldSpecified;

    private double bidMultiplierField;

    private bool bidMultiplierFieldSpecified;

    /// <remarks/>
    public DayOfWeek dayOfWeek {
      get {
        return this.dayOfWeekField;
      }
      set {
        this.dayOfWeekField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dayOfWeekSpecified {
      get {
        return this.dayOfWeekFieldSpecified;
      }
      set {
        this.dayOfWeekFieldSpecified = value;
      }
    }

    /// <remarks/>
    public int startHour {
      get {
        return this.startHourField;
      }
      set {
        this.startHourField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startHourSpecified {
      get {
        return this.startHourFieldSpecified;
      }
      set {
        this.startHourFieldSpecified = value;
      }
    }

    /// <remarks/>
    public MinuteOfHour startMinute {
      get {
        return this.startMinuteField;
      }
      set {
        this.startMinuteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startMinuteSpecified {
      get {
        return this.startMinuteFieldSpecified;
      }
      set {
        this.startMinuteFieldSpecified = value;
      }
    }

    /// <remarks/>
    public int endHour {
      get {
        return this.endHourField;
      }
      set {
        this.endHourField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endHourSpecified {
      get {
        return this.endHourFieldSpecified;
      }
      set {
        this.endHourFieldSpecified = value;
      }
    }

    /// <remarks/>
    public MinuteOfHour endMinute {
      get {
        return this.endMinuteField;
      }
      set {
        this.endMinuteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endMinuteSpecified {
      get {
        return this.endMinuteFieldSpecified;
      }
      set {
        this.endMinuteFieldSpecified = value;
      }
    }

    /// <remarks/>
    public double bidMultiplier {
      get {
        return this.bidMultiplierField;
      }
      set {
        this.bidMultiplierField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bidMultiplierSpecified {
      get {
        return this.bidMultiplierFieldSpecified;
      }
      set {
        this.bidMultiplierFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum DayOfWeek {

    /// <remarks/>
    MONDAY,

    /// <remarks/>
    TUESDAY,

    /// <remarks/>
    WEDNESDAY,

    /// <remarks/>
    THURSDAY,

    /// <remarks/>
    FRIDAY,

    /// <remarks/>
    SATURDAY,

    /// <remarks/>
    SUNDAY,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum MinuteOfHour {

    /// <remarks/>
    ZERO,

    /// <remarks/>
    FIFTEEN,

    /// <remarks/>
    THIRTY,

    /// <remarks/>
    FORTY_FIVE,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class ProvinceTarget : GeoTarget {

    private string provinceCodeField;

    /// <remarks/>
    public string provinceCode {
      get {
        return this.provinceCodeField;
      }
      set {
        this.provinceCodeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class PolygonTarget : GeoTarget {

    private GeoPoint[] verticesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("vertices")]
    public GeoPoint[] vertices {
      get {
        return this.verticesField;
      }
      set {
        this.verticesField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class MetroTarget : GeoTarget {

    private string metroCodeField;

    /// <remarks/>
    public string metroCode {
      get {
        return this.metroCodeField;
      }
      set {
        this.metroCodeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class CountryTarget : GeoTarget {

    private string countryCodeField;

    /// <remarks/>
    public string countryCode {
      get {
        return this.countryCodeField;
      }
      set {
        this.countryCodeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class CityTarget : GeoTarget {

    private string cityNameField;

    private string provinceCodeField;

    private string countryCodeField;

    /// <remarks/>
    public string cityName {
      get {
        return this.cityNameField;
      }
      set {
        this.cityNameField = value;
      }
    }

    /// <remarks/>
    public string provinceCode {
      get {
        return this.provinceCodeField;
      }
      set {
        this.provinceCodeField = value;
      }
    }

    /// <remarks/>
    public string countryCode {
      get {
        return this.countryCodeField;
      }
      set {
        this.countryCodeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Image : Media {

    private byte[] dataField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] data {
      get {
        return this.dataField;
      }
      set {
        this.dataField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Video))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Image))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Media {

    private long mediaIdField;

    private bool mediaIdFieldSpecified;

    private MediaMediaType mediaTypeDbField;

    private bool mediaTypeDbFieldSpecified;

    private long referenceIdField;

    private bool referenceIdFieldSpecified;

    private Media_Size_DimensionsMapEntry[] dimensionsField;

    private Media_Size_StringMapEntry[] urlsField;

    private MediaMimeType mimeTypeField;

    private bool mimeTypeFieldSpecified;

    private string sourceUrlField;

    private MediaMediaSubType mediaSubTypeField;

    private bool mediaSubTypeFieldSpecified;

    private string nameField;

    private long fileSizeField;

    private bool fileSizeFieldSpecified;

    private Media_MediaExtendedCapabilityType_Media_MediaExtendedCapabilityStateMapEntry[] extendedCapabilitiesField;

    private string creationTimeField;

    private string mediaTypeField;

    /// <remarks/>
    public long mediaId {
      get {
        return this.mediaIdField;
      }
      set {
        this.mediaIdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool mediaIdSpecified {
      get {
        return this.mediaIdFieldSpecified;
      }
      set {
        this.mediaIdFieldSpecified = value;
      }
    }

    /// <remarks/>
    public MediaMediaType mediaTypeDb {
      get {
        return this.mediaTypeDbField;
      }
      set {
        this.mediaTypeDbField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool mediaTypeDbSpecified {
      get {
        return this.mediaTypeDbFieldSpecified;
      }
      set {
        this.mediaTypeDbFieldSpecified = value;
      }
    }

    /// <remarks/>
    public long referenceId {
      get {
        return this.referenceIdField;
      }
      set {
        this.referenceIdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool referenceIdSpecified {
      get {
        return this.referenceIdFieldSpecified;
      }
      set {
        this.referenceIdFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dimensions")]
    public Media_Size_DimensionsMapEntry[] dimensions {
      get {
        return this.dimensionsField;
      }
      set {
        this.dimensionsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("urls")]
    public Media_Size_StringMapEntry[] urls {
      get {
        return this.urlsField;
      }
      set {
        this.urlsField = value;
      }
    }

    /// <remarks/>
    public MediaMimeType mimeType {
      get {
        return this.mimeTypeField;
      }
      set {
        this.mimeTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool mimeTypeSpecified {
      get {
        return this.mimeTypeFieldSpecified;
      }
      set {
        this.mimeTypeFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string sourceUrl {
      get {
        return this.sourceUrlField;
      }
      set {
        this.sourceUrlField = value;
      }
    }

    /// <remarks/>
    public MediaMediaSubType mediaSubType {
      get {
        return this.mediaSubTypeField;
      }
      set {
        this.mediaSubTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool mediaSubTypeSpecified {
      get {
        return this.mediaSubTypeFieldSpecified;
      }
      set {
        this.mediaSubTypeFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }

    /// <remarks/>
    public long fileSize {
      get {
        return this.fileSizeField;
      }
      set {
        this.fileSizeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fileSizeSpecified {
      get {
        return this.fileSizeFieldSpecified;
      }
      set {
        this.fileSizeFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("extendedCapabilities")]
    public Media_MediaExtendedCapabilityType_Media_MediaExtendedCapabilityStateMapEntry[] extendedCapabilities {
      get {
        return this.extendedCapabilitiesField;
      }
      set {
        this.extendedCapabilitiesField = value;
      }
    }

    /// <remarks/>
    public string creationTime {
      get {
        return this.creationTimeField;
      }
      set {
        this.creationTimeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Media.Type")]
    public string MediaType {
      get {
        return this.mediaTypeField;
      }
      set {
        this.mediaTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Media.MediaType", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum MediaMediaType {

    /// <remarks/>
    AUDIO,

    /// <remarks/>
    DYNAMIC_IMAGE,

    /// <remarks/>
    HTML,

    /// <remarks/>
    ICON,

    /// <remarks/>
    IMAGE,

    /// <remarks/>
    STANDARD_ICON,

    /// <remarks/>
    VIDEO,

    /// <remarks/>
    VIDEO_IMAGE,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Media_Size_DimensionsMapEntry {

    private MediaSize keyField;

    private bool keyFieldSpecified;

    private Dimensions valueField;

    /// <remarks/>
    public MediaSize key {
      get {
        return this.keyField;
      }
      set {
        this.keyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keySpecified {
      get {
        return this.keyFieldSpecified;
      }
      set {
        this.keyFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Dimensions value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Media.Size", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum MediaSize {

    /// <remarks/>
    FULL,

    /// <remarks/>
    SHRUNKEN,

    /// <remarks/>
    PREVIEW,

    /// <remarks/>
    VIDEO_THUMBNAIL,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Dimensions {

    private int widthField;

    private bool widthFieldSpecified;

    private int heightField;

    private bool heightFieldSpecified;

    /// <remarks/>
    public int width {
      get {
        return this.widthField;
      }
      set {
        this.widthField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool widthSpecified {
      get {
        return this.widthFieldSpecified;
      }
      set {
        this.widthFieldSpecified = value;
      }
    }

    /// <remarks/>
    public int height {
      get {
        return this.heightField;
      }
      set {
        this.heightField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool heightSpecified {
      get {
        return this.heightFieldSpecified;
      }
      set {
        this.heightFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Media_Size_StringMapEntry {

    private MediaSize keyField;

    private bool keyFieldSpecified;

    private string valueField;

    /// <remarks/>
    public MediaSize key {
      get {
        return this.keyField;
      }
      set {
        this.keyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keySpecified {
      get {
        return this.keyFieldSpecified;
      }
      set {
        this.keyFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Media.MimeType", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum MediaMimeType {

    /// <remarks/>
    IMAGE_JPEG,

    /// <remarks/>
    IMAGE_GIF,

    /// <remarks/>
    IMAGE_PNG,

    /// <remarks/>
    FLASH,

    /// <remarks/>
    TEXT_HTML,

    /// <remarks/>
    PDF,

    /// <remarks/>
    MSWORD,

    /// <remarks/>
    MSEXCEL,

    /// <remarks/>
    RTF,

    /// <remarks/>
    AUDIO_WAV,

    /// <remarks/>
    AUDIO_MP3,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Media.MediaSubType", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum MediaMediaSubType {

    /// <remarks/>
    GOOGLE_HOSTED,

    /// <remarks/>
    YOU_TUBE_HOSTED,

    /// <remarks/>
    IRS_STORED,

    /// <remarks/>
    ADS_DB_STORED,

    /// <remarks/>
    AMS_STORED,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Media_MediaExtendedCapabilityType_Media_MediaExtendedCapabilityStateMapEntry {

    private MediaMediaExtendedCapabilityType keyField;

    private bool keyFieldSpecified;

    private MediaMediaExtendedCapabilityState valueField;

    private bool valueFieldSpecified;

    /// <remarks/>
    public MediaMediaExtendedCapabilityType key {
      get {
        return this.keyField;
      }
      set {
        this.keyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keySpecified {
      get {
        return this.keyFieldSpecified;
      }
      set {
        this.keyFieldSpecified = value;
      }
    }

    /// <remarks/>
    public MediaMediaExtendedCapabilityState value {
      get {
        return this.valueField;
      }
      set {
        this.valueField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valueSpecified {
      get {
        return this.valueFieldSpecified;
      }
      set {
        this.valueFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Media.MediaExtendedCapabilityType", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum MediaMediaExtendedCapabilityType {

    /// <remarks/>
    MPEG2_PROGRAM_STREAM_SD,

    /// <remarks/>
    MPEG2_PROGRAM_STREAM_SD_WITH_BLACK,

    /// <remarks/>
    MPEG2_TRANSPORT_STREAM_SD,

    /// <remarks/>
    GXF_SD,

    /// <remarks/>
    FLV_320,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Media.MediaExtendedCapabilityState", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum MediaMediaExtendedCapabilityState {

    /// <remarks/>
    UNKNOWN,

    /// <remarks/>
    SUPPORTED,

    /// <remarks/>
    NOT_SUPPORTED,

    /// <remarks/>
    PASSED_PREREQ,

    /// <remarks/>
    FAILED_PREREQ,

    /// <remarks/>
    MEETS_CRITERIA,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Video : Media {

    private long durationMillisField;

    private bool durationMillisFieldSpecified;

    private string streamingUrlField;

    private bool readyToPlayOnTheWebField;

    private bool readyToPlayOnTheWebFieldSpecified;

    /// <remarks/>
    public long durationMillis {
      get {
        return this.durationMillisField;
      }
      set {
        this.durationMillisField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool durationMillisSpecified {
      get {
        return this.durationMillisFieldSpecified;
      }
      set {
        this.durationMillisFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string streamingUrl {
      get {
        return this.streamingUrlField;
      }
      set {
        this.streamingUrlField = value;
      }
    }

    /// <remarks/>
    public bool readyToPlayOnTheWeb {
      get {
        return this.readyToPlayOnTheWebField;
      }
      set {
        this.readyToPlayOnTheWebField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool readyToPlayOnTheWebSpecified {
      get {
        return this.readyToPlayOnTheWebFieldSpecified;
      }
      set {
        this.readyToPlayOnTheWebFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class ImageAd : Ad {

    private Image imageField;

    private string nameField;

    /// <remarks/>
    public Image image {
      get {
        return this.imageField;
      }
      set {
        this.imageField = value;
      }
    }

    /// <remarks/>
    public string name {
      get {
        return this.nameField;
      }
      set {
        this.nameField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class MobileImageAd : Ad {

    private MarkupLanguageType[] markupLanguagesField;

    private string[] mobileCarriersField;

    private Image imageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("markupLanguages")]
    public MarkupLanguageType[] markupLanguages {
      get {
        return this.markupLanguagesField;
      }
      set {
        this.markupLanguagesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mobileCarriers")]
    public string[] mobileCarriers {
      get {
        return this.mobileCarriersField;
      }
      set {
        this.mobileCarriersField = value;
      }
    }

    /// <remarks/>
    public Image image {
      get {
        return this.imageField;
      }
      set {
        this.imageField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum MarkupLanguageType {

    /// <remarks/>
    HTML,

    /// <remarks/>
    CHTML,

    /// <remarks/>
    XHTML,

    /// <remarks/>
    WML,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class TextAd : Ad {

    private string headlineField;

    private string description1Field;

    private string description2Field;

    /// <remarks/>
    public string headline {
      get {
        return this.headlineField;
      }
      set {
        this.headlineField = value;
      }
    }

    /// <remarks/>
    public string description1 {
      get {
        return this.description1Field;
      }
      set {
        this.description1Field = value;
      }
    }

    /// <remarks/>
    public string description2 {
      get {
        return this.description2Field;
      }
      set {
        this.description2Field = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class MobileAd : Ad {

    private string headlineField;

    private string descriptionField;

    private MarkupLanguageType[] markupLanguagesField;

    private string[] mobileCarriersField;

    private string businessNameField;

    private string countryCodeField;

    private string phoneNumberField;

    /// <remarks/>
    public string headline {
      get {
        return this.headlineField;
      }
      set {
        this.headlineField = value;
      }
    }

    /// <remarks/>
    public string description {
      get {
        return this.descriptionField;
      }
      set {
        this.descriptionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("markupLanguages")]
    public MarkupLanguageType[] markupLanguages {
      get {
        return this.markupLanguagesField;
      }
      set {
        this.markupLanguagesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mobileCarriers")]
    public string[] mobileCarriers {
      get {
        return this.mobileCarriersField;
      }
      set {
        this.mobileCarriersField = value;
      }
    }

    /// <remarks/>
    public string businessName {
      get {
        return this.businessNameField;
      }
      set {
        this.businessNameField = value;
      }
    }

    /// <remarks/>
    public string countryCode {
      get {
        return this.countryCodeField;
      }
      set {
        this.countryCodeField = value;
      }
    }

    /// <remarks/>
    public string phoneNumber {
      get {
        return this.phoneNumberField;
      }
      set {
        this.phoneNumberField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "AdGroupAd.Status", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum AdGroupAdStatus {

    /// <remarks/>
    ENABLED,

    /// <remarks/>
    PAUSED,

    /// <remarks/>
    DISABLED,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdStats : Stats {

    private double percentServedField;

    private bool percentServedFieldSpecified;

    /// <remarks/>
    public double percentServed {
      get {
        return this.percentServedField;
      }
      set {
        this.percentServedField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool percentServedSpecified {
      get {
        return this.percentServedFieldSpecified;
      }
      set {
        this.percentServedFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdStats))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdExtensionOverrideStats))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Stats {

    private string startDateField;

    private string endDateField;

    private StatsNetwork networkField;

    private bool networkFieldSpecified;

    private long clicksField;

    private bool clicksFieldSpecified;

    private long impressionsField;

    private bool impressionsFieldSpecified;

    private Money costField;

    private double averagePositionField;

    private bool averagePositionFieldSpecified;

    private Money averageCpcField;

    private Money averageCpmField;

    private double ctrField;

    private bool ctrFieldSpecified;

    private long conversionsField;

    private bool conversionsFieldSpecified;

    private double conversionRateField;

    private bool conversionRateFieldSpecified;

    private Money costPerConversionField;

    private long conversionsManyPerClickField;

    private bool conversionsManyPerClickFieldSpecified;

    private double conversionRateManyPerClickField;

    private bool conversionRateManyPerClickFieldSpecified;

    private Money costPerConversionManyPerClickField;

    private string statsTypeField;

    /// <remarks/>
    public string startDate {
      get {
        return this.startDateField;
      }
      set {
        this.startDateField = value;
      }
    }

    /// <remarks/>
    public string endDate {
      get {
        return this.endDateField;
      }
      set {
        this.endDateField = value;
      }
    }

    /// <remarks/>
    public StatsNetwork network {
      get {
        return this.networkField;
      }
      set {
        this.networkField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool networkSpecified {
      get {
        return this.networkFieldSpecified;
      }
      set {
        this.networkFieldSpecified = value;
      }
    }

    /// <remarks/>
    public long clicks {
      get {
        return this.clicksField;
      }
      set {
        this.clicksField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool clicksSpecified {
      get {
        return this.clicksFieldSpecified;
      }
      set {
        this.clicksFieldSpecified = value;
      }
    }

    /// <remarks/>
    public long impressions {
      get {
        return this.impressionsField;
      }
      set {
        this.impressionsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool impressionsSpecified {
      get {
        return this.impressionsFieldSpecified;
      }
      set {
        this.impressionsFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Money cost {
      get {
        return this.costField;
      }
      set {
        this.costField = value;
      }
    }

    /// <remarks/>
    public double averagePosition {
      get {
        return this.averagePositionField;
      }
      set {
        this.averagePositionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averagePositionSpecified {
      get {
        return this.averagePositionFieldSpecified;
      }
      set {
        this.averagePositionFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Money averageCpc {
      get {
        return this.averageCpcField;
      }
      set {
        this.averageCpcField = value;
      }
    }

    /// <remarks/>
    public Money averageCpm {
      get {
        return this.averageCpmField;
      }
      set {
        this.averageCpmField = value;
      }
    }

    /// <remarks/>
    public double ctr {
      get {
        return this.ctrField;
      }
      set {
        this.ctrField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ctrSpecified {
      get {
        return this.ctrFieldSpecified;
      }
      set {
        this.ctrFieldSpecified = value;
      }
    }

    /// <remarks/>
    public long conversions {
      get {
        return this.conversionsField;
      }
      set {
        this.conversionsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conversionsSpecified {
      get {
        return this.conversionsFieldSpecified;
      }
      set {
        this.conversionsFieldSpecified = value;
      }
    }

    /// <remarks/>
    public double conversionRate {
      get {
        return this.conversionRateField;
      }
      set {
        this.conversionRateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conversionRateSpecified {
      get {
        return this.conversionRateFieldSpecified;
      }
      set {
        this.conversionRateFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Money costPerConversion {
      get {
        return this.costPerConversionField;
      }
      set {
        this.costPerConversionField = value;
      }
    }

    /// <remarks/>
    public long conversionsManyPerClick {
      get {
        return this.conversionsManyPerClickField;
      }
      set {
        this.conversionsManyPerClickField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conversionsManyPerClickSpecified {
      get {
        return this.conversionsManyPerClickFieldSpecified;
      }
      set {
        this.conversionsManyPerClickFieldSpecified = value;
      }
    }

    /// <remarks/>
    public double conversionRateManyPerClick {
      get {
        return this.conversionRateManyPerClickField;
      }
      set {
        this.conversionRateManyPerClickField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conversionRateManyPerClickSpecified {
      get {
        return this.conversionRateManyPerClickFieldSpecified;
      }
      set {
        this.conversionRateManyPerClickFieldSpecified = value;
      }
    }

    /// <remarks/>
    public Money costPerConversionManyPerClick {
      get {
        return this.costPerConversionManyPerClickField;
      }
      set {
        this.costPerConversionManyPerClickField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Stats.Type")]
    public string StatsType {
      get {
        return this.statsTypeField;
      }
      set {
        this.statsTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Stats.Network", Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum StatsNetwork {

    /// <remarks/>
    SEARCH,

    /// <remarks/>
    GOOGLE_SEARCH,

    /// <remarks/>
    SEARCH_NETWORK,

    /// <remarks/>
    CONTENT,

    /// <remarks/>
    CONTENT_KEYWORD_BID,

    /// <remarks/>
    CONTENT_PLACEMENT_BID,

    /// <remarks/>
    ALL,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Money : ComparableValue {

    private long microAmountField;

    private bool microAmountFieldSpecified;

    /// <remarks/>
    public long microAmount {
      get {
        return this.microAmountField;
      }
      set {
        this.microAmountField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool microAmountSpecified {
      get {
        return this.microAmountFieldSpecified;
      }
      set {
        this.microAmountFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(NumberValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(LongValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(Money))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class ComparableValue {

    private string comparableValueTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ComparableValue.Type")]
    public string ComparableValueType {
      get {
        return this.comparableValueTypeField;
      }
      set {
        this.comparableValueTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(LongValue))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleValue))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class NumberValue : ComparableValue {
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class LongValue : NumberValue {

    private long numberField;

    private bool numberFieldSpecified;

    /// <remarks/>
    public long number {
      get {
        return this.numberField;
      }
      set {
        this.numberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numberSpecified {
      get {
        return this.numberFieldSpecified;
      }
      set {
        this.numberFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class DoubleValue : NumberValue {

    private double numberField;

    private bool numberFieldSpecified;

    /// <remarks/>
    public double number {
      get {
        return this.numberField;
      }
      set {
        this.numberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numberSpecified {
      get {
        return this.numberFieldSpecified;
      }
      set {
        this.numberFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdExtensionOverrideStats : Stats {
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class PolicyViolationKey {

    private string policyNameField;

    private string violatingTextField;

    /// <remarks/>
    public string policyName {
      get {
        return this.policyNameField;
      }
      set {
        this.policyNameField = value;
      }
    }

    /// <remarks/>
    public string violatingText {
      get {
        return this.violatingTextField;
      }
      set {
        this.violatingTextField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class ExemptionRequest {

    private PolicyViolationKey keyField;

    /// <remarks/>
    public PolicyViolationKey key {
      get {
        return this.keyField;
      }
      set {
        this.keyField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdGroupAdOperation))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class Operation {

    private Operator operatorField;

    private bool operatorFieldSpecified;

    private string operationTypeField;

    /// <remarks/>
    public Operator @operator {
      get {
        return this.operatorField;
      }
      set {
        this.operatorField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool operatorSpecified {
      get {
        return this.operatorFieldSpecified;
      }
      set {
        this.operatorFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Operation.Type")]
    public string OperationType {
      get {
        return this.operationTypeField;
      }
      set {
        this.operationTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public enum Operator {

    /// <remarks/>
    ADD,

    /// <remarks/>
    REMOVE,

    /// <remarks/>
    SET,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdGroupAdOperation : Operation {

    private AdGroupAd operandField;

    private ExemptionRequest[] exemptionRequestsField;

    /// <remarks/>
    public AdGroupAd operand {
      get {
        return this.operandField;
      }
      set {
        this.operandField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("exemptionRequests")]
    public ExemptionRequest[] exemptionRequests {
      get {
        return this.exemptionRequestsField;
      }
      set {
        this.exemptionRequestsField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdGroupAdPage))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public abstract partial class Page {

    private int totalNumEntriesField;

    private bool totalNumEntriesFieldSpecified;

    private string pageTypeField;

    /// <remarks/>
    public int totalNumEntries {
      get {
        return this.totalNumEntriesField;
      }
      set {
        this.totalNumEntriesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalNumEntriesSpecified {
      get {
        return this.totalNumEntriesFieldSpecified;
      }
      set {
        this.totalNumEntriesFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Page.Type")]
    public string PageType {
      get {
        return this.pageTypeField;
      }
      set {
        this.pageTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdGroupAdPage : Page {

    private AdGroupAd[] entriesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("entries")]
    public AdGroupAd[] entries {
      get {
        return this.entriesField;
      }
      set {
        this.entriesField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class Paging {

    private int startIndexField;

    private bool startIndexFieldSpecified;

    private int numberResultsField;

    private bool numberResultsFieldSpecified;

    /// <remarks/>
    public int startIndex {
      get {
        return this.startIndexField;
      }
      set {
        this.startIndexField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startIndexSpecified {
      get {
        return this.startIndexFieldSpecified;
      }
      set {
        this.startIndexFieldSpecified = value;
      }
    }

    /// <remarks/>
    public int numberResults {
      get {
        return this.numberResultsField;
      }
      set {
        this.numberResultsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numberResultsSpecified {
      get {
        return this.numberResultsFieldSpecified;
      }
      set {
        this.numberResultsFieldSpecified = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class DateRange {

    private string minField;

    private string maxField;

    /// <remarks/>
    public string min {
      get {
        return this.minField;
      }
      set {
        this.minField = value;
      }
    }

    /// <remarks/>
    public string max {
      get {
        return this.maxField;
      }
      set {
        this.maxField = value;
      }
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdStatsSelector))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class StatsSelector {

    private DateRange dateRangeField;

    private string statsSelectorTypeField;

    /// <remarks/>
    public DateRange dateRange {
      get {
        return this.dateRangeField;
      }
      set {
        this.dateRangeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StatsSelector.Type")]
    public string StatsSelectorType {
      get {
        return this.statsSelectorTypeField;
      }
      set {
        this.statsSelectorTypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdStatsSelector : StatsSelector {
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://adwords.google.com/api/adwords/cm/v200906")]
  public partial class AdGroupAdSelector {

    private long[] campaignIdsField;

    private long[] adGroupIdsField;

    private long[] adIdsField;

    private AdStatsSelector statsSelectorField;

    private Paging pagingField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("campaignIds")]
    public long[] campaignIds {
      get {
        return this.campaignIdsField;
      }
      set {
        this.campaignIdsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adGroupIds")]
    public long[] adGroupIds {
      get {
        return this.adGroupIdsField;
      }
      set {
        this.adGroupIdsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adIds")]
    public long[] adIds {
      get {
        return this.adIdsField;
      }
      set {
        this.adIdsField = value;
      }
    }

    /// <remarks/>
    public AdStatsSelector statsSelector {
      get {
        return this.statsSelectorField;
      }
      set {
        this.statsSelectorField = value;
      }
    }

    /// <remarks/>
    public Paging paging {
      get {
        return this.pagingField;
      }
      set {
        this.pagingField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  public delegate void getCompletedEventHandler(object sender, getCompletedEventArgs e);

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  public partial class getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

    private object[] results;

    internal getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
      :
            base(exception, cancelled, userState) {
      this.results = results;
    }

    /// <remarks/>
    public AdGroupAdPage Result {
      get {
        this.RaiseExceptionIfNecessary();
        return ((AdGroupAdPage) (this.results[0]));
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  public delegate void mutateCompletedEventHandler(object sender, mutateCompletedEventArgs e);

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  public partial class mutateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

    private object[] results;

    internal mutateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
      :
            base(exception, cancelled, userState) {
      this.results = results;
    }

    /// <remarks/>
    public AdGroupAdReturnValue Result {
      get {
        this.RaiseExceptionIfNecessary();
        return ((AdGroupAdReturnValue) (this.results[0]));
      }
    }
  }
}
