//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Google.Api.Ads.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Google.Api.Ads.Common.CommonErrorMessages", typeof(CommonErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthToken login failed. See ErrorCode for more details..
        /// </summary>
        internal static string AuthTokenLoginFailed {
            get {
                return ResourceManager.GetString("AuthTokenLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required key &apos;client_email&apos; is missing in JSON secrets file..
        /// </summary>
        internal static string ClientEmailIsMissingInJsonFile {
            get {
                return ResourceManager.GetString("ClientEmailIsMissingInJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse value for setting name &apos;{0}&apos;. Value provided: &apos;{1}&apos;..
        /// </summary>
        internal static string ConfigSettingParseError {
            get {
                return ResourceManager.GetString("ConfigSettingParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be null.
        /// </summary>
        internal static string EmailCannotBeNull {
            get {
                return ResourceManager.GetString("EmailCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load JSON secrets file for service account configuration. See inner exception for details..
        /// </summary>
        internal static string FailedToLoadJsonSecretsFile {
            get {
                return ResourceManager.GetString("FailedToLoadJsonSecretsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse response from server. See inner exception for more details..
        /// </summary>
        internal static string FailedToParseAuthTokenException {
            get {
                return ResourceManager.GetString("FailedToParseAuthTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid stage for Soap message..
        /// </summary>
        internal static string InvalidStageForSoapMessage {
            get {
                return ResourceManager.GetString("InvalidStageForSoapMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse SOAP Document. Underlying error: {0}.
        /// </summary>
        internal static string MalformedSoap {
            get {
                return ResourceManager.GetString("MalformedSoap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate factoryType field in Type {0}.
        /// </summary>
        internal static string MissingFactoryType {
            get {
                return ResourceManager.GetString("MissingFactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth2 authorizationCode cannot be empty when fetching access token..
        /// </summary>
        internal static string OAuth2AuthorizationCodeIsEmpty {
            get {
                return ResourceManager.GetString("OAuth2AuthorizationCodeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth2 Offline mode should be true to refresh access token..
        /// </summary>
        internal static string OAuth2IsNotInOfflineMode {
            get {
                return ResourceManager.GetString("OAuth2IsNotInOfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load private key from specified JWT certificate..
        /// </summary>
        internal static string OAuth2JwtCertificateInvalid {
            get {
                return ResourceManager.GetString("OAuth2JwtCertificateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like your application is not configured to use OAuth2 properly. Required OAuth2 parameter {0} is missing. You may run Common\\Utils\\OAuth2TokenGenerator.cs to generate a default OAuth2 configuration..
        /// </summary>
        internal static string OAuth2ParameterErrorMessage {
            get {
                return ResourceManager.GetString("OAuth2ParameterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be null.
        /// </summary>
        internal static string PasswordCannotBeNull {
            get {
                return ResourceManager.GetString("PasswordCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required key &apos;private_key&apos; is missing in JSON secrets file..
        /// </summary>
        internal static string PrivateKeyIsMissingInJsonFile {
            get {
                return ResourceManager.GetString("PrivateKeyIsMissingInJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes not closed in csv record..
        /// </summary>
        internal static string QuotesNotClosedInCsvLine {
            get {
                return ResourceManager.GetString("QuotesNotClosedInCsvLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service cannot be null.
        /// </summary>
        internal static string ServiceCannotBeNull {
            get {
                return ResourceManager.GetString("ServiceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache signature cannot be null..
        /// </summary>
        internal static string SignatureCannotBeNull {
            get {
                return ResourceManager.GetString("SignatureCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source stream is not readable..
        /// </summary>
        internal static string SourceStreamIsNotReadable {
            get {
                return ResourceManager.GetString("SourceStreamIsNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start index should be less than end index..
        /// </summary>
        internal static string StartIndexShouldBeLessThanEndIndex {
            get {
                return ResourceManager.GetString("StartIndexShouldBeLessThanEndIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parameter should be greater than 0 and less than the length of text..
        /// </summary>
        internal static string StringIndexOutOfBounds {
            get {
                return ResourceManager.GetString("StringIndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target stream is not writable..
        /// </summary>
        internal static string TargetStreamIsNotWritable {
            get {
                return ResourceManager.GetString("TargetStreamIsNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to split cannot be null..
        /// </summary>
        internal static string TextCannotBeNull {
            get {
                return ResourceManager.GetString("TextCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown trace source : {0}..
        /// </summary>
        internal static string UnknownTraceSource {
            get {
                return ResourceManager.GetString("UnknownTraceSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered service type {0} was requested..
        /// </summary>
        internal static string UnregisteredServiceTypeRequested {
            get {
                return ResourceManager.GetString("UnregisteredServiceTypeRequested", resourceCulture);
            }
        }
    }
}
